### ISSUE TITLE
No easy way to access components of Vector*i

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/ogre#1043]
#### System Information
- Ogre Version: master/1.12.0
- Operating System / Platform: Debian GNU/Linux 9 (stretch)

#### Detailled description
I tried to access the components of a Vector*i like this:
`vec.x;vec.y;vec.z;vec.w`

However this didn't work.
It seems to me that this is only implemented for Ogre::Real vectors:
https://github.com/OGRECave/ogre/blob/e1c3732c51f9099bed10d36805b738015adc8f47/OgreMain/include/OgreVector.h#L270

Is there another way or is this part just not implemented yet?

**Comment by paroj** [comment]
vec[0], vec[1] ..

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
Is it planned to support `vec.x;vec.y;vec.z;vec.w` access on vectors which are not Ogre::Real vectors or does one need to implement an own solution for this?

**Comment by paroj** [comment]
what is the issue with using vec[0] instead of vec.x? the issue with the xyzw scheme is that you cannot iterate over it and id does not scale beyond 4d - therefore I would rather limit its usage..

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
> the issue with the xyzw scheme is that you cannot iterate over it and id does not scale beyond 4d

That sounds sensible.

> what is the issue with using vec[0] instead of vec.x?

To be honest, this is related to the following: OGRECave/scape#28
Previously, the xyzw scheme has been used there with the int vector type.

**Comment by paroj** [comment]
I think you can make your usecase work by declaring 
```cpp
template <> struct _OgreExport VectorBase<4, int> ...
```
before instantiating a Vector4i
