### ISSUE TITLE
How to compile ogre with Ubuntu?

### ISSUE THREAD

**Issue by hcGuyue** [OGRECave/ogre#1059]
#### System Information
- Ogre Version: :grey_question: 2.1
- Operating System / Platform: :grey_question: Ubuntu 16.04 
- RenderSystem: :grey_question:

#### Detailled description

I am new to Ogre. After I downloading Ogre 2.1 from this github, I cannot configure  correctly with cmake whose version is 3.5.  I always got 2 errors of configuration. The one is "CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'". 
And the other one is "/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a2d55.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
  8 Linking C executable cmTC_a2d55
  7 /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a2d55.dir/link.txt --verbose=1
  6 /usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_a2d55.dir/CheckFunctionExists.c.o  -o cmTC_a2d55 -rdynamic -lpthreads
  5 /usr/bin/ld: cannot find -lpthreads"
Does anyone know how to fix these problems?

**Comment by AllianceDarkSylinc** [comment]
Hi!
See [Setting up Linux](https://ogrecave.github.io/ogre/api/2.1/_setting_up_ogre_linux.html)

How are you running your CMake commands?

**Comment by darksylinc** [comment]
Hi!
See [Setting up Linux](https://ogrecave.github.io/ogre/api/2.1/_setting_up_ogre_linux.html)

How are you running your CMake commands?

**Comment by hcGuyue** [comment]
> Hi!
> See [Setting up Linux](https://ogrecave.github.io/ogre/api/2.1/_setting_up_ogre_linux.html)
> 
> How are you running your CMake commands?

I run the cmake like cmake -G"Unix Makefiles" -S path/to/ogre.  This errors also happen when I make the  ogre 1.11.5 following the guide in https://ogrecave.github.io/ogre/api/latest/building-ogre.html .  I tried to configure the cmake in command line.  I wonder if something is wrong in my steps.

**Comment by darksylinc** [comment]
Try running this script:

```
#!/bin/bash
mkdir Test
cd Test
mkdir ogredeps
echo "--- Cloning Ogredeps ---"
hg clone https://bitbucket.org/cabalistic/ogredeps ogredeps
cd ogredeps
mkdir build
cd build
cmake -G Ninja ..
echo "--- Building Ogredeps ---"
ninja
ninja install
cd ../../
mkdir ogre
echo "--- Cloning Ogre 2.1 ---"
hg clone https://bitbucket.org/sinbad/ogre -r v2-1 ogre
cd ogre
ln -s ../ogredeps/build/ogredeps Dependencies
mkdir -p build/Debug
mkdir -p build/Release
cd build/Debug
echo "--- Building Ogre (Debug) ---"
cmake -D OGRE_USE_BOOST=0 -D OGRE_CONFIG_THREAD_PROVIDER=0 -D OGRE_CONFIG_THREADS=0 -D OGRE_BUILD_COMPONENT_SCENE_FORMAT=1 -D OGRE_BUILD_SAMPLES2=1 -D OGRE_BUILD_TESTS=0 -D CMAKE_BUILD_TYPE="Debug" -G Ninja ../..
ninja
cd ../Release
echo "--- Building Ogre (Release) ---"
cmake -D OGRE_USE_BOOST=0 -D OGRE_CONFIG_THREAD_PROVIDER=0 -D OGRE_CONFIG_THREADS=0 -D OGRE_BUILD_COMPONENT_SCENE_FORMAT=1 -D OGRE_BUILD_SAMPLES2=1 -D OGRE_BUILD_TESTS=0 -D CMAKE_BUILD_TYPE="Release" -G Ninja ../..
ninja

echo "Done!"
```

It will checkout latest 2.1, build its dependencies and then build Ogre 2.1

If that fails then there could be something missing or broken (likely gcc-related) in your system

**Comment by hcGuyue** [comment]
> Try running this script:
> 
> ```
> #!/bin/bash
> mkdir Test
> cd Test
> mkdir ogredeps
> echo "--- Cloning Ogredeps ---"
> hg clone https://bitbucket.org/cabalistic/ogredeps ogredeps
> cd ogredeps
> mkdir build
> cd build
> cmake -G Ninja ..
> echo "--- Building Ogredeps ---"
> ninja
> ninja install
> cd ../../
> mkdir ogre
> echo "--- Cloning Ogre 2.1 ---"
> hg clone https://bitbucket.org/sinbad/ogre -r v2-1 ogre
> cd ogre
> ln -s ../ogredeps/build/ogredeps Dependencies
> mkdir -p build/Debug
> mkdir -p build/Release
> cd build/Debug
> echo "--- Building Ogre (Debug) ---"
> cmake -D OGRE_USE_BOOST=0 -D OGRE_CONFIG_THREAD_PROVIDER=0 -D OGRE_CONFIG_THREADS=0 -D OGRE_BUILD_COMPONENT_SCENE_FORMAT=1 -D OGRE_BUILD_SAMPLES2=1 -D OGRE_BUILD_TESTS=0 -D CMAKE_BUILD_TYPE="Debug" -G Ninja ../..
> ninja
> cd ../Release
> echo "--- Building Ogre (Release) ---"
> cmake -D OGRE_USE_BOOST=0 -D OGRE_CONFIG_THREAD_PROVIDER=0 -D OGRE_CONFIG_THREADS=0 -D OGRE_BUILD_COMPONENT_SCENE_FORMAT=1 -D OGRE_BUILD_SAMPLES2=1 -D OGRE_BUILD_TESTS=0 -D CMAKE_BUILD_TYPE="Release" -G Ninja ../..
> ninja
> 
> echo "Done!"
> ```
> It will checkout latest 2.1, build its dependencies and then build Ogre 2.1
> 
> If that fails then there could be something missing or broken (likely gcc-related) in your system

I have made it successfully. Thanks very much for your help.
