### ISSUE TITLE
crash when tasking out of fullscreen

### ISSUE THREAD

**Issue by creadmefford** [OGRECave/ogre#1083]
after upgrading from 1.8.1 to 1.11.5, my project now crashes when tasking away and back from fullscreen mode.  

the OgrePanelOverlayElement and OgreTextAreaOverlayElement attempt to unset vertex bindings that in some calls do not exist.  this causes an invalid binding exception to be thrown taking down the process.

see:

https://github.com/creadmefford/ogre/commit/c4ef8048dee6c983d0a4a6f693a50a676ef83802

**Comment by paroj** [comment]
fixed by  #1084
