### ISSUE TITLE
Fails to create a mesh from a manual object due to materials in different groups

### ISSUE THREAD

**Issue by jvanlabeke** [OGRECave/ogre#1099]
System Information
- Ogre Version: 1.11.5
 - Operating System / Platform: : Windows 10 x64
- RenderSystem: DX9 / opengl

We use a manual object to create an mesh. This mesh uses materials in differerent groups.

Basically we configure the manual object with the following pseudo-code:

Begin( materialA, groupA)
..
End()

Begin(materialB, groupB)
...
End()

When we convert the manual object to a mesh by calling convertToMesh(), the code try to setup the mesh material using the group given as a parameter to convertToMesh() ... 
which defeats the purpose of giving groups with the Begin() methods.

Please look up at line 787, in file OgreManualObject.cpp:

            sm->setMaterialName(sec->getMaterialName(), groupName);

The material group name stored in the ManualObjectSection sec is not used.

I think the code should be:

            sm->setMaterialName(sec->getMaterialName(), sec->getMaterialGroup());

Whet do you think?
Regards

**Comment by paroj** [comment]
sounds good. can you provide a pull-request?

**Comment by jvanlabeke** [comment]
I can try to write a pull request (would be my first).

But ... after further investigations, the groupName is not forwarded to the subMesh.
And then later the submesh doesnt forward the groupName to the subEntity when we create the entity in a scene.

cf OgreSubMesh.cpp @ line 54:
```
void SubMesh::setMaterialName( const String& name, const String& groupName /* = ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME */)
    {
        mMaterialName = name;
        // TOFIX? here i think we should add a member mGroupName
        mMatInitialised = true;
    }
```

Then OgreEntity.cpp @ line 1474:
```
    void Entity::buildSubEntityList(MeshPtr& mesh, SubEntityList* sublist)
    {
        // Create SubEntities
        size_t i, numSubMeshes;

        numSubMeshes = mesh->getNumSubMeshes();
        for (i = 0; i < numSubMeshes; ++i)
        {
            SubMesh* subMesh = mesh->getSubMesh(i);
            SubEntity* subEnt = OGRE_NEW SubEntity(this, subMesh);
            if (subMesh->isMatInitialised())
                // TOFIX? here, the group from the material submesh is not used
                subEnt->setMaterialName(subMesh->getMaterialName(), mesh->getGroup()); 
            sublist->push_back(subEnt);
        }
    }
```

So the question is should I try to forward the material group everywhere (as in the code above).
Or shoud I reword my own code to not use groups ? 
Or put meshes materials, entities in the same group ?

Regards
Julien

**Comment by paroj** [comment]
yeah, thats also broken I guess.

Ogre currently assumes that the Mesh and its Material are in the same group. But it already supports different Material groups per SubEntity.

I will take a look at that. However, do create a pull request for ManualObject.

**Comment by paroj** [comment]
the deeper issues should have been taken care of in #1103
