### ISSUE TITLE
Build ogre error on macOS

### ISSUE THREAD

**Issue by zjzcn1** [OGRECave/ogre#1123]
#### System Information
- Ogre Version: : 1.11.5
- Operating System / Platform: : macOS Mojave
- RenderSystem: :  + OpenGL 3.3+ + Metal

#### Detailled description
On build source error.

#### Ogre.log
Scanning dependencies of target OgreMain
[  0%] Building CXX object OgreMain/CMakeFiles/OgreMain.dir/src/OgreASTCCodec.cpp.o
In file included from /Users/xxx/Downloads/ogre/OgreMain/src/OgreASTCCodec.cpp:29:
In file included from /Users/xxx/Downloads/ogre/OgreMain/src/OgreStableHeaders.h:40:
In file included from /Users/xxx/Downloads/ogre/OgreMain/include/OgrePrerequisites.h:30:
/Users/xxx/Downloads/ogre/OgreMain/include/OgrePlatform.h:150:13: fatal error:
      'Availability.h' file not found
#include "Availability.h"
            ^~~~~~~~~~~~~~~~
1 error generated.

**Comment by paroj** [comment]
you must use the xcode cmake generator.
