### ISSUE TITLE
D3D11: Mixed types in getCustomAttribute() method

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/ogre#1191]
#### System Information
- Ogre Version: 1.12
- Operating System / Platform: Windows 10
- RenderSystem: D3D11

#### Detailled description
I recently noticed that some values returned by the getCustomAttribute() method have mixed types or do not exist at all.
- BUFFER
This is mostly of the type `D3D11HardwarePixelBuffer` and is used this way.
But it is only implemented for `D3D11RenderTexture` which can cause crashes at [this position](https://github.com/OGRECave/ogre/blob/d4b31c0586dd23e2fc4d48b087e8303205caa45c/RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp#L1203) with `D3D11MultiRenderTarget` for example.
- DDBACKBUFFER
This is treated like 2 different types: [ID3D11Texture2D**](https://github.com/OGRECave/ogre/blob/d4b31c0586dd23e2fc4d48b087e8303205caa45c/RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp#L115) and [HardwarePixelBuffer**](https://github.com/OGRECave/ogre/blob/d4b31c0586dd23e2fc4d48b087e8303205caa45c/RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp#L604) but is only used as [ID3D11Texture2D**](https://github.com/OGRECave/ogre/blob/d4b31c0586dd23e2fc4d48b087e8303205caa45c/RenderSystems/Direct3D11/src/OgreD3D11DepthBuffer.cpp#L75).

I can't figure out why this was done by the `getCustomAttribute()` method at all because it returns render system specific values (ID3D11Texture2D for example).

**Comment by paroj** [comment]
the lack of proper internal interfaces basically. getCustomAttribute serves two purposes:
1. it checks if the given pointer is of type `D3D11RenderTexture` (other classes return NULL)
2. it allows exposing arbitrary data over an [any-like](https://en.cppreference.com/w/cpp/utility/any) interface

Nr 2 was the original use-case and is still valid  & [document here](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_render_target.html#a6c32524efacf6da599d5daccf3d9e166).
Nr. 1 requires some refactoring to be properly fixed, which I have done for GL here https://github.com/OGRECave/ogre/commit/a57e7fc443afbc0d217f6e2bde67cb1804458738

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
So it would be a possible solution to introduce a class like `D3D11RenderTarget` or am I wrong?

**Comment by paroj** [comment]
yes, that would be the correct solution
