### ISSUE TITLE
Overlay: Manual font textures are unsupported

### ISSUE THREAD

**Issue by EmilyMansfield** [OGRECave/ogre#1195]
#### System Information
- Ogre Version: 1.12.0

#### Detailed Description
`ManualResourceLoader`s can be used to load a `Font` by setting the glyph positions, but it would be useful if they could also be used to load the `Texture` backing the `Font`. The full description for `Font` in the documentation suggests that this is possible:

> You can either create the texture manually in code, or you can use a .fontdef script to define it

but `Font::loadImpl()` creates the `Texture` for you so there is no opportunity to load one with a `ManualResourceLoader` as far as I can tell, and no way to set the texture other than `Font::loadImpl()`. So this is maybe a bug but also kind of a feature request.

#### Proposed Fix
My workaround has been to avoid calling `Font::loadImpl()` in the `ManualResourceLoader` for the `Font` and instead allow the user to create the material and texture manually by adding a public `void Font::_setMaterial(const MaterialPtr &)` member.

I'm happy to provide a pull request for that change if it is wanted.

**Comment by paroj** [comment]
> Proposed Fix

yes, please go ahead. This is obviously and API limitation as the loadImpl should not be called when a manual loader is used:
https://github.com/OGRECave/ogre/blob/master/OgreMain/include/OgreResource.h#L203-L204
