### ISSUE TITLE
Macos no OpenGL render on Mojave / Mac Mini

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#1198]
#### System Information
- Ogre Version: 1.12.1 (Master)
- Operating System / Platform: MacOS
- RenderSystem: OpenGL

#### Detailed description
My apps with Ogre are working well on OSX High sierra  (IMac mid-2010 with ATI card)
But I only have a black window on a Mac with Mojave (Mac mini end-2014 with Intel Iris)
There is no exception, nothing in logs...
I don't have another Mac computer to test.

**Comment by paroj** [comment]
can you try the SampleBrowser with SDL2 as in #913?

**Comment by arkeon7** [comment]
Sorry I don't build the sample browser. Also I don't use SDL2, I use QT on OSX for windows.
I'll try the check the OSX code when I'll have time.

**Comment by arkeon7** [comment]
Also calling windowMovedOrResized() do not change anything for me, I can see the buffer with the correct size but it still empty

**Comment by paroj** [comment]
apple introduced an breaking change with Mojave. SDL2 added a workaround for that and consequently OGRE works if SDL2 is used for windowing. However I never came to figure out what exactly is broken to fix OGRE native windowing that is used when SDL2 is not available.

**Comment by arkeon7** [comment]
https://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/
I'll  update QT and rebuild it. But it seems that the best trick is to downgrade xcode....

**Comment by arkeon7** [comment]
Still no luck even with QT 5.12.3.
I think I will abandon Apple things soon...

**Comment by arkeon7** [comment]
It seems that mojave require Opengl context and calls in the main thread...
Just modifying my program to run all in main thread make the 3D buffer appear correctly
