### ISSUE TITLE
Terrain: _renderCompositeMap does not use the material's group

### ISSUE THREAD

**Issue by EmilyMansfield** [OGRECave/ogre#1209]
#### System Information
- Ogre Version: 1.12.1

#### Detailed description
`TerrainMaterialGenerator::_renderCompositeMap` takes a `MaterialPtr` but only passes its name to the composite map plane, not its group, so unless the material is in the default group the material won't be found when the composite map is baked.

This can happen if the user has subclassed `TerrainMaterialGenerator` and is generating textures in their own resource group, or even if they're using the provided `TerrainMaterialGeneratorA` but the `Terrain` itself isn't in the default group.

#### Proposed Fix(es)
This is easy to fix by just passing the material group in the appropriate places in `_renderCompositeMap`, but since the composite map plane is a `ManualObject` there's an opportunity here to make some changes to that. In particular, `ManualObject` and `ManualObjectSection` work with material name and group pairs, but could have overloads added that take `MaterialPtr` instead, like `SubMesh` now has after #1103. This would save some material lookups and make it harder to introduce bugs like the above in the future. #1099 could also be closed simultaneously.

Is there a preference for either of these fixes? I'm happy to submit a pull request for either.

**Comment by paroj** [comment]
I would prefer the `MaterialPtr` overloads

**Comment by EmilyMansfield** [comment]
Awesome, I'll start working on that :smile:
