### ISSUE TITLE
Android build OGRE_CONFIG_DOUBLE=TRUE fails

### ISSUE THREAD

**Issue by djreep81** [OGRECave/ogre#1246]
#### System Information
- Ogre Version: :1.12.1: 
- Operating System / Platform: :Android build ndk r20: 
- RenderSystem: :gles2:

#### Detailled description

I can build both arm v7a and arm64 v8a for android, however I would like to get NEON working.  So for the arm64 v8a builds I add the option OGRE_CONFIG_DOUBLE:BOOL=TRUE

This causes build errors since in some places a float is expected

#### Ogre.log

```
ogre-1.12.1/OgreMain/src/OgreAutoParamDataSource.cpp:641:16: error: no viable conversion from returned value of type 'const Vector<[...], float>' to function return type 'const Vector<[...], Ogre::Real>'
        return mPointParams;
               ^~~~~~~~~~~~
/Users/dave/Projects/dependencies/ogre-1.12.1/OgreMain/include/OgreVector.h:304:23: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const Ogre::Vector4f' (aka 'const Vector<4, float>') to 'const Ogre::Vector<4, double> &' for 1st argument
    class _OgreExport Vector : public VectorBase<dims, T>
                      ^
/Users/dave/Projects/dependencies/ogre-1.12.1/OgreMain/include/OgreVector.h:304:23: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const Ogre::Vector4f' (aka 'const Vector<4, float>') to 'Ogre::Vector<4, double> &&' for 1st argument
```
-->

**Comment by paroj** [comment]
> however I would like to get NEON working

the cmake switch for that is `-DANDROID_ARM_NEON=TRUE`

while `OGRE_CONFIG_DOUBLE` is indeed broken, it is unrelated

**Comment by djreep81** [comment]
Thanks, you are correct @paroj 

I will go ahead and close this one out.  

I was surprised that ANDROID_ARM_NEON was not set by android toolchain when building for arm64-v8a since all devices for that architecture support neon according to the documentation here [android neon](https://developer.android.com/ndk/guides/cpu-arm-neon).

It appears to set that variable in the toolchain when building for 'armeabi v7a with neon'

I'll just manually set it for all arm64-v8a builds.  Thanks!
