### ISSUE TITLE
Make Various language port into Ogre SDK

### ISSUE THREAD

**Issue by cookgreen** [OGRECave/ogre#1251]
Hi, since there is no .net binding in the ogre sdk, so I am thinking whether you guys can make various language port into ogre SDK including CSharp?

**Comment by paroj** [comment]
the latest master snapshot SDK should include everything to use Ogre with .NET:
https://bintray.com/ogrecave/ogre/download_file?file_path=ogre-sdk-master1-vc15-x64.zip

see the lib/cli/ subdirectory
