### ISSUE TITLE
Simple 2D Map-Texture with custom shaders stopped working with Ogre 1.11

### ISSUE THREAD

**Issue by Martin-Idel** [OGRECave/ogre#1252]
#### System Information
- Ogre Version: 1.10.12 vs 1.12.1 (commit https://github.com/OGRECave/ogre/commit/17800a4d1887d3498e7862328d2d731d44262a78)
- Operating System / Platform: all major platforms (Windows, Linux, Mac) 
- RenderSystem: OpenGL

#### Detailled description
When upgrading RViz to Ogre 1.12.1 to pull in all the new changes (this fixes a few long standing intermittent test failures on aarch and also helps with MacOS issues, so thank you for your hard work), there is a problem regarding the map display (downstream issue: https://github.com/ros2/rviz/issues/453)

In short, the display takes a 2d texture and colors it acting as a map in the 3d scene. Without any changes to shaders or the code in question, we now get a blank 2D "object" with errors
```
Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-1] active samplers with a different type refer to the same texture image unit
```
and after the first error recurring 
```
[rviz2-1] [ERROR] [rviz2]: Error prior to using GLSL Program Object : GL_INVALID_OPERATION
```
I did a bisect and got lucky: Without any code changes in the RViz code-base and just switching the Ogre checkout, the breaking change occurs in https://github.com/OGRECave/ogre/commit/17800a4d1887d3498e7862328d2d731d44262a78 - if I switch to the commit before that one, the problem disappears and it occurs with this commit. 

It might be that the shader is somehow wrong - but since it worked perfectly before on many platforms, this would be odd (nevertheless, please see the shaders here: https://github.com/ros2/rviz/blob/ros2/rviz_rendering/ogre_media/materials/glsl120/indexed_8bit_image.vert and https://github.com/ros2/rviz/blob/ros2/rviz_rendering/ogre_media/materials/glsl120/indexed_8bit_image.vert)

**Comment by paroj** [comment]
the change by that commit is described in the changelog here (second bullet point):
https://github.com/OGRECave/ogre/blob/master/Docs/1.11-Notes.md#breaking-non-api-changes

my guess would be that you declare the "palette" texture in some material script (which defaults to a 2D texture) which then gets sampled with sampler1D.

**Comment by Martin-Idel** [comment]
I saw the description, but I thought that didn't apply here, because it seemed to me that we didn't really define the texture in a script. So it seems to be a usage error after all. If you want, I can close this issue then and reopen in the forum as I still don't fully understand the problem.

---

Otherwise, here is my summary: I found the material script and it's very simple:
```
material rviz/Indexed8BitImage
{
  technique
  {
    pass
    {
      vertex_program_ref rviz/glsl120/indexed_8bit_image.vert {}

      fragment_program_ref rviz/glsl120/indexed_8bit_image.frag
      {
        param_named eight_bit_image int 0
        param_named palette int 1
      }
    }
  }
}
```
To me, that just reads as it declares that the two parameters `eight_bit_image` and `palette` used in the fragment shader can be accessed by 0 and 1 from outside the script. There is no visible declaration of any texture (maybe that is the problem?).

The fragment shader then knows that `palette` is a sampler uniform:
```

#version 120

// Draws an 8-bit image using RGB values from a 256x1 palette texture.

varying vec2 UV;
uniform sampler2D eight_bit_image;
uniform sampler1D palette;
uniform float alpha;

void main()
{
  // The 0.999 multiply is needed because brightness value 255 comes
  // out of texture2D() as 1.0, which wraps around to 0.0 in the
  // palette texture.
  vec4 color = texture1D( palette, 0.999 * texture2D( eight_bit_image, UV ).x );
  gl_FragColor = vec4( color.rgb, color.a * alpha );
}
```
And the shaders are bound together into a program via
```
fragment_program rviz/glsl120/indexed_8bit_image.frag glsl
{
  source indexed_8bit_image.frag
  default_params
  {
    param_named_auto alpha custom 1
  }
}

vertex_program rviz/glsl120/indexed_8bit_image.vert glsl
{
  source indexed_8bit_image.vert
}
```

Now inside the program, we create the texture:
```
texture_ = Ogre::TextureManager::getSingleton().loadRawData(
    "MapTexture" + std::to_string(texture_count_++),
    "rviz_rendering",
    pixel_stream,
    static_cast<uint16_t>(width_), static_cast<uint16_t>(height_),
    Ogre::PF_L8, Ogre::TEX_TYPE_2D, 0);
```
and set it using:
```
Ogre::Pass * pass = material_->getTechnique(0)->getPass(0);
    Ogre::TextureUnitState * tex_unit = nullptr;
    if (pass->getNumTextureUnitStates() > 0) {
      tex_unit = pass->getTextureUnitState(0);
    } else {
      tex_unit = pass->createTextureUnitState();
    }

    tex_unit->setTextureName(texture_);
```
which I would read as corresponding to the `eight_bit_image` sampler because of the `getTextureUnitState(0)` and then the palette texture will be created via a call to
```
palette_texture_ = Ogre::TextureManager::getSingleton().loadRawData(
    tex_name, "rviz_rendering", palette_stream, 256, 1, Ogre::PF_BYTE_RGBA, Ogre::TEX_TYPE_1D, 0)
```
and set similarly via:
```
    Ogre::Pass * pass = material_->getTechnique(0)->getPass(0);
    Ogre::TextureUnitState * palette_tex_unit = nullptr;
    if (pass->getNumTextureUnitStates() > 1) {
      palette_tex_unit = pass->getTextureUnitState(1);
    } else {
      palette_tex_unit = pass->createTextureUnitState();
    }
    palette_tex_unit->setTexture(palette_texture_);
    palette_tex_unit->setTextureFiltering(Ogre::TFO_NONE);
```

**Comment by paroj** [comment]
your code looks good, so the issue must be more complicated. The only hint we have is:
ˋˋˋ
active samplers with a different type refer to the same texture image unit
ˋˋˋ
this means that both eight_bit_image and palette refer to the same texture. I remember hitting this somewhere when porting code after the commit you identified. However I forgot what the fix was...

Maybe this is caused by the material being fully loaded (and hence the shader being compiled) before the textures are created. (On the other hand having the textures hardcoded in the material script should have fixed that) Try inspecting the material whether it has the right amount of texture units/ techniques/ passes before when the error is happening.

**Comment by Martin-Idel** [comment]
Okay, further investigation revealed that at some point we are removing and destroying the texture and (before the next render step) set a new one. However, this seemed to have messed something up - if I only remove and destroy the texture after exchanging it in the texture via `setTexture(...)`, everything seems to work as intended.

I still get an error `Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : active samplers with a different type refer to the same texture image unit` once, but it doesn't have any visible effect, I can't pin down when it actually happens and it was already present before the upgrade, so it's definitely not a bug on Ogre's side. Therefore, I'll close this.

Thanks for your help!
