### ISSUE TITLE
X11EGLWindow::resize problem

### ISSUE THREAD

**Issue by xuzhongxing** [OGRECave/ogre#1253]
#### System Information
- Ogre Version: 1.11.3
- Operating System / Platform: Ubuntu 19.04
- RenderSystem: GL3+

#### Detailled description
I use OGRE in a QT Widget. I use EGL. And X11EGLWindow::resize() cannot resize my GL window. 

If I modify the code like this:
```
if (!mIsExternal) {
    XResizeWindow((Display*)mGLSupport->getNativeDisplay(), (Window)mWindow, width, height);
}
```
It will resize window correctly.

**Comment by paroj** [comment]
you should be calling windowMovedOrResized after resizing your Qt widget.

**Comment by xuzhongxing** [comment]
I called. It does not help.
X11EGLWindow::windowMovedOrResized() does not do window resizing.

**Comment by xuzhongxing** [comment]
Thanks for the fixing.
