### ISSUE TITLE
GL3+ Texture upload is on slow path

### ISSUE THREAD

**Issue by 1k0** [OGRECave/ogre#1267]
#### System Information
- Ogre Version: Ogre 1 master (Tested on 1.12.1)
- Operating System / Platform: Windows 10, NVidia
- RenderSystem: GL3Plus

#### Detailled description
GL3PlusRS glTexStorage texture upload codepath is in "driver slow path" at the moment. This could be a possible NVidia driver bug, since I found no limitation in GL spec which would explain this behaviour. Please note, that I only tested this on Nvidia HW since I dont own any AMD, or Intel GPU-s, on those this codepath could be fine.

I made a simple test case, upload a 4k*4k texture and measure the upload time. With pure GL it took 17ms, with OGRE it took 54ms. (The OGRE Texture upload stack was on fast path, so no resizes npot or anything like that) 
So I investigated, VS Profiler said most of the work was done inside glTexSubImage2D(), but glTexSubImage2D() had the correct fast path GL parameters, which I also used in my test code. This proved that some texture creation parameters might cause slowdowns (driver slow path), since the texture upload in my code was fine with default texParams.

It turned out that specifying glTexParameteri -s before creating the backing GPU pixel buffer can be problematic in some limited cases. So commenting out them one by one, I found out that GL_TEXTURE_WRAP_* parameters will cause driver slow path IF not on GL default vaule. But this happens only if you specify the parameters first and then create the texture storage.

So this is fast :
        GlTexStorage2D(GL_TEXTURE_2D, 1, GL_RGBA8, image.getWidth(), image.getHeight());
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);

This is not : 
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
        gl->setTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
        GlTexStorage2D(GL_TEXTURE_2D, 1, GL_RGBA8, image.getWidth(), image.getHeight());

Possible solutions : 
-----------------------------------------------------
- In OgreGL3PlusTexture.cpp around line 130 set the texture parameter to the correct default one GL_REPEAT.

mRenderSystem->_getStateCacheManager()->setTexParameteri(texTarget,
GL_TEXTURE_WRAP_S, **GL_REPEAT**);
mRenderSystem->_getStateCacheManager()->setTexParameteri(texTarget,
GL_TEXTURE_WRAP_T, **GL_REPEAT**);
mRenderSystem->_getStateCacheManager()->setTexParameteri(texTarget,
GL_TEXTURE_WRAP_R, **GL_REPEAT**);

I used this as a quick fix, this will set us on driver fast path.

- A slightly bigger but maybe better fix would be to set the texture params after creating the texture store. Not sure if it is 100% correct by spec, but this would avoid driver bugs like this in the future. So : 

GlHandle texture;
GlGenTextures(1, &texture);
gl->bindGLTexture(GL_TEXTURE_2D, texture);
GlTexStorage2D(GL_TEXTURE_2D, 1, GL_RGBA8, image.getWidth(), image.getHeight());

//Specify TexParami-s here

//Upload texture later

**Comment by paroj** [comment]
it should be safe to delete those texture filter/ wrap settings altogether as they are managed through sampler objects nowadays. Can you provide an according pull request if that works for you?

**Comment by paroj** [comment]
fun fact https://github.com/OGRECave/ogre-attic/commit/3c0ee0cb996a2b97a06acea49720f666e0f2d616

**Comment by 1k0** [comment]
Nice, but cant really blame them. OpenGL spec is pretty spotty in places. There are a lot of "grey areas". 
I can create a pull request, but which fix should I implement? I would go for Option 2 just to be a litte more future proof. Basically : 
-Create texture handle
-Bind texture
-Setup pixel storage
-Setup tex params

I can check the spec is this is valid, not sure if specing storage before params is OK.

**Comment by 1k0** [comment]
So gl spec 4.2 wont disallow the oreder specified above. Also found a khronos snippet which uses this kind of ordering. https://www.khronos.org/opengl/wiki/Common_Mistakes#Automatic_mipmap_generation

Also found some intereting things in gl 4.2 spec under "Effects of Sampler Objects on Texture Completeness"
"If a sampler object and a texture object are simultaneously bound to the same texture unit, then the sampling state for that unit is taken from the sampler object"

I tested the slowdown bug with sampler objects, but they will not trigger it. We could also bind 0 sampler object while creating texture/texture storage to avoid possible future bugs.

**Comment by 1k0** [comment]
Found a second problem. If texture pixes storage is created with old API glTexImage*D, then upload with glTexSubImage*D will be slow even if the whole image is rewritten. Slow = 16ms vs. 30 ms in case of a 4k*4k texture.

This might be caused by driver internal synchronization. Not using glTexSubImage*D and always respecifying texture with glTexImage*D is faster. Note that this problem is not present with glTexStorage*D textures, probably because their immutable internal texture format.

We could track if the OgreGL3PlusTexture is immutable with an extra private boolean mIsImmutable. And use different code path accordingly in the GL3PlusTextureBuffer upload() routine.

**Comment by paroj** [comment]
> We could also bind 0 sampler object while creating texture/texture storage to avoid possible future bugs.

yes, this option please. You can then revert the changes from this commit: https://github.com/OGRECave/ogre-attic/commit/3c0ee0cb996a2b97a06acea49720f666e0f2d616

**Comment by paroj** [comment]
> And use different code path accordingly in the GL3PlusTextureBuffer upload() routine.

that would require duplicating most of the ::upoad code, which I think is not worth the trouble given that most users will hit the glTexStorage path over time.

**Comment by 1k0** [comment]
I dont see how a PBO would help in this case, but I can try it tomorrow. 
I would gladly write that upload code too, this rendersystem is called GL3Plus for a reason. IMO we should not expect GL4 features, only use the if they are present. 
The bigger question is if glTexSubImage "slowness" is present on other GL implementations. (AMD Intel)

**Comment by 1k0** [comment]
Soo we cant really revert the offending commit. Found it why it was "broken" in the first place before that commit. (Probably) The following GL_TEXTURE_RECTANGLE limitations were offended : 
-tex wrap cannot be repeat
-min filter cannot be mipmapped, only linear/nearest

GL_TEXTURE_RECTANGLE is extremely picky, I am not sure what should we do if GL_TEXTURE_RECTANGLE was requested with mipmaps. Set Ogre::Textures         
uint32 mNumRequestedMipmaps;
uint32 mNumMipmaps;
too, and be robust or just cheeze it with an exception.

**Comment by paroj** [comment]
Do the Parameters have to be Set at creation time? Rectangle Texture Handling ist currently done Here https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreTextureUnitState.cpp#L277

**Comment by 1k0** [comment]
Params set at creation time will be the textures default param set, which will be overridden if a sampler is attached to the same texture unit. This affects "texture completeness" too according to spec. So in theory it should be fine. 
I would still set a valid texture sampling state at creation time, its OpenGL after all.

**Comment by 1k0** [comment]
BTW the default parameters are not a problem here, it can be solved easily with a few ifs. My problem is the mipmap generation. In glTexImage2D if target is GL_TEXTURE_RECTANGLE level must be 0. The current code does not care about this AFAIK. 

My guess would be to handle this case like the compressed texture case and set both mNumMipmaps and mNumRequestedMipmaps to 0.

**Comment by 1k0** [comment]
This is also present at thexure upload, though it will be fixed by using only 1 mip level. For GL_TEXTURE_RECTANGLE glGenerateMipmap should be disabled though so have to fix that too.

**Comment by paroj** [comment]
so, I have investigated the GL_TEXTURE_RECTANGLE case. Actually it is not very useful nowadays:
https://www.khronos.org/opengl/wiki/Rectangle_Texture

the main purpose why it exists in Ogre is probably this:
https://forums.ogre3d.org/viewtopic.php?t=65518

however the API in question is obsoleted by AVFoundation.

Further looking at the OGRE implementation, revealed that it probably never really worked:
https://github.com/paroj/ogre/commit/325a926e49530e925f1b173a370a7fb178730b94

Therefore I rather decided to deprecate TEX_TYPE_2D_RECT.

#1271 will fix this issue. Please open a new one for the `glTexSubImage` slowness.

**Comment by paroj** [comment]
btw PBOs seem to help: https://gist.github.com/roxlu/4663550

feel free to object if you can measure considerable performance improvements by using GL_TEXTURE_RECTANGLE

**Comment by fbridault** [comment]
@gKevin this thread looks interesting considering our concerns with texture upload performances.
