### ISSUE TITLE
I  Found PixFormat Error In  GL3Plus

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#1278]
#### System Information
- Ogre Version: :grey_question: 1.12.3
- Operating System / Platform: :grey_question: win7 and win10
- RenderSystem: :grey_question: GL3Plus

#### Detailled description

I Found the  Pix Format Ogre::PF_BYTE_A Has behave  differently in Gl3Plus Render System compare with GL Render System and DX9 Render System.  the  Pix Channel Can't set to black
Use GLPlus. But the Others RenderSystem can do it.

#### Ogre.log

```
 Ogre::TexturePtr m_Texture = Ogre::TextureManager::getSingletonPtr()->createManual("name2", "General", Ogre::TEX_TYPE_2D,
		 512, 512, 1, 0, Ogre::PF_BYTE_A, Ogre::TU_DEFAULT);
	 UINT nSize = 512 * 512 * 1;
	 unsigned char* m_pData = new unsigned char[nSize];
	 memset(m_pData, 0, nSize);  //Can't Make sense In GL3Plus

	 Ogre::HardwarePixelBufferSharedPtr buffer = m_Texture->getBuffer();
	 Ogre::PixelBox pixelBox(512, 512, 1, Ogre::PF_BYTE_A, m_pData);
	 Ogre::Box imageBox(0, 0, 512, 512);
	 buffer->blitFromMemory(pixelBox, imageBox);



	 MeshManager::getSingleton().createPlane("floor", ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME,
		 Ogre::Plane(Vector3::UNIT_Y, 0), 10, 10, 1, 1, true, 1, 1, 1, Vector3::UNIT_Z);
	 Ogre::Entity* floor = appMgr->mSceneMgr->createEntity("floor");
	 SceneNode *nfloor = appMgr->mSceneMgr->createSceneNode();
	 nfloor->attachObject(floor);
	 Ogre::MaterialPtr floorMat = Ogre::MaterialManager::getSingletonPtr()->getByName("Examples/Rockwall");
	 if (!floorMat->isLoaded())
	 {
		 floorMat->load();
	 }
	 floorMat->getBestTechnique()->getPass(0)->getTextureUnitState(0)->setTexture(m_Texture);


/*////////////////////////////////////////////////////////////
I Use The Below Shader To see the Alpha Channel Color
The Problem is  It  Show Different  bewteen RenderSystems
*/


/* File: ulit_vfs_150.glsl */

#version 150
#ifdef VS_PROGRAM
in vec4 position;
in vec4 uv0;

out vec2 oUv0;
uniform mat4 wvpMat;
void main()
{
    gl_Position = wvpMat * position;
    oUv0 = uv0.xy;

}
#else

in vec2 oUv0;
uniform sampler2D diffuseMap;
out vec4 color;
void main ()              
{
	vec4 texColor =  texture(diffuseMap, oUv0);
	float c = texColor.a;
	color = vec4(0, c, 0, 1);
}

#endif

/* File: ulit_vfs_150.material */

vertex_program ulit_VS glsl
{ 
    source ulit_vfs_150.glsl
	preprocessor_defines VS_PROGRAM
	default_params
	{
		param_named_auto wvpMat worldviewproj_matrix	
	}
} 

fragment_program ulit_FS glsl
{
  source ulit_vfs_150.glsl
  default_params
  {
  		param_named diffuseMap int 0
  }
}


material Examples/Rockwall
{
	technique
	{
		pass
		{
			vertex_program_ref ulit_VS{}
                         fragment_program_ref ulit_FS{}
			texture_unit
			{
				
			}
		}
	}
}
```

**Comment by 36yang** [comment]
Choose different RenderSystem form  GL3Plus,  the result is  different。

**Comment by paroj** [comment]
alpha textures are not supported by GL3 any more:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml

try using GL_RED instead of GL_ALPHA here:
https://github.com/OGRECave/ogre/blob/master/RenderSystems/GL3Plus/src/OgreGL3PlusPixelFormat.cpp#L72

and set up swizzling accordingly here:
https://github.com/OGRECave/ogre/blob/master/RenderSystems/GL3Plus/src/OgreGL3PlusTexture.cpp#L125

**Comment by 36yang** [comment]
Thank you for your, I will have a try




------------------ 原始邮件 ------------------
发件人: "Pavel Rojtberg"<notifications@github.com>; 
发送时间: 2019年9月23日(星期一) 晚上6:13
收件人: "OGRECave/ogre"<ogre@noreply.github.com>; 
抄送: "闯"<948082928@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [OGRECave/ogre] I  Found PixFormat Error In  GL3Plus (#1278)




alpha textures are not supported by GL3 any more:
 https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml
 
try using GL_RED instead of GL_ALPHA here:
 https://github.com/OGRECave/ogre/blob/master/RenderSystems/GL3Plus/src/OgreGL3PlusPixelFormat.cpp#L72
 
and set up swizzling accordingly here:
 https://github.com/OGRECave/ogre/blob/master/RenderSystems/GL3Plus/src/OgreGL3PlusTexture.cpp#L125

**Comment by 36yang** [comment]
I   now  use  Ogre::PF_R8  instead, It work the same in diffent render system

**Comment by 36yang** [comment]
I   now  use  Ogre::PF_R8  instead, It work the same in diffent render system
