### ISSUE TITLE
Skybox orientation bug

### ISSUE THREAD

**Issue by jhwangbo** [OGRECave/ogre#1302]
- Ogre Version: :1.12.2

SceneManager::SkyRenderer::setSkyBox() does not work properly when orientation is specified because it rotates the texture coordinates as well. If both texture coordinate and the position are rotated, nothing changes. Here is my quick fix

            // These orientations don't have to be rotated
            // middle = orientation * middle;
            // up = orientation * up;
            // right = orientation * right;

            Vector3 pos, pos2;
            pos = middle + up - right;
            pos2 = orientation * pos;
            mSkyBoxObj->position(pos2);
            mSkyBoxObj->textureCoord(pos.normalisedCopy() * Vector3(1,1,-1));

            // bottom left
            pos = middle - up - right;
            pos2 = orientation * pos;
            mSkyBoxObj->position(pos2);
            mSkyBoxObj->textureCoord(pos.normalisedCopy() * Vector3(1,1,-1));

            // bottom right
            pos = middle - up + right;
            pos2 = orientation * pos;
            mSkyBoxObj->position(pos2);
            mSkyBoxObj->textureCoord(pos.normalisedCopy() * Vector3(1,1,-1));

            // top right
            pos = middle + up + right;
            pos2 = orientation * pos;
            mSkyBoxObj->position(pos2);
            mSkyBoxObj->textureCoord(pos.normalisedCopy() * Vector3(1,1,-1));

**Comment by paroj** [comment]
can you provide a pull-request?
