### ISSUE TITLE
GLSL preprocessor does not handle multiple #elif

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/ogre#1307]
#### System Information
- Ogre Version: 1.12 (master)
- Operating System / Platform: Windows
- RenderSystem: OpenGL3+

#### Detailled description
The GLSL preprocessor does not handle `#elif` directive. This can be tested with modifying the PBR fragment shader that comes with Ogre by changing the result `gl_FragColor`:

```
#if defined(HAS_OCCLUSIONMAP) && defined(DEBUG_OCCLUSION)
    gl_FragColor = vec4(ao, ao, ao, 1.0);
#elif defined(DEBUG_NORMAL)
    gl_FragColor = vec4(n.x, n.y, n.z, 1.0);
#elif defined(HAS_EMISSIVEMAP) && defined(DEBUG_EMISSIVE)
    gl_FragColor = vec4(emissive.r, emissive.g, emissive.b, 1.0);
#elif defined(DEBUG_METAL)
    gl_FragColor = vec4(metallic, metallic, metallic, 1.0);
#elif defined(DEBUG_ROUGHNESS)
    gl_FragColor = vec4(perceptualRoughness, perceptualRoughness, perceptualRoughness, 1.0);
#else
    gl_FragColor = vec4(1.0, 0.0, 0.0, baseColor.a);
#endif
```

This will always execute the last line regardless of `DEBUG_OCCLUSION`, `DEBUG_NORMAL`, `DEBUG_EMISSIVE`, `DEBUG_METAL` or `DEBUG_ROUGHNESS` definitions. How ever if the code is changed to:

```
#if defined(HAS_OCCLUSIONMAP) && defined(DEBUG_OCCLUSION)
    gl_FragColor = vec4(ao, ao, ao, 1.0);
#else
    gl_FragColor = vec4(1.0, 0.0, 0.0, baseColor.a);
#endif
```

It will correctly handle the first line if `DEBUG_OCCLUSION` is defined.

**Comment by paroj** [comment]
maybe `defined()` is broken. See this test:
https://github.com/OGRECave/ogre/blob/master/Tests/RenderSystems/GLSupport/GLSLTests.cpp#L64

**Comment by SNiLD** [comment]
`defined()` alone can't be broken as following code does work:

```
#if defined(HAS_OCCLUSIONMAP) && defined(DEBUG_OCCLUSION)
    gl_FragColor = vec4(ao, ao, ao, 1.0);
#else
#if defined(DEBUG_NORMAL)
    gl_FragColor = vec4(n.x, n.y, n.z, 1.0);
#else
#if defined(HAS_EMISSIVEMAP) && defined(DEBUG_EMISSIVE)
    gl_FragColor = vec4(emissive.r, emissive.g, emissive.b, 1.0);
#else
#if defined(DEBUG_METAL)
    gl_FragColor = vec4(metallic, metallic, metallic, 1.0);
#else
#if defined(DEBUG_ROUGHNESS)
    gl_FragColor = vec4(perceptualRoughness, perceptualRoughness, perceptualRoughness, 1.0);
#else
    gl_FragColor = vec4(1.0, 0.0, 0.0, baseColor.a);
#endif
#endif
#endif
#endif
#endif
```

So then it must be combination of `#elif` and `defined()`.

**Comment by paroj** [comment]
so the error is that the `#else` block only considers the preceding `#elif`
