### ISSUE TITLE
imgui not included in github release tarball

### ISSUE THREAD

**Issue by Yamakuzure** [OGRECave/ogre#1332]
#### System Information
- Ogre Version: 1.12.3
- Operating System / Platform: Gentoo Linux / x86_64
- RenderSystem: none, yet, but planning with OpenGL3+

#### Detailled description
I am working on an ebuild for the latest ogre-1.12.3 release. When the configuration starts, it results in an error, that imgui.cpp can not be found.

**_Note_**: With 1.12.2 the ebuild worked perfectly fine, and all demos from the SampleBrowser worked well.

Configuration:
````
cmake \
    -C \
    /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3_build/gentoo_common_config.cmake \
    -G \
    Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_SKIP_INSTALL_RPATH=yes \
    -DOGRE_BUILD_COMPONENT_BITES=yes \
    -DOGRE_BUILD_COMPONENT_CSHARP=no \
    -DOGRE_BUILD_COMPONENT_HLMS=yes \
    -DOGRE_BUILD_COMPONENT_JAVA=no \
    -DOGRE_BUILD_COMPONENT_PAGING=yes \
    -DOGRE_BUILD_COMPONENT_PROPERTY=yes \
    -DOGRE_BUILD_COMPONENT_PYTHON=no \
    -DOGRE_BUILD_COMPONENT_RTSHADERSYSTEM=yes \
    -DOGRE_BUILD_COMPONENT_TERRAIN=yes \
    -DOGRE_BUILD_COMPONENT_VOLUME=yes \
    -DOGRE_BUILD_DEPENDENCIES=no \
    -DOGRE_BUILD_PLUGIN_CG=yes \
    -DOGRE_BUILD_PLUGIN_FREEIMAGE=yes \
    -DOGRE_BUILD_PLUGIN_EXRCODEC=no \
    -DOGRE_BUILD_RENDERSYSTEM_GL=yes \
    -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=yes \
    -DOGRE_BUILD_RENDERSYSTEM_GLES2=no \
    -DOGRE_BUILD_SAMPLES=yes \
    -DOGRE_BUILD_TESTS=no \
    -DOGRE_BUILD_TOOLS=yes \
    -DOGRE_CONFIG_DOUBLE=yes \
    -DOGRE_CONFIG_ENABLE_GL_STATE_CACHE_SUPPORT=yes \
    -DOGRE_CONFIG_ENABLE_GLES2_CG_SUPPORT=no \
    -DOGRE_CONFIG_ENABLE_GLES3_SUPPORT=no \
    -DOGRE_CONFIG_THREADS=3 \
    -DOGRE_CONFIG_THREAD_PROVIDER=std \
    -DOGRE_ENABLE_PRECOMPILED_HEADERS=no \
    -DOGRE_GLSUPPORT_USE_EGL=no \
    -DOGRE_INSTALL_DOCS=yes \
    -DOGRE_INSTALL_SAMPLES=yes \
    -DOGRE_INSTALL_SAMPLES_SOURCE=yes \
    -DOGRE_PROFILING=no \
    -DOGRE_RESOURCEMANAGER_STRICT=2 \
    -DCMAKE_BUILD_TYPE=Gentoo \
    -DCMAKE_TOOLCHAIN_FILE=/home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3_build/gentoo_toolchain.cmake \
    /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3
````
Relevant Output:
````
-- Configuring done
CMake Error at Components/Overlay/CMakeLists.txt:33 (add_library):
  Cannot find source file:

    /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Components/Overlay/src/imgui/imgui.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at Components/Overlay/CMakeLists.txt:33 (add_library):
  No SOURCES given to target: OgreOverlay


CMake Generate step failed.  Build files cannot be regenerated correctly.
````
A look into the corresponding directory:
````
 $ l /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Components/Overlay/src/imgui/
insgesamt 4,0K
-rw-r--r-- 1 sed sed 140 14. Nov 19:34 imconfig.h
````

#### Ogre.log
None, yet.

#### Hotfix
Currently I build with adding `-DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI=no`, and that works as always, but I thought you's wish to know that the imgui inclusion is incomplete.

**Comment by Yamakuzure** [comment]
Damn... I was a bit quick...

Compilation does not work this way out of the box. It fails at:
````
[520/575] ...
In file included from Samples/include/ImGuiDemo.h:4,
                 from /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Samples/Common/src/DefaultSamplesPlugin.cpp:53:
/home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Components/Overlay/include/OgreImGuiOverlay.h:12:10: fatal error: imgui.h: No such file or directory
   12 | #include <imgui.h>
      |          ^~~~~~~~~
compilation terminated.
````
Seems like the include directory is missing when imgui is deactivated.

### Hotfix:
I thought to just add the imgui include directory and the header to the includes list, but compilation still fails with
````
In file included from Samples/include/ImGuiDemo.h:4,
                 from /home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Samples/Common/src/DefaultSamplesPlugin.cpp:53:
/home/portage/dev-games/ogre-1.12.3/work/ogre-1.12.3/Components/Overlay/include/OgreImGuiOverlay.h:12:10: fatal error: imgui.h: No such file or directory
   12 | #include <imgui.h>
      |          ^~~~~~~~~
compilation terminated.
````
For now I am giving up and will deactivate the overlays until I can properly patch this, or it is fixed in master.

**Comment by Yamakuzure** [comment]
Ok, found the issue. The imgui subfolder is a submodule; Which is not included when downloading a release.

**Comment by Yamakuzure** [comment]
I now fetch using git and checkout the submodule and everything works.

However, could you please include imgui in the next release?

**Comment by mathacka** [comment]
Same thing happened to me, thanks for your solution

**Comment by paroj** [comment]
blocked by https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073

**Comment by MrBenGriffin** [comment]
If you have already cloned ogre, you can do this:
```
cd (path to ogre)
git submodule update --init --recursive
```

**Comment by aleksandaratanasov** [comment]
> blocked by https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073
> 
> workaround:
> 
> ```
> git clone --recursive --branch v1.12.3 https://github.com/OGRECave/ogre.git
> ```

This does not work. I tried checking out `v13.0.1` (latest tag) and I still get missing `imgui_tables.cpp`

**Comment by MrBenGriffin** [comment]
> This does not work. I tried checking out `v13.0.1` (latest tag) and I still get missing `imgui_tables.cpp`

Try
```
cd (path to ogre)
git submodule update --init --recursive
```

**Comment by paroj** [comment]
imgui is no longer a submodule. If you are upgrading from 1.12, delete your build folder. (or take a look at IMGUI_DIR in cmake)
