### ISSUE TITLE
ShadowDepth Error occur By render a  refelect texture

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#1337]
#### System Information
- Ogre Version: :Ogre1.12.3: 
- Operating System / Platform: :grey_question: Win7 and Win10 
- RenderSystem: :grey_question: GL3Plus RenderSystems

#### Detailled description

I Use the  GL3Plus RenderSystems, then main window is a rendertexture. I use the  pssm shadow  technique （i.e ShadowTechnique::SHADOWTYPE_TEXTURE_ADDITIVE_INTEGRATED）, then I create a rendertexture to implent the water reflect.  finally the shadow becom error.  and then reason is the the reflect texture's update affected the shadow texture。 also i try close the depth write and set a different depth buffer id when render reflect texture. but  make no sense。 only I stop update the reflect texture  then shadow become right.

#### Ogre.log
<!-- when attaching code or the log use triple backticks as below:
the log is right.
paste your log here
```
-->

**Comment by 36yang** [comment]
the result right when use old rendsystem like gl or dx9, only occur in gl3 but not try dx11

**Comment by paroj** [comment]
I guess the problem is that the AutoParamDataSource somehow mixes up the active camera and/ or the texture projection matrix. But I will need to investigate.
Do you have some reproducer code?

**Comment by 36yang** [comment]
The project too large, I will take some time to reappear the problem in a new project. then I will show the code here

**Comment by 36yang** [comment]
This is  all the src code that can show the problem:
It's a win32 program

file: main.cpp

#include <Windows.h>
#include <ShellAPI.h> //文件拖拽用到

//打开控制台
#include <stdio.h>
#include <io.h>
#include <fcntl.h> 

#include "Ogre.h"
#include "WaterObj.h"

HWND hWnd;  //保存窗口句柄
HINSTANCE gHInstance; //保存程序句柄
const char* WND_CLASS_NAME = "Main_window";
LRESULT CALLBACK	WndProc(HWND, UINT, WPARAM, LPARAM);

Ogre::SceneManager* mSceneMgr;
Ogre::RenderWindow* mWindow;
Ogre::Root* mRoot;



//打开控制台窗口
BOOL CreateConsole(void)
{
	FreeConsole();
	if (AllocConsole())
	{
		int hCrt = _open_osfhandle((long)
			GetStdHandle(STD_OUTPUT_HANDLE), _O_TEXT);
		*stdout = *(::_fdopen(hCrt, "w"));
		::setvbuf(stdout, NULL, _IONBF, 0);
		*stderr = *(::_fdopen(hCrt, "w"));
		::setvbuf(stderr, NULL, _IONBF, 0);
		return TRUE;


	}return FALSE;
}


void createScene()
{
	mSceneMgr->setAmbientLight(Ogre::ColourValue(0.3, 0.3, 0.3));

	mSceneMgr->setShadowTechnique(Ogre::ShadowTechnique::SHADOWTYPE_TEXTURE_ADDITIVE_INTEGRATED);

	Ogre::LiSPSMShadowCameraSetup* lispsmSetup = new Ogre::LiSPSMShadowCameraSetup();
	Ogre::ShadowCameraSetupPtr mCurrentShadowCameraSetup = Ogre::ShadowCameraSetupPtr(lispsmSetup);
	mSceneMgr->setShadowCameraSetup(mCurrentShadowCameraSetup);
	if (mRoot->getRenderSystem()->getCapabilities()->hasCapability(Ogre::RSC_HWRENDER_TO_TEXTURE))
	{
		mSceneMgr->setShadowTextureSettings(4096, 1, Ogre::PF_FLOAT32_R, 0, 50);  // In D3D, use a 1024x1024 shadow texture
		mWindow->setDepthBufferPool(10);
	}
	else
	{
		mSceneMgr->setShadowTextureSettings(512, 1, Ogre::PF_FLOAT32_R, 0, 50);  // Use 512x512 texture in GL since we can't go higher than the window res
		mWindow->setDepthBufferPool(10);
	}
	Ogre::MaterialPtr casterMat = Ogre::MaterialManager::getSingletonPtr()->getByName("PSSM/shadow_caster");
	mSceneMgr->setShadowTextureCasterMaterial(casterMat);
	const float shadowFar = 35;  //阴影计算距离100米
	mSceneMgr->setShadowFarDistance(shadowFar);
	mSceneMgr->setShadowTextureCountPerLightType(Ogre::Light::LT_DIRECTIONAL, 1);
	Ogre::GpuSharedParametersPtr p = Ogre::GpuProgramManager::getSingleton().getSharedParameters("pssm_params");
	p->setNamedConstant("shadowParams", Ogre::ColourValue(0.7f, 0.7f, 0.7f, 0.15f)); //阴影参数，1-rgb表示阴影颜色， a表示阴影技术（a<0.1无阴影 a<0.2liPSM a<0.3PSSM）
	p->setNamedConstant("shadowParams2", Ogre::Vector4(0.000488f, -0.0001f, 0.00625f, 0.0f)); //阴影参数inverseShadowmapSize，fixedDepthBias，gradientClamp，gradientScaleBias
	p->setNamedConstant("pssmSplitPoints", Ogre::Vector4(0.01f, 10.0f, 60.0f, shadowFar));

	Ogre::Light* l2 = mSceneMgr->createLight();
	l2->setType(Ogre::Light::LT_DIRECTIONAL);
	l2->setDirection(Ogre::Vector3(0.577350, -0.577350, -0.577350));
	l2->setDiffuseColour(1.0f, 1.0f, 1.0f);
	l2->setSpecularColour(1.0f, 1.0f, 1.0f);
	l2->setCastShadows(true);


	Ogre::Entity* floor = mSceneMgr->createEntity("plane.mesh");
	Ogre::SceneNode* floorNode = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	floorNode->attachObject(floor);
	floor->setCastShadows(false);
	floorNode->setScale(4, 1, 4);
	floor->setMaterialName("RockWall");

	Ogre::Entity* qiao = mSceneMgr->createEntity("Prefab_Cube");
	qiao->setMaterialName("cubb");
	Ogre::SceneNode* qiaoNode = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	qiaoNode->attachObject(qiao);
	qiaoNode->setScale(0.01, 0.03, 0.01);
	//qiao->setCastShadows(false);
	qiaoNode->setPosition(-3.8259, 3, 2.2846);

	Ogre::Entity* qiao2 = mSceneMgr->createEntity("Prefab_Cube");
	qiao2->setMaterialName("cubb");
	Ogre::SceneNode* qiaoNode2 = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	qiaoNode2->attachObject(qiao2);
	qiaoNode2->setScale(0.01, 0.03, 0.01);
	qiaoNode2->setPosition(0, 3, -2);
	//qiao->setCastShadows(false);

	Ogre::Entity* shu1 = mSceneMgr->createEntity("法师职业_树_05.mesh");
	Ogre::SceneNode* shu1Node = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	shu1Node->attachObject(shu1);
	shu1Node->setPosition(-4.4454, 0, 5.3547);
	shu1Node->setScale(0.01, 0.01, 0.01);
	
	Ogre::Entity* shu2 = mSceneMgr->createEntity("法师职业_树_05.mesh");
	Ogre::SceneNode* shu2Node = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	shu2Node->attachObject(shu2);
	shu2Node->setPosition(-1.8099, 0, 5.8852);
	shu2Node->setScale(0.01, 0.01, 0.01);

	Ogre::Entity* shu3 = mSceneMgr->createEntity("法师职业_树_05.mesh");
	Ogre::SceneNode* shu3Node = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	shu3Node->attachObject(shu3);
	shu3Node->setPosition(-2.7873, 0, -0.4701);
	shu3Node->setScale(0.01, 0.01, 0.01);

	Ogre::Entity* shu4 = mSceneMgr->createEntity("法师职业_树_05.mesh");
	Ogre::SceneNode* shu4Node = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	shu4Node->attachObject(shu4);
	shu4Node->setPosition(0.0674, 0, 2.6881);
	shu4Node->setScale(0.01, 0.01, 0.01);

	Ogre::Entity* shu5 = mSceneMgr->createEntity("法师职业_树_05.mesh");
	Ogre::SceneNode* shu5Node = mSceneMgr->getRootSceneNode()->createChildSceneNode();
	shu5Node->attachObject(shu5);
	shu5Node->setPosition(-6.1153, 0, 2.9846);
	shu5Node->setScale(0.01, 0.01, 0.01);

	WaterObj* waterplane = new WaterObj(NULL, mWindow->getViewport(0)->getCamera(), true);
	waterplane->mEntity->setCastShadows(false);
	waterplane->mActiveVertexParameters->setNamedConstant("waveAmp", 0.01f);
	waterplane->mNode->setPosition(0, 2.0f, 4);
}

void setupScene()
{
	mSceneMgr = mRoot->createSceneManager(Ogre::ST_GENERIC);

	Ogre::Camera* mCamera = mSceneMgr->createCamera("mainCamera");
	mCamera->setNearClipDistance(0.1);
	mCamera->setFarClipDistance(500);
	mCamera->setAutoAspectRatio(true);
	Ogre::Viewport* vp = mWindow->addViewport(mCamera);
	vp->setBackgroundColour(Ogre::ColourValue(0.0f, 0.3f, 0.0f));
	//vp->getTarget()->setDepthBufferPool(30);

	mCamera->setPosition(0, 10, -10);
	mCamera->lookAt(0, 0, 0);


	Ogre::String mediaPath = "../media/";
	auto managers = Ogre::ResourceGroupManager::getSingleton().getResourceManagerIterator();
	for (auto it = managers.begin(); it != managers.end(); ++it)
	{
		auto resours = it->second->getResourceIterator();
		Ogre::LogManager::getSingleton().logMessage(it->second->getResourceType());
		for (auto itr = resours.begin(); itr != resours.end(); ++itr)
		{
			auto resss = itr->second->getName();

			Ogre::LogManager::getSingleton().logMessage(resss);
		}
	}
	Ogre::StringVector vd = Ogre::ResourceGroupManager::getSingletonPtr()->getResourceGroups();
	for (int i = 0; i < vd.size(); i++)
	{
		Ogre::LogManager::getSingleton().logMessage(vd.at(i));
	}

	//pssm阴影公用参数
	Ogre::GpuSharedParametersPtr parames = Ogre::GpuProgramManager::getSingleton().createSharedParameters("pssm_params");
	parames->addConstantDefinition("pssmSplitPoints", Ogre::GpuConstantType::GCT_FLOAT4);
	parames->addConstantDefinition("shadowParams", Ogre::GpuConstantType::GCT_FLOAT4);
	parames->addConstantDefinition("shadowParams2", Ogre::GpuConstantType::GCT_FLOAT4);
	parames->setNamedConstant("shadowParams", Ogre::ColourValue(0.3f, 0.3f, 0.3f, 0.25f)); //阴影参数，rgb表示阴影颜色， a表示阴影技术（a<0.1无阴影 a<0.2PSM a<0.3PSSM）
	parames = Ogre::GpuProgramManager::getSingletonPtr()->createSharedParameters("fog_params");
	parames->addConstantDefinition("fogColor", Ogre::GpuConstantType::GCT_FLOAT4);
	parames->addConstantDefinition("fogParams", Ogre::GpuConstantType::GCT_FLOAT4); //mode start end density mode雾类型[没有，线性 指数]
	parames->setNamedConstant("fogColor", Ogre::ColourValue(0.0f, 0.0f, 0.0f, 1.0f));
	parames->setNamedConstant("fogParams", Ogre::Vector4(0, 0, 100, 0.01f));

	//*
	//引擎核心资源，最先初始化
	Ogre::ResourceGroupManager::getSingleton().createResourceGroup("Core", true);
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "core", "FileSystem", "Core");
	Ogre::ResourceGroupManager::getSingletonPtr()->initialiseResourceGroup("Core");
	//Ogre内部资源
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "core/ShadowVolume", "FileSystem", Ogre::ResourceGroupManager::INTERNAL_RESOURCE_GROUP_NAME);
	//给内置材质加上shader
	Ogre::MaterialPtr mat = Ogre::MaterialManager::getSingleton().getByName("BaseWhite");
	if (!mat->isLoaded()) { mat->load(); }
	mat->getBestTechnique()->getPass(0)->setVertexProgram("BaseWhite_VS");
	mat->getBestTechnique()->getPass(0)->setFragmentProgram("BaseWhite_FS");
	mat = Ogre::MaterialManager::getSingleton().getByName("BaseWhiteNoLighting");
	if (!mat->isLoaded()) { mat->load(); }
	mat->getBestTechnique()->getPass(0)->setVertexProgram("BaseWhite_VS");
	mat->getBestTechnique()->getPass(0)->setFragmentProgram("BaseWhiteNoLight_FS");
	mat = Ogre::MaterialManager::getSingleton().getByName("DefaultSettings");
	if (!mat->isLoaded()) { mat->load(); }
	mat->getBestTechnique()->getPass(0)->setVertexProgram("BaseWhite_VS");
	mat->getBestTechnique()->getPass(0)->setFragmentProgram("BaseWhite_FS");

	Ogre::ResourceGroupManager::getSingleton().createResourceGroup("Terrain");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "Terrain", "FileSystem", "Terrain");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/SETerrain/glsl", "FileSystem", "Terrain");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/SETerrain", "FileSystem", "Terrain");

	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/water", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/texture", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/shadow", "FileSystem", "General");

	
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "mesh", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "mesh/sinbad", "FileSystem", "General");
	
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/JXSky/BoxSky", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/JXSky/PlaneSky", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/JXSky/DomeSky", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/JXSky", "FileSystem", "General");
	//instance
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/Instance/man", "FileSystem", "General");
	Ogre::ResourceGroupManager::getSingleton().addResourceLocation(mediaPath + "materials/Instance", "FileSystem", "General");
	//*/

	Ogre::ResourceGroupManager::getSingleton().initialiseAllResourceGroups();

	//添加一个内置的水平面
	Ogre::Plane plane(Ogre::Vector3::UNIT_Y, 0);
	Ogre::MeshManager::getSingletonPtr()->createPlane("plane.mesh", Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME,
		plane, 10, 10, 1, 1, true, 1, 1, 1, Ogre::Vector3::UNIT_Z);
}




INT WINAPI WinMain(HINSTANCE hInst, HINSTANCE, LPSTR strCmdLine, INT argc)
{
	WNDCLASS wc =
	{
		0, WndProc, 0, 0, GetModuleHandle(NULL), LoadIcon(NULL, MAKEINTRESOURCE(1001)),
		LoadCursor(NULL, IDC_ARROW), (HBRUSH)GetStockObject(BLACK_BRUSH), NULL, TEXT(WND_CLASS_NAME),
	};
	RegisterClass(&wc);
	gHInstance = hInst;

	UINT width = GetSystemMetrics(SM_CXSCREEN);
	UINT height = GetSystemMetrics(SM_CYSCREEN);
	//p_appMgr->ScreenW = width; p_appMgr->ScreenH = height;
	//窗口的样式 WS_OVERLAPPEDWINDOW  WS_OVERLAPPEDWINDOW^WS_THICKFRAME WS_DLGFRAME|WS_SYSMENU
	//hWnd = CreateWindow(wc.lpszClassName, TEXT("JXSceneEditor"), WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT, 1280, 720, NULL, NULL, wc.hInstance, NULL);
	//创建一个支持文件拖拽的窗口|WS_EX_ACCEPTFILES
	hWnd = CreateWindowEx(WS_EX_ACCEPTFILES, wc.lpszClassName, TEXT("JXSceneEditor"), WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT, 1280, 720, NULL, NULL, wc.hInstance, NULL);
	if (!hWnd){ return false; }

	//CreateConsole(); //打开控制台
	mRoot = new Ogre::Root("", "");


#ifndef OGRE_STATIC_LIB
#ifdef _DEBUG
	mRoot->loadPlugin("Codec_STBI_d.dll");
	//mRoot->loadPlugin("RenderSystem_Direct3D9_d.dll");
	//mRoot->loadPlugin("RenderSystem_GL_d.dll");
	mRoot->loadPlugin("RenderSystem_GL3Plus_d.dll");
	//mRoot->loadPlugin("RenderSystem_Direct3D11_d.dll");
	//mRoot->loadPlugin("Plugin_BSPSceneManager_d.dll");
#else
	Root->loadPlugin("Codec_STBI.dll");
	//mRoot->loadPlugin("RenderSystem_Direct3D9.dll");
	//mRoot->loadPlugin("RenderSystem_GL.dll");
	mRoot->loadPlugin("RenderSystem_GL3Plus.dll");
	mRoot->loadPlugin("Plugin_BSPSceneManager.dll");
	mRoot->loadPlugin("Plugin_ParticleFX.dll");
#endif
#else
		//静态链接版初始化插件//
	Ogre::STBIPlugin* pImgCodecPlugin = OGRE_NEW Ogre::STBIPlugin();
	mRoot->installPlugin(pImgCodecPlugin);
	Ogre::GL3PlusPlugin* pGl3plugin = OGRE_NEW Ogre::GL3PlusPlugin();
	mRoot->installPlugin(pGl3plugin);
	Ogre::BspSceneManagerPlugin* gBspSceneManagerPlugin = OGRE_NEW Ogre::BspSceneManagerPlugin();
	mRoot->installPlugin(gBspSceneManagerPlugin);
#endif // !OGRE_STATIC_LIB


	Ogre::RenderSystem* rsys = mRoot->getAvailableRenderers().at(0);
	mRoot->setRenderSystem(rsys);
	mRoot->initialise(false);//禁止ogre创建新的渲染窗口 

	Ogre::NameValuePairList params;
	params["externalWindowHandle"] = std::to_string((long)hWnd);
	params["vsync"] = "No";   //开启垂直同步
	//params["gamma"] = "Yes";   //开启Gamma校正
	params["FSAA"] = "4";     //抗锯齿等级
	params["colourDepth"] = "32"; //颜色深度
	params["depthBuffer"] = "No"; //GL3不创建深度缓冲
	mWindow = mRoot->createRenderWindow(
		"mainWindow",   //窗口名字
		1280,        //使用外部窗口，这里的宽高参数被忽略
		720,
		false,             //是否全屏显示		
		&params);


	setupScene();
	createScene();

	ShowCursor(true); 
	ShowWindow(hWnd, SW_SHOW);
	UpdateWindow(hWnd);

	MSG msg;
	while (true)
	{
		//if
		while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))  //PM_REMOVE 收到一个消息后，将这个消息从消息队列中移除，PM_NOREMOVE顾名思义就是不移除该消息了。
		{
			if (msg.message == WM_QUIT)
				return 0;
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}

		if (mWindow != NULL)
		{
			if (mWindow->isActive())
			{
				try
				{	
					mRoot->renderOneFrame();	
				}
				catch (Ogre::Exception e)
				{
					Ogre::LogManager::getSingleton().logMessage("捕获到异常请尽快处理");
					Ogre::LogManager::getSingleton().logMessage(e.getDescription());
				}
			}
		}
	}
	return (int)msg.wParam;
}




LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
	int wmId, wmEvent;
	PAINTSTRUCT ps;
	HDC hdc;

	if (::GetForegroundWindow() == hWnd)   //当前窗口是活动窗口，否则不响应鼠标事件//
	{

		POINT point;
		if (message == WM_KEYDOWN) //按键按下
		{
			bool repeat = (lParam & (1 >> 30)) != 0;
			if (!repeat)
			{

			}

		}
		else if (message == WM_KEYUP) //按键松开
		{
			//Ogre::LogManager::getSingletonPtr()->logMessage("WM_KEYUP");
		
		}
		else if (message == WM_MOUSEMOVE)  	//鼠标移动//
		{
			//int x = (short)HIWORD(lParam);
			//int y =(short)HIWORD(lParam);
			GetCursorPos(&point);
			ScreenToClient(hWnd, &point); //换成客户区坐标
			long touchId[1]; float Xs[1]; float Ys[1];
			touchId[0] = 0; Xs[0] = point.x; Ys[0] = point.y;
		}
		else if (message == WM_LBUTTONDOWN)    //左键按下//
		{
			

		}
		else if (message == WM_RBUTTONDOWN)    //右键按下//
		{
		}
		else if (message == WM_LBUTTONUP)    //左键键抬起//
		{
			
		}
		else if (message == WM_RBUTTONUP)  //右键抬起//
		{
			
		}
		else if (message == WM_MBUTTONDOWN)  //中键按下
		{
			
		}
		else if (message == WM_MBUTTONUP)   //中键抬起//
		{

		}
		else if (message == WM_MOUSEWHEEL)       //鼠标滚轮//
		{
			
		}
		else if (message == WM_TOUCH)     //触摸屏操作
		{
			
		} //触摸操作
		else if (message == WM_CHAR)
		{
			//wchar_t ch = (wchar_t)wParam;
			//char ch =  wParam;
			//MyGUI::UString str(&ch);
			//p_appMgr->EditBoxinsertText(str);
			//return 0;
		}
		else if (message == WM_IME_CHAR)
		{
			return 0;
		}
	} //是否活动窗口//



	switch (message)
	{
	case WM_COMMAND:
		wmId = LOWORD(wParam);
		wmEvent = HIWORD(wParam);
		break;
	case WM_PAINT:
		hdc = BeginPaint(hWnd, &ps);
		// TODO: 在此添加任意绘图代码...
		EndPaint(hWnd, &ps);
		break;
		//case WM_CREATE:
	case WM_SIZE:   //窗口大小改变

		break;

	case WM_CLOSE: //窗口关闭消息
	{	
		return DefWindowProc(hWnd, message, wParam, lParam); //默认关闭		   
		break;
	}
	case WM_DROPFILES:  //拖拽文件
		//OnDropFiles((HDROP)wParam);
		break;
	case WM_DESTROY:
		PostQuitMessage(0);
		break;
	default:
		return DefWindowProc(hWnd, message, wParam, lParam);
	}
	return DefWindowProc(hWnd, message, wParam, lParam);
}

**Comment by paroj** [comment]
the interesting part is in `WaterObj` I guess. Please attach the code as .txt to keep this readable.

**Comment by 36yang** [comment]
yes , I update it in the before comment

**Comment by 36yang** [comment]
some shortcuts
![warn](https://user-images.githubusercontent.com/6148501/69287865-af780d00-0c32-11ea-8e4f-50a6b8aa21d8.png)
![rsult0](https://user-images.githubusercontent.com/6148501/69287805-8788a980-0c32-11ea-9cde-26459de3cd32.png)
![result1](https://user-images.githubusercontent.com/6148501/69287822-91aaa800-0c32-11ea-97f2-faaae929a51c.png)

**Comment by paroj** [comment]
without any of the required resources, all I can get to is this:
![bug](https://user-images.githubusercontent.com/4941802/69431439-0a475c80-0d38-11ea-98c8-48f330ce1ced.png)

**Comment by 36yang** [comment]
[OgreBUG.rar.txt](https://github.com/OGRECave/ogre/files/3881837/OgreBUG.rar.txt)
I send my project to you, In the archive file.  all  the media files are include.It can be opened by Visual studio, only debug.
Thank for your reply

**Comment by 36yang** [comment]
the resource shader only implent the depth shadow

**Comment by paroj** [comment]
the issue seems to be the custom near clip plane. Removing that also removes the artifacts. If you rely on that, you might want to use a second camera that follows the main one, like in PlayPen_ReflectedBillboards

**Comment by 36yang** [comment]
Thank you, I used a second camera to render the reflect texture, the shadow become right.
