### ISSUE TITLE
Dynamic linker issue on macOS Catalina when launching the project

### ISSUE THREAD

**Issue by yopox** [OGRECave/ogre#1345]
#### System Information
- Ogre Version: 1.12.4
- Operating System / Platform: macOS Catalina 10.15.1
- RenderSystem: OpenGL

#### Detailed description
I managed to build the latest source and put the content of the `sdk` folder in `/usr/local/ogre`.
I'm using CLion to build the project, here is my `CMakeLists.txt` :

```cmake
cmake_minimum_required(VERSION 3.15)
project(crystals_cpp)

set(CMAKE_CXX_STANDARD 17)

find_package(OGRE 1.12.4 REQUIRED COMPONENTS Bites RTShaderSystem)

file(GLOB_RECURSE SRCS "${PROJECT_SOURCE_DIR}/src/*.cpp")
file(GLOB_RECURSE HDRS "${PROJECT_SOURCE_DIR}/src/*.h")
file(COPY ${OGRE_CONFIG_DIR}/resources.cfg DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

add_executable(${PROJECT_NAME} MACOSX_BUNDLE ${SRCS} ${HDRS})

target_link_libraries(
        ${PROJECT_NAME}
        ${OGRE_LIBRARIES}
)
```

I can build successfully :

```
% cmake .
-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : /usr/local/ogre/Media
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yopox/GitHub/crystals-cpp
```

However, when I launch the project, there is an issue with `dyld` :

```
% ./crystals_cpp
dyld: Library not loaded: @executable_path/../Frameworks/OgreRTShaderSystem.framework/Versions/1.12.4/OgreRTShaderSystem
  Referenced from: /Users/yopox/GitHub/crystals-cpp/./crystals_cpp
  Reason: image not found
```

I found a workaround on other issues (using `install_name_tool -change` to set the correct paths), but it doesn't fix the issue :

```
% otool -L crystals_cpp
crystals_cpp:
	/usr/local/ogre/lib/macosx/Release/OgreBites.framework/Versions/1.12.4/OgreBites (compatibility version 1.12.4, current version 1.12.4)
	/usr/local/ogre/lib/macosx/Release/OgreRTShaderSystem.framework/Versions/1.12.4/OgreRTShaderSystem (compatibility version 1.12.4, current version 1.12.4)
	/usr/local/ogre/lib/macosx/Release/OgreOverlay.framework/Versions/1.12.4/OgreOverlay (compatibility version 1.12.4, current version 1.12.4)
	/usr/local/ogre/lib/macosx/Release/Ogre.framework/Versions/1.12.4/Ogre (compatibility version 1.12.4, current version 1.12.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
% ./crystals_cpp
dyld: Library not loaded: @executable_path/../Frameworks/OgreOverlay.framework/Versions/1.12.4/OgreOverlay
  Referenced from: /usr/local/ogre/lib/macosx/Release/OgreBites.framework/Versions/1.12.4/OgreBites
  Reason: image not found
```

Am I missing something in the `CMakeLists.txt` ?  It seems strange that Ogre is found when compiling but not anymore when launching the game.

**Comment by lorrden** [comment]
That seems to imply that the OgreBites.framwork wants to load OgreOverlay relative to the executable (crystals_cpp). That implies that the library should be located in a folder called frameworks on level above the crystals_cpp, that is if you have an executable bundle for it, the exec ends up in foo.app/Contents/MacOS/crystals_cpp, then the referenced frameworks should be in foo.app/Contents/Frameworks/

Also, it is easier to debug these issues using `otool -l` (flag is small ell), which will show also rpath definitions in the executable or library.

**Comment by paroj** [comment]
to fix this properly, see:
https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/RPATH-handling

I have no OSX access right now, so somebody else will have to test & fix this.
