### ISSUE TITLE
GLSL: sampler2D[] only gets first array value set

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/ogre#1352]
#### System Information
- Ogre Version: 1.12 (master)
- Operating System / Platform: Windows 10 64-bit
- RenderSystem: OpenGL3+

#### Detailled description
Setting sampler2D array values from C++ code only sets the first value but rest of the array values are left unset. Int array and float array values do get set correctly.

I tried setting the values via `int*` function and separately with the `"name[0]"`, `"name[1]"`, etc syntax.

Here is simplified C++ code for setting the sampler2D[] values:
```cpp
int numSamplers = 0;
std::vector<int> normalSamplers(LAYER_COUNT);

for (size_t i = 0; i < LAYER_COUNT; ++i)
{
    colorSamplers[i] = numSamplers++;
}

params->setNamedConstant("colorTexture", colorSamplers.data(), LAYER_COUNT, 1);
```

And usage on the GLSL side:
```glsl
uniform sampler2D colorTexture[LAYER_COUNT];
```

`LAYER_COUNT` is preprocessor define and seems to be working correctly.

**Comment by paroj** [comment]
does it work if you change `1` to `glArraySize` here:
https://github.com/OGRECave/ogre/blob/master/RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLMonolithicProgram.cpp#L361

**Comment by SNiLD** [comment]
That does indeed fix it!
