### ISSUE TITLE
ManualObjectSection::getMaterialName() returns group name

### ISSUE THREAD

**Issue by fractilegames** [OGRECave/ogre#1364]
#### System Information
- Ogre Version: master
- Operating System / Platform: X11
- RenderSystem: GL

#### Detailled description

ManualObjectSection constructor sets mMaterialName to group name.

**Comment by paroj** [comment]
looks like a typo. Can you provide a PR fixing this?

**Comment by fractilegames** [comment]
https://github.com/OGRECave/ogre/pull/1365
