### ISSUE TITLE
Sometimes specific Terrain will not be visible

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/ogre#1373]
#### System Information
- Ogre Version: 1.12-master
- Operating System / Platform: Windows 10 64-bit
- RenderSystem: OpenGL3+

#### Detailled description
This issue has existed for a long time (at least since 1.9), but it has started occuring more and more with every major update of Ogre. Now with 1.12 and especially with relatively flat surfaces this occurs quite consistently.

Only way that I've found how to detect that this is happening is to compare the terrain root scene node AABB vs. the terrain WorldAABB like this:

`camera->isVisible(terrain->_getRootSceneNode()->_getWorldAABB()) != camera->isVisible(terrain->getWorldAABB())`

If that is true, then also the terrain will not be visible. I've still been unable to locate the real reason why those AABB's would be different in that case and what could cause it.

**Comment by paroj** [comment]
which scene manager are you using?

**Comment by SNiLD** [comment]
I'm using the DefaultSceneManager. Terrain instances are handled by TerrainGroup and terrain block loads are triggered by TerrainPagedWorldSection.

If I unload the terrain when I detect that broken AABB and load it again it usually loads as visible and working one. This is the method I have been using previously for getting it to work. But nowadays this happens too often and I have to reload the terrain blocks all the time.

**Comment by SNiLD** [comment]
I need to investigate this more. It seems that with Ogre 1.12 that method of detecting that the Terrain would not be visible is no longer valid (i.e. it gives a lot of false positives). It might be that the disappearing Terrain blocks has actually been fixed in 1.12 and is no longer happening or is happening very rarely.

**Comment by SNiLD** [comment]
Ok, the disappearing Terrain blocks still happens (rarely), but indeed the method for detecting it gives a lot of false positives.

**Comment by paroj** [comment]
are you loading the terrain blocks synchronously or in background?

**Comment by SNiLD** [comment]
They are loaded in background.

**Comment by paroj** [comment]
can you reproduce this with synchronous loading as well? (that would give a hint whether we are looking for a race or a logical bug)
