### ISSUE TITLE
MaterialManager::setDefault* no longer works with mipmap_bias

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/ogre#1422]
#### System Information
- Ogre Version: 1.12.4
- Operating System / Platform: Windows 10 64-bit
- RenderSystem: OpenGL3+

#### Detailled description

`MaterialManager::setDefaultAnisotropy` and `MaterialManager::setDefaultTextureFiltering` used to set the defaults for textures that are added from material files via `texture_unit` block. These functions do not work anymore. I'm not exactly sure which version broke this, but it used to work at least with the basic OpenGL RenderSystem.

It seems that this only affects when `mipmap_bias` is used. We had `mipmap_bias -2` in material and that must have forced linear filtering to the material. You can close this ticket if this is the intended behavior (documentation doesn't say that it will explicitly change the filtering type).

**Comment by paroj** [comment]
this is likely related to the Sampler Object change described here:
https://www.ogre3d.org/2018/10/24/ogre-1-11-mid-term-report

changing any sampling related parameter will create a new local sampler for that TUS and thus not use any of the default settings.

**Comment by SNiLD** [comment]
This is fixed by documenting the new functionality in https://github.com/OGRECave/ogre/commit/cd1d39e889cd577a764d6b2d482a66c3346d08d6.
