### ISSUE TITLE
Shared params & Uniform buffer

### ISSUE THREAD

**Issue by LMCrashy** [OGRECave/ogre#1476]
Hi,

I'm trying to use the gpu shared parameters in combination with Uniform buffers, but there is an issue with the GpuSharedParameters::_upload() implementation.

The function iterates through the map of params and calculates the offset like this:

```
// in bytes
            size_t length = param.arraySize * param.elementSize * 4;
            mHardwareBuffer->writeData(offset, length, dataPtr);
            offset += length;
```

However, the map is ordered alphabetically, and there is a mismatch between the offset calculated this way and the actual offset in the uniform buffer in the gpu.

Example:
Here is my shared_param declaration

```
shared_params FogParams
{
	shared_param_named sunDirection float4 0 -1 0 0
	shared_param_named sunColor 	float4 1 1 1 0
	shared_param_named sunPower 	float 1
	
	shared_param_named BetaRay float3 		0.0020687620  0.0034983605  0.0072542001
	shared_param_named BetaMie float3 		0.00036545776 0.00047315995 0.00066936179
}

```

and the uniform block (glsl):

```
layout(shared) uniform FogParams
{
	vec4 sunDirection;
	vec4 sunColor;
	float sunPower;
	
	vec3 BetaRay;
	vec3 BetaMie;
	vec4 DensityAlt;
}

```

But when uploading params, the order is

>BetaMie
>BetaRay
>DensityAlt
>...
>(etc)

Therefore, the values aren't uploaded at the right place.

Maybe the GpuConstantDefinitionMap should use an unordered map, or the offset should be calculated using the physical index instead.

**Comment by LMCrashy** [comment]
Actually, there is another issue, at least in GL3+.

Of course if one wants to share the same uniform buffer across different shaders it nees the buffer to use the "shared" layout to have the same offsets everywhere.

The offset for each uniform is not "guessable", one need to retrieve it from the program handle.
This pic from nSight show that 

![image](https://user-images.githubusercontent.com/28775797/75606617-e641a700-5aee-11ea-85b1-d1a40c368928.png)

Here, BetaRay is at offset 48 which is not 4*4(sunDirection) + 4*4 (sunColor) + 4(sunPower) = 36. "sunPower" is having a 4*4bytes size, but other floats from my constant buffer( I've only displayed a small part of it) are indeed using a 4bytes size.

Previously, there was this code in the GL3+RS to retrieve the offsets

```
// Get active block parameter properties.
GpuConstantDefinitionIterator sharedParamDef = blockSharedParams->getConstantDefinitionIterator();
std::vector<const char*> sharedParamNames;
for (; sharedParamDef.current() != sharedParamDef.end(); sharedParamDef.moveNext())
{
	sharedParamNames.push_back(sharedParamDef.current()->first.c_str());
}

std::vector<GLuint> uniformParamIndices(sharedParamNames.size());
std::vector<GLint> uniformParamOffsets(sharedParamNames.size());

OGRE_CHECK_GL_ERROR(glGetUniformIndices(mGLProgramHandle, sharedParamNames.size(), &sharedParamNames[0], &uniformParamIndices[0]));
//FIXME debug this (see stdout)
OGRE_CHECK_GL_ERROR(glGetActiveUniformsiv(mGLProgramHandle, uniformParamIndices.size(), &uniformParamIndices[0], GL_UNIFORM_OFFSET, &uniformParamOffsets[0]));

GpuNamedConstants& consts = const_cast<GpuNamedConstants&>(blockSharedParams->getConstantDefinitions());
MapIterator<GpuConstantDefinitionMap> sharedParamDefMut(consts.map);
```

But in current implementation, nothing retrieves the actual location of uniforms in the buffer.

**Comment by paroj** [comment]
> The offset for each uniform is not "guessable", one need to retrieve it from the program handle.

you are required to use `std140` for shared_params  at the moment

https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Memory_layout

**Comment by LMCrashy** [comment]
I've also tried with std140 layout qualifier before, this doesn't help with the offset issue:

![image](https://user-images.githubusercontent.com/28775797/75607523-50ab1500-5af8-11ea-9f50-9c4fe0f59d3b.png)

Sometimes a float uses 4bytes, sometimes 16bytes, vec3 uses 16bytes here and not 9.
This is not predictable and should be retrieved from the gpu program

**Comment by paroj** [comment]
> This is not predictable and should be retrieved from the gpu program

no, it is specified as per the link above. e.g. vec3 is required to be 16byte aligned. We just dont adhere to the rules in ogre.

The real question is whether its easier to implement the rules or query the driver.

**Comment by paroj** [comment]
#1477 should yield the above offsets and fix the upload iteration

**Comment by LMCrashy** [comment]
Thanks for your time and clarification. I was suspecting an aligment issue per uniform but not this way, it makes sense now.

Unfortunatly, this patch gives the same logical index for BetaMie and BetaRay: 48

Wouln't it be easier to accumulate offset in a member value when adding a new constant and calculate the next aligned position ? Using the size of the mXXXConstants lists doesn't give an accurate information of previous values alignment.

I'm working on a fix done this way, I'll tell if it works.

**Comment by paroj** [comment]
> Wouldn't it be easier to accumulate offset in a member value when adding a new constant and calculate the next aligned position ?

yeah, you are right. As of now, we are discarding any previous padding when calculating the offset.

**Comment by LMCrashy** [comment]
Woops, 
My fix proposal wasn't properly handling matrices.

I reworked it (again) in this commit : https://github.com/LMCrashy/ogre/commit/ab74f5c931b585c52518d3adbbe036d0a653e234

Tested it against this Uniform block 
```
layout(std140) uniform TestAlignment
{
	mat3 _mat33 ; 	//0
	mat4x3 _mat43 ; //48
	float _float ; 	//112
	mat3x4 _mat34 ; //128
	vec3 _vec3;	//176
	vec2 _vec2; 	//192
	mat4 _mat44; 	//208
	float _float1; 	//272
	float _float2; 	//276
	mat3 _mat33_2; 	//288
	mat2 _mat22 ;	//336
};
```

**Comment by paroj** [comment]
can you create a PR with this fix?
