### ISSUE TITLE
OGRE_PLUGIN_DIR CMake variable points to the wrong  directory on Windows

### ISSUE THREAD

**Issue by traversaro** [OGRECave/ogre#1499]
#### System Information
- Ogre Version: `master` branch, commit https://github.com/OGRECave/ogre/commit/2cd58e714b5cda53acf5144a2b51d0e7afb511b3 
- Operating System / Platform: Windows
- RenderSystem: Not Relevant 

#### Detailled description
The `OGRE_PLUGIN_DIR` CMake variable is exported in the `OGREConfig.cmake` file as "The directory where the OGRE plugins are located", see https://github.com/OGRECave/ogre/blame/a9ef702429de6ef037b4acf9b91570ccbe9ef179/Docs/src/tutorials/setup.md#L15 . However, it is always defined as `@PACKAGE_CMAKE_INSTALL_PREFIX@/lib/OGRE` (see https://github.com/OGRECave/ogre/blob/d33d5bb844d157ad2ad51f333f02051bc172d850/CMake/Templates/OGREConfig.cmake.in#L27), while on Windows the OGRE plugns are installed in ` `@PACKAGE_CMAKE_INSTALL_PREFIX@/bin`, see https://github.com/OGRECave/ogre/blob/2cd58e714b5cda53acf5144a2b51d0e7afb511b3/CMake/Utils/OgreConfigTargets.cmake#L101 (note that on Windows plugins are "RUNTIME" artifacts, while on Linux/macOS they are "LIBRARY"). 

I will be happy to open a  PR to fix this problem.

#### Ogre.log
Not relevant.

**Comment by paroj** [comment]
> I will be happy to open a PR to fix this problem.

please go ahead

**Comment by traversaro** [comment]
> 
> 
> > I will be happy to open a PR to fix this problem.
> 
> please go ahead

Done in  https://github.com/OGRECave/ogre/pull/1501 .
