### ISSUE TITLE
error C2338 when building with double precision

### ISSUE THREAD

**Issue by gmanol** [OGRECave/ogre#1502]
#### System Information
- Ogre Version: 1.12.5
- Operating System / Platform: Windows / x64
- Compiler: MSVC 2015

#### Detailed description
Build fails when compiling OgreInstanceBatch.cpp with double precision.

#### Build log
```
E:\Devel\Ogre\v1.12.5-master\ogre-master\OgreMain\src\OgreInstanceBatch.cpp(534): warning C4244: 'initializing': conversion from 'const Ogre::Real' to 'float', possible loss of data
e:\devel\ogre\v1.12.5-master\ogre-master\ogremain\include\OgreVector.h(61): error C2338: must have at least 4 dimensions
```

**Comment by paroj** [comment]
can you provide a pull-request fixing this?

**Comment by gmanol** [comment]
I'll try.

**Comment by paroj** [comment]
you need to do a clean build after changing that cmake setting
