### ISSUE TITLE
SkyBox use png texture with separateUV crashed

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#1507]
#### System Information
- Ogre Version: :grey_question: 1.12.4
- Operating System / Platform: :grey_question: win7
- RenderSystem: :grey_question: RenderSystem_GL3Plus

#### Detailled description

I set skybox use separateUV textures that is png/tga/dds format cause crashed,  the only work format is jpg. but it not support alpha. I will upload my resource in below.

**Comment by 36yang** [comment]
this is my skybox resource

- [ ] 
[BoxSky.zip](https://github.com/OGRECave/ogre/files/4393308/BoxSky.zip)

**Comment by paroj** [comment]
the issue is that `dld1_top.png` has a different pixel format (no alpha) compared to the other sides.

Need to investigate how to handle that.

**Comment by paroj** [comment]
try commenting out this line https://github.com/OGRECave/ogre/blob/f4644f00a238d02e0ef55a699980c0f9b16d455d/OgreMain/src/OgreTexture.cpp#L311

**Comment by 36yang** [comment]
Thank you, It is work now,  when I comment out the line, but don't know if it is has other problem.
