### ISSUE TITLE
[Solved] multiple colors on the same entity 

### ISSUE THREAD

**Issue by tesseract-solutions** [OGRECave/ogre#1539]
Hi,

I want to create an entity with several colors. 

So i think i need to create a material scirpt with vertex program ? 

I can generate script with vertex coordinates and color. 

May be someone have more info to create this one .... ? 

thank you

**Comment by paroj** [comment]
https://ogrecave.github.io/ogre/api/latest/_the-_core-_objects.html#Entities

**Comment by tesseract-solutions** [comment]
Thank you. 

But in an entity I can set one material. I want to add color at vertex or faces of my mesh. 

And entity class have not function to do it.

**Comment by paroj** [comment]
An entity is composed of several sub-entities, where each can have a different material.

Vertex colors are stored like any other vertex attribute. See this for how to create an according mesh manually:
https://ogrecave.github.io/ogre/api/latest/manual-mesh-creation.html

and on the material side: https://ogrecave.github.io/ogre/api/latest/_material-_scripts.html#diffuse

**Comment by tesseract-solutions** [comment]
Thank you,

I update attribute color of  my vertex. And i works fine !
