### ISSUE TITLE
[OGRE-499] Boost Thread-mt Linking problem on Mac 10.10 (yeosmite)

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#156]
<b>[reporter="wdavilaneto", created="Mon, 24 Aug 2015 06:52:11 +0200"]</b>

<p>Linking CXX shared library ../lib/macosx/Ogre.framework/Ogre<br/>
Undefined symbols for architecture x86_64:<br/>
  "std::_<em>1::</em><em>vector_base_common<true>::</em>_throw_length_error() const", referenced from:<br/>
      void std::_<em>1::vector<std::</em><em>1::pair<boost::condition_variable*, boost::mutex*>, std::</em><em>1::allocator<std::</em><em>1::pair<boost::condition_variable*, boost::mutex*> > >::</em><em>push_back_slow_path<std::</em><em>1::pair<boost::condition_variable*, boost::mutex*> const>(std::</em>_1::pair<boost::condition_variable*, boost::mutex*> const&) in libboost_thread-mt.a(thread.o)<br/>
      void std::_<em>1::vector<boost::shared_ptr<boost::detail::shared_state_base>, std::</em><em>1::allocator<boost::shared_ptr<boost::detail::shared_state_base> > >::</em>_push_back_slow_path<boost::shared_ptr<boost::detail::shared_state_base> const>(boost::shared_ptr<boost::detail::shared_state_base> const&) in libboost_thread-mt.a(thread.o)<br/>
  "std::runtime_error::runtime_error(char const*)", referenced from:<br/>
      boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) in libboost_thread-mt.a(thread.o)<br/>
      boost::condition_variable::do_wait_until(boost::unique_lock<boost::mutex>&, timespec const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::condition_variable::condition_variable() in libboost_thread-mt.a(thread.o)<br/>
      boost::mutex::mutex() in libboost_thread-mt.a(thread.o)<br/>
      boost::unique_lock<boost::mutex>::lock() in libboost_thread-mt.a(thread.o)<br/>
      boost::mutex::lock() in libboost_thread-mt.a(thread.o)<br/>
      boost::unique_lock<boost::mutex>::unlock() in libboost_thread-mt.a(thread.o)<br/>
      ...<br/>
  "std::runtime_error::runtime_error(std::runtime_error const&)", referenced from:<br/>
      void boost::throw_exception<boost::thread_resource_error>(boost::thread_resource_error const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> > boost::enable_current_exception<boost::exception_detail::error_info_injector<boost::thread_resource_error> >(boost::exception_detail::error_info_injector<boost::thread_resource_error> const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >::clone() const in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> > const&) in libboost_thread-mt.a(thread.o)<br/>
      void boost::throw_exception<boost::lock_error>(boost::lock_error const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> > boost::enable_current_exception<boost::exception_detail::error_info_injector<boost::lock_error> >(boost::exception_detail::error_info_injector<boost::lock_error> const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >::clone() const in libboost_thread-mt.a(thread.o)<br/>
      ...<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em><em>1::allocator<char> >::</em>_init(char const*, unsigned long)", referenced from:<br/>
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system-mt.a(error_code.o)<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em>_1::allocator<char> >::append(char const*)", referenced from:<br/>
      boost::system::system_error::what() const in libboost_thread-mt.a(thread.o)<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em>_1::allocator<char> >::append(char const*, unsigned long)", referenced from:<br/>
      boost::system::system_error::what() const in libboost_thread-mt.a(thread.o)<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em>_1::allocator<char> >::assign(char const*)", referenced from:<br/>
      boost::system::system_error::what() const in libboost_thread-mt.a(thread.o)<br/>
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in libboost_system-mt.a(error_code.o)<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em><em>1::allocator<char> >::basic_string(std::</em><em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em>_1::allocator<char> > const&)", referenced from:<br/>
      void boost::throw_exception<boost::thread_resource_error>(boost::thread_resource_error const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> > boost::enable_current_exception<boost::exception_detail::error_info_injector<boost::thread_resource_error> >(boost::exception_detail::error_info_injector<boost::thread_resource_error> const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >::clone() const in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >::clone_impl(boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> > const&) in libboost_thread-mt.a(thread.o)<br/>
      void boost::throw_exception<boost::lock_error>(boost::lock_error const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> > boost::enable_current_exception<boost::exception_detail::error_info_injector<boost::lock_error> >(boost::exception_detail::error_info_injector<boost::lock_error> const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >::clone() const in libboost_thread-mt.a(thread.o)<br/>
      ...<br/>
  "std::_<em>1::basic_string<char, std::</em><em>1::char_traits<char>, std::</em>_1::allocator<char> >::~basic_string()", referenced from:<br/>
      boost::system::system_error::what() const in libboost_thread-mt.a(thread.o)<br/>
      boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) in libboost_thread-mt.a(thread.o)<br/>
      boost::condition_variable::do_wait_until(boost::unique_lock<boost::mutex>&, timespec const&) in libboost_thread-mt.a(thread.o)<br/>
      boost::system::system_error::~system_error() in libboost_thread-mt.a(thread.o)<br/>
      boost::system::system_error::~system_error() in libboost_thread-mt.a(thread.o)<br/>
      boost::condition_variable::condition_variable() in libboost_thread-mt.a(thread.o)<br/>
      void boost::throw_exception<boost::thread_resource_error>(boost::thread_resource_error const&) in libboost_thread-mt.a(thread.o)<br/>
      ...<br/>
  "std::bad_alloc::bad_alloc()", referenced from:<br/>
      boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>() in libboost_thread-mt.a(thread.o)<br/>
ld: symbol(s) not found for architecture x86_64<br/>
clang: error: linker command failed with exit code 1 (use -v to see invocation)<br/>
make<span class="error">&#91;2&#93;</span>: *** <span class="error">&#91;lib/macosx/Ogre.framework/Versions/1.10.0/Ogre&#93;</span> Error 1<br/>
make<span class="error">&#91;1&#93;</span>: *** <span class="error">&#91;OgreMain/CMakeFiles/OgreMain.dir/all&#93;</span> Error 2<br/>
make: *** <span class="error">&#91;all&#93;</span> Error 2</p>

**Comment by bowang** [comment]
The source of your problem is due to the deviation of libc++ from libstdc++ (details can be found on http://libcxx.llvm.org)
Since OS X 10.9, Apple uses its own version of C++ library, i.e. libc++, with its clang compiler by default, rather than the standard libstdc++ from GNU.

However, in CMakeList.txt, the deployment target is set to 10.7, i.e.
```
  # 10.7 is the minimum for libc++ support
  set(CMAKE_OSX_DEPLOYMENT_TARGET 10.7)
```
The parameter CMAKE_OSX_DEPLOYMENT_TARGET is propagated into the compilation argument as '-mmacosx-version-min=10.7'

In OS X 10.7, the default C++ library was still libstdc++. Thus, clang attempts to link OGRE against libstdc++. Meanwhile, the boost library on your Mac OSX has been updated and is built with libc++, which you can confirm with otool as follow:
```
otool -L /usr/local/lib/libboost_system.dylib
```
Therefore, the linker cannot find the libc++ library required by boost.

Solution: in short, build OGRE targeting at your OS X version (i,e, 10.10) by correcting CMAKE_OSX_DEPLOYMENT_TARGET.
```
  set(CMAKE_OSX_DEPLOYMENT_TARGET 10.10)
```

**Comment by bowang** [comment]
The source of your problem is due to the deviation of libc++ from libstdc++ (details can be found on http://libcxx.llvm.org)
Since OS X 10.9, Apple uses its own version of C++ library, i.e. libc++, with its clang compiler by default, rather than the standard libstdc++ from GNU.

However, in CMakeList.txt, the deployment target is set to 10.7, i.e.
```
  # 10.7 is the minimum for libc++ support
  set(CMAKE_OSX_DEPLOYMENT_TARGET 10.7)
```
The parameter CMAKE_OSX_DEPLOYMENT_TARGET is propagated into the compilation argument as '-mmacosx-version-min=10.7'

In OS X 10.7, the default C++ library was still libstdc++. Thus, clang attempts to link OGRE against libstdc++. Meanwhile, the boost library on your Mac OSX has been updated and is built with libc++, which you can confirm with otool as follow:
```
otool -L /usr/local/lib/libboost_system.dylib
```
Therefore, the linker cannot find the libc++ library required by boost.

Solution: in short, build OGRE targeting at your OS X version (i,e, 10.10) by correcting CMAKE_OSX_DEPLOYMENT_TARGET.
```
  set(CMAKE_OSX_DEPLOYMENT_TARGET 10.10)
```

**Comment by paroj** [comment]
thanks for your explanation. However on the CI server this currently only triggers a warning - it seems that the newer Xcode/ CMake handles this correctly now. See:
https://travis-ci.org/OGRECave/ogre/jobs/102723959#L2086
