### ISSUE TITLE
Cmake: sdl2-config.cmake unsafe for cross-compilation

### ISSUE THREAD

**Issue by RomainNaour** [OGRECave/ogre#1568]
#### System Information
- Ogre Version: v1.12.6
- Operating System / Platform: Buildroot
- RenderSystem: OpenGL GLX

#### Detailled description
Since [1] replacing FindSDL2.cmake by sdl2-config.cmake, the SDL2 headers from the host and the target are mixed while cross-compiling. /usr/include/SDL2 is hardcoded in sdl2-config.cmake.

sdl2-config.cmake doesn't give the same result as sdl2-config while cross-compiling:
staging/usr/bin/sdl2-config --cflags
staging/usr/include/SDL2 ...

 sdl2-config.cmake
/usr/include/SDL2

This is an SDL2 upstream bug [2], but for now sdl2-config or pkg-config must be used.

[1] https://github.com/OGRECave/ogre/commit/6de6f9b4081a07c911932441700c54b72ec1ee1f
[2] https://bugzilla.libsdl.org/show_bug.cgi?id=4597

#### Ogre.log
None, Build issue.

**Comment by paroj** [comment]
as stated in [2] this is rather an issue with your host system. If you build SDL2 using cmake, a proper sdl2-config.cmake is generated that resolves the include path relative to itself.

As a workaround you can probably set `SDL2_DIR` to point to the target sdl2-config.cmake.
