### ISSUE TITLE
issue with qt5 and cmake

### ISSUE THREAD

**Issue by nevarim** [OGRECave/ogre#1569]
on cmake when i compile i have this error

CMake Warning at CMake/Dependencies.cmake:300 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:305 (include)

**Comment by paroj** [comment]
this is merely a warning, that you can safely ignore, if you do not need qt support
