### ISSUE TITLE
Proper use of OgreBites::ApplicationContextQt

### ISSUE THREAD

**Issue by Tectu** [OGRECave/ogre#1583]
I'd like to integrate OGRE into an existing Qt application. You can think of it as a simulation application that also needs a 3D viewer.

The plan is to use `OgreBites::ApplicationContextQt` and integrate the `QWindow` into the application as a `QWidget` by using `QWidget::windowHandle()`.

I created a minimal test example using Qt 5.13, cmake 3.15 and the latest OGRE master branch.

My `main_window` class:
```cpp
#pragma once

#include <QMainWindow>

class ogre_widget;

class main_window :
    public QMainWindow
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(main_window)

public:
    main_window()
    {
        m_ogre_widget = new ogre_widget;

        QWidget* central_widget = new QWidget;
        central_widget->setAttribute(Qt::WA_NativeWindow, true);
        m_ogre_widget->createWindow(central_widget->windowHandle());
        setCentralWidget(central_widget);

        m_ogre_widget->startTimer(std::chrono::milliseconds(10));
        m_ogre_widget->createDummyScene();
    }


    ~main_window() override = default;

private:
    ogre_widget* m_ogre_widget = nullptr;
};
```

My `ogre_widget` class:
```cpp
#pragma once

#include <QWindow>

#include <OgreApplicationContextQt.h>

class ogre_widget :
    public OgreBites::ApplicationContextQt
{
    Q_OBJECT
    Q_DISABLE_COPY_MOVE(ogre_widget)

public:
    // Construction
    ogre_widget() = default;
    ~ogre_widget() override = default;
};
```
However, the thing crashes immediately with a null address access violation exception.

I'd like to ask what the proper use of `OgreBites::ApplicationContextQt` is. The documentation is very minimal and I couldn't find any usage examples. I assume that I am either not using the proper calls (eg. `createWindow()` or that I am missing a crucial piece of setup here.

Specifically: Do I create a `QWidget` myself and then pass the corresponding `QWindow` pointer to `OgreBites::ApplicationContextQt::createWindow()` or do I let Ogre create the QWindow for me and somehow embedd that into a QWidget?
And what's the matter with `OgreBites::ApplicationContextQt::injectMainWindow()`? How/when should this be used?

Any help is appreciated.

**Comment by paroj** [comment]
ogre must create the first window itself, therefore you cannot use `createWindow` and that is what `injectMainWindow` is for.
Note that you can cast the `NativeWindowType` returned by `createWindow` to `QWidget`, so you can also override `createWindow` to interecept that.

You can take a look at Spacescape on how to integrate Ogre into a larger UI:
https://github.com/OGRECave/spacescape/blob/master/Spacescape/src/QtSpacescapeWidget.cpp

**Comment by Tectu** [comment]
Got it running based on the Spacescape code you linked. Thank you a lot for your help!

OGRE is an extremely well written piece of software. As an embedded developer for industrial systems I am always having a very daunting experience working with open source libraries for things like games and so on due to a massive lack of quality - not so with OGRE - it has been a great experience so far!
