### ISSUE TITLE
"Sinbad.mesh" in Boostrap.cpp has not found on 

### ISSUE THREAD

**Issue by nicolaspapp** [OGRECave/ogre#1591]
Hello Guys,
I have been trying your Project. Turns out I tried compiling the boostrap example and it throws an `Ogre::FileNotFoundException` exception. The error seems to come from this line: 

https://github.com/OGRECave/ogre/blob/40fb3406dad2f7f97fb3f32469e54a0c6dabffd9/Samples/Tutorials/Bootstrap.cpp#L67

I am pretty new to 3D engines, but it looks Sinbad.mesh is nowhere to be found. I tried with other mesh files from `../media/models ` and it seems to work ok.

It is pretty easy to fix, but it can be confusing if you are trying this for the first time.
Regards

**Comment by paroj** [comment]
in your `resources.cfg` should be a line like
```
Zip=../Media/packs/Sinbad.zip
```
referencing the mesh.

**Comment by nicolaspapp** [comment]
Ohhh I see now. Apparently there was something wrong with my IDE configuration  and OGRE was not finding the `resources.cfg` file that was being copied from `OGRE_CONFIG_DIR.` Now everything is up and running.

Thanks for the clarification!
