### ISSUE TITLE
Use newer SSE2NEON for more intrinsics with Aarch64 fastpath

### ISSUE THREAD

**Issue by jserv** [OGRECave/ogre#1625]
The current `ogre` repository contains a copy of SSE2NEON, which is quite old and non-maintained. [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon) is arguably the most active fork of existing SSE2NEON derived projects, providing more SSE intrinsics with ARM/ARM64 optimizations and bug-fixes. It would be great to migrate the latest [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon).

**Comment by paroj** [comment]
> contains a copy of SSE2NEON, which is quite old and non-maintained

this is not a problem at all, as long the implementation is correct, which I verified it to be.

> providing more SSE intrinsics with ARM/ARM64 optimizations

we only care about the intrinsics we currently use. A quick glance on the implementation showed that it is exactly the same as in our copy. So nothing to gain here either.
