### ISSUE TITLE
[OGRE-509] Android example for 1.10 or 2.0

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#163]
<b>[reporter="alexeyknyshev", created="Tue, 10 Nov 2015 20:26:21 +0100"]</b>

<p>There is no complete (or actual) howto about developing Ogre3d based Android application (not compiling ogre as static library for Android).</p>

**Comment by fntheirs** [comment]
Hi! I'm working with Qt and OGRE for Android platform. Is there an actual tutorial? I'm trying to make it work but I'm following Qt window + OGRE tutorial and I don't know how to load the resources from assets and some other things.

**Comment by paroj** [comment]
there is no tutorial for this as it not a very common usage scenario. You should be able to get it running using the AndroidJNI sample as a starting point: https://github.com/OGRECave/ogre/blob/cdbc6519b7d09c44c44232bf2de678ec82723abc/Samples/AndroidJNI/OgreActivityJNI.cpp

**Comment by ftheirs** [comment]
Thanks paroj! I'll try with your recomendation.
