### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#1641]
Archlinux ogre3d 1.12.28
#### Detailled description
commit 225320e0cc4b1bb49b21d8ecd88d987edd57b0b7

cmake --build . --clean-first --config release

[ 37%] Linking CXX static library ../lib/libOgreMainStatic.a
Error running link command: No such file or directory
make[2]: *** [OgreMain/CMakeFiles/OgreMain.dir/build.make:3250: lib/libOgreMainStatic.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:1434: OgreMain/CMakeFiles/OgreMain.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

*SDL2 is not being detected like it configuring it as for android maybe

**Comment by paroj** [comment]
the commit hash is invalid. master works on the CI: https://travis-ci.com/github/OGRECave/ogre/jobs/365098704
