### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#1646]
Archlinux ogre3d 1.12.28
Detailled description

commit 30a80186b8d6464c22e1d04936c1bd9ef6e26d9e

cmake -P ci-build.cmake 
cmake --build build

[ 67%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/imgui.cpp.o
[ 67%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/imgui_draw.cpp.o
[ 68%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/imgui_widgets.cpp.o
[ 68%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/imgui_demo.cpp.o
[ 68%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/misc/freetype/imgui_freetype.cpp.o
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.8/build/imgui-1.73/misc/freetype/imgui_freetype.cpp: In function ‘bool ImFontAtlasBuildWithFreeType(FT_Library, ImFontAtlas*, unsigned int)’:
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.8/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:334:72: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct ImFontBuildSrcDataFT’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  334 |     memset(src_tmp_array.Data, 0, (size_t)src_tmp_array.size_in_bytes());
      |                                                                        ^
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.8/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:295:8: note: ‘struct ImFontBuildSrcDataFT’ declared here
  295 | struct ImFontBuildSrcDataFT
      |        ^~~~~~~~~~~~~~~~~~~~
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.8/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:335:72: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct ImFontBuildDstDataFT’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  335 |     memset(dst_tmp_array.Data, 0, (size_t)dst_tmp_array.size_in_bytes());
      |                                                                        ^
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.8/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:308:8: note: ‘struct ImFontBuildDstDataFT’ declared here
  308 | struct ImFontBuildDstDataFT
      |        ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Components/Overlay/CMakeFiles/OgreOverlay.dir/build.make:343: Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/misc/freetype/imgui_freetype.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2377: Components/Overlay/CMakeFiles/OgreOverlay.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**Comment by paroj** [comment]
drop the -Werror flag - it does not work with recent compilers yet:
https://github.com/OGRECave/ogre/blob/30a80186b8d6464c22e1d04936c1bd9ef6e26d9e/ci-build.cmake#L2

**Comment by Joilnen** [comment]
After pulled and commented the line 2 and 84 from ci-build.cmake

commit 30a80186b8d6464c22e1d04936c1bd9ef6e26d9e

cmake -P ci-build.cmake
cmake --build build

[ 65%] Linking CXX shared library ../../lib/libOgreTerrain.so
[ 65%] Built target OgreTerrain
Scanning dependencies of target Plugin_DotScene
[ 65%] Building CXX object PlugIns/DotScene/CMakeFiles/Plugin_DotScene.dir/src/DotSceneLoader.cpp.o
[ 65%] Linking CXX shared library ../../lib/Plugin_DotScene.so
[ 65%] Built target Plugin_DotScene
[ 65%] Building CXX object Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/misc/freetype/imgui_freetype.cpp.o
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/build/imgui-1.73/misc/freetype/imgui_freetype.cpp: In function ‘bool ImFontAtlasBuildWithFreeType(FT_Library, ImFontAtlas*, unsigned int)’:
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:334:72: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct ImFontBuildSrcDataFT’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  334 |     memset(src_tmp_array.Data, 0, (size_t)src_tmp_array.size_in_bytes());
      |                                                                        ^
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:295:8: note: ‘struct ImFontBuildSrcDataFT’ declared here
  295 | struct ImFontBuildSrcDataFT
      |        ^~~~~~~~~~~~~~~~~~~~
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:335:72: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct ImFontBuildDstDataFT’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  335 |     memset(dst_tmp_array.Data, 0, (size_t)dst_tmp_array.size_in_bytes());
      |                                                                        ^
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/build/imgui-1.73/misc/freetype/imgui_freetype.cpp:308:8: note: ‘struct ImFontBuildDstDataFT’ declared here
  308 | struct ImFontBuildDstDataFT
      |        ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Components/Overlay/CMakeFiles/OgreOverlay.dir/build.make:343: Components/Overlay/CMakeFiles/OgreOverlay.dir/__/__/imgui-1.73/misc/freetype/imgui_freetype.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2377: Components/Overlay/CMakeFiles/OgreOverlay.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**Comment by paroj** [comment]
rm -rf build

**Comment by Joilnen** [comment]
Cool compiled SampleBrowser seems ok, but next I clicked ESC to back from "Dear ImGui" example 

[ 98%] Building CXX object Components/Terrain/CMakeFiles/OgreTerrain.dir/src/OgreTerrainMaterialShaderHelperCg.cpp.o
[ 99%] Building CXX object Components/Terrain/CMakeFiles/OgreTerrain.dir/src/OgreTerrainMaterialShaderHelperGLSL.cpp.o
[ 99%] Building CXX object Components/Terrain/CMakeFiles/OgreTerrain.dir/src/OgreTerrainQuadTreeNode.cpp.o
[ 99%] Building CXX object Components/Terrain/CMakeFiles/OgreTerrain.dir/src/OgreTerrainPaging.cpp.o
[ 99%] Building CXX object Components/Terrain/CMakeFiles/OgreTerrain.dir/src/OgreTerrainPagedWorldSection.cpp.o
[100%] Linking CXX static library ../../lib/libOgreTerrainStatic.a
[100%] Built target OgreTerrain
Scanning dependencies of target Plugin_DotScene
[100%] Building CXX object PlugIns/DotScene/CMakeFiles/Plugin_DotScene.dir/src/DotSceneLoader.cpp.o
/home/joilnen/ogre3d_devel/my/ogre3d-1.12.x/PlugIns/DotScene/src/DotSceneLoader.cpp:11:10: fatal error: 'pugixml.hpp' file not found
#include <pugixml.hpp>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [PlugIns/DotScene/CMakeFiles/Plugin_DotScene.dir/build.make:83: PlugIns/DotScene/CMakeFiles/Plugin_DotScene.dir/src/DotSceneLoader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:717: PlugIns/DotScene/CMakeFiles/Plugin_DotScene.dir/all] Error 2
make: *** [Makefile:172: all] Error 2

**Comment by paroj** [comment]
original issue fixed.

**Comment by paroj** [comment]
imgui issue should be fixed by #1650
