### ISSUE TITLE
Make SWIG support ImGUI

### ISSUE THREAD

**Issue by cookgreen** [OGRECave/ogre#1659]
currently there is not imgui overlay included in the swig output

**Comment by paroj** [comment]
it should be. Maybe you compiled Ogre without imgui support?

**Comment by cookgreen** [comment]
> it should be. Maybe you compiled Ogre without imgui support?

Yeah, I have compiled the Ogre 1.12.8 without imgui support

Currently I hope can add imgui support

**Comment by paroj** [comment]
you will have to wait for the linked PR, as I noted that imgui is currently only enabled for Python

**Comment by cookgreen** [comment]
> you will have to wait for the linked PR, as I noted that imgui is currently only enabled for Python

Please enable for C# as soon as possible

and enable terrain for C#
