### ISSUE TITLE
Make SWIG support Terrain

### ISSUE THREAD

**Issue by cookgreen** [OGRECave/ogre#1662]
currently there is no terrain support in swig for C#

**Comment by paroj** [comment]
the Terrain Component has not yet been wrapped for SWIG. You can take a look at the RTSS, for the required interface file: https://github.com/OGRECave/ogre/blob/master/Components/RTShaderSystem/include/OgreRTShader.i

once you create one, you have to reference it like this: https://github.com/OGRECave/ogre/blob/00528852f2ebfba1a2711e45a831215b917d2db0/Components/Csharp/CMakeLists.txt#L30

if you get it working, please create a pull request

**Comment by cookgreen** [comment]
fine

**Comment by paroj** [comment]
@mgangwisch is currently taking a look at this

**Comment by paroj** [comment]
@mgangwisch allegedly finished the wrapping, but did not contribute it back.

**Comment by mgangwisch** [comment]
no; its not finished yet.

**Comment by paroj** [comment]
feel free to open a "Draft" PR, if you need any input on what you got so far.

**Comment by natan-fernandes** [comment]
Are you still working on this, @mgangwisch ?
