### ISSUE TITLE
TextAreaOverlayElement.setCaption paramter type is SWIGTYPE_p_UTFString

### ISSUE THREAD

**Issue by cookgreen** [OGRECave/ogre#1663]
TextAreaOverlayElement's setCaption method parameter type is SWIGTYPE_p_UTFString

and SWIGTYPE_p_UTFString can't be new since it is a class which is unaccessable

**Comment by paroj** [comment]
as a workaround, you can use
```
text.setParameter("caption", "something")
```

**Comment by cookgreen** [comment]
> as a workaround, you can use
> 
> ```
> text.setParameter("caption", "something")
> ```

Hmm, I think there still need a `Text` or `Caption` property just like Mogre
