### ISSUE TITLE
Ogre-1.12.9 fails to build with GLES2 CG support

### ISSUE THREAD

**Issue by Yamakuzure** [OGRECave/ogre#1712]
#### System Information
- Ogre Version: 1.12.9
- Operating System / Platform: Gentoo Linux
- RenderSystem: GLES2

#### Detailled description
I have all relevant system libraries installed with GLES2 support and also have both hlsl2glslfork and glsl-optimizer installed.

gcc-9.3.0
glibc-2.32
mesa-20.1.7
nvidia-cg-toolkit-3.1.0013

#### Ogre.log
This is the snippet from the build log:
````
FAILED: RenderSystems/GLES2/CMakeFiles/RenderSystem_GLES2.dir/src/GLSLES/src/OgreGLSLESCgProgramFactory.cpp.o 
(...)
In file included from ogre-1.12.9/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESCgProgramFactory.cpp:29:
ogre-1.12.9/RenderSystems/GLES2/src/GLSLES/include/OgreGLSLESCgProgramFactory.h:48:30: error: invalid covariant return
    type for ‘virtual Ogre::HighLevelGpuProgram* Ogre::GLSLESCgProgramFactory::create(Ogre::ResourceManager*,
    const String&, Ogre::ResourceHandle, const String&, bool, Ogre::ManualResourceLoader*)’
   48 |         HighLevelGpuProgram* create(ResourceManager* creator, const String& name, ResourceHandle handle,
                                            const String& group, bool isManual, ManualResourceLoader* loader);
      |                              ^~~~~~
In file included from ogre-1.12.9/RenderSystems/GLES2/src/GLSLES/include/OgreGLSLESCgProgramFactory.h:33,
                 from ogre-1.12.9/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESCgProgramFactory.cpp:29:
ogre-1.12.9/OgreMain/include/OgreHighLevelGpuProgramManager.h:53:29: note: overridden function is
    ‘virtual Ogre::GpuProgram* Ogre::HighLevelGpuProgramFactory::create(Ogre::ResourceManager*, const String&,
        Ogre::ResourceHandle, const String&, bool, Ogre::ManualResourceLoader*)’
   53 |         virtual GpuProgram* create(ResourceManager* creator,
      |                             ^~~~~~
````

Currently I have configured OGRE with these flags, maybe the selections are the culprit?

````
-DOGRE_BUILD_PLUGIN_CG=yes
(...)
-DOGRE_BUILD_RENDERSYSTEM_GL=yes
-DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=yes
-DOGRE_BUILD_RENDERSYSTEM_GLES2=yes
(...)
-DOGRE_CONFIG_ENABLE_GL_STATE_CACHE_SUPPORT=yes
-DOGRE_CONFIG_ENABLE_GLES2_CG_SUPPORT=yes
-DOGRE_CONFIG_ENABLE_GLES3_SUPPORT=yes
````

If I switch this to

````
-DOGRE_CONFIG_ENABLE_GLES2_CG_SUPPORT=no
````

the build succeeds and everything is built and installed just fine.

**Comment by paroj** [comment]
even if compilation would succeed, that would not give you much. hlsl2glsl does not produce valid ESSL code and fixing that is not reasonable nowadays.
The currently recommended alternative would be:
https://www.ogre3d.org/2020/07/26/ogre-ecosystem-roundup-6#OgreUnifiedShader_as_a_Cg_replacement

**Comment by Yamakuzure** [comment]
> even if compilation would succeed, that would not give you much. hlsl2glsl does not produce valid ESSL code and fixing that is not reasonable nowadays.
> The currently recommended alternative would be:
> https://www.ogre3d.org/2020/07/26/ogre-ecosystem-roundup-6#OgreUnifiedShader_as_a_Cg_replacement

I'll check that out, thanks!

Well, I can totally live without GLES2_CG_SUPPORT, Almost all Samples work perfectly well with the GLES Render System, and the ones which do not, complain the same about shaders as with the regular OpenGL Render System. So I am good.
Thank you vey much!

**Comment by Yamakuzure** [comment]
Just out of curiosity, as both glsl-optimizer and hlsl2glsl are discontinued, will Ogre move to an alternative in the foreseeable future?

**Comment by paroj** [comment]
actual both of these can be replaced with a SPIR-V based tooling (glslang + SPIRV-cross). We dont have much support in Ogre for that, but thats where we should be heading.
There is also HLSLParser, which is more of a hlsl2glsl replacement, but that does not give us much over the UnifiedShader macros.
