### ISSUE TITLE
Ogre-1.12.9: SampleBrowser cancels with an assertion failure

### ISSUE THREAD

**Issue by Yamakuzure** [OGRECave/ogre#1713]
#### System Information
- Ogre Version: 1.12.9
- Operating System / Platform: Gentoo Linux 
- RenderSystem: unspecified

#### Detailled description
With ogre-1.12.8 installed in the same way, everything worked quite fine.

But when I install ogre-1.12.9 and try to start the SampleBrowser (Ogre cache got deleted) it breaks off with:

````
*-*-* OGRE Initialising
*-*-* Version 1.12.9 (Rhagorthua)
OverlayElementFactory for type Panel registered.
OverlayElementFactory for type BorderPanel registered.
OverlayElementFactory for type TextArea registered.
Registering ResourceManager for type Font
SampleBrowser: ogre-1.12.9/OgreMain/src/OgrePixelFormat.cpp:691: static void Ogre::PixelUtil::bulkPixelConversion(const Ogre::PixelBox&, const Ogre::PixelBox&): Assertion `src.getWidth() == dst.getWidth() && src.getHeight() == dst.getHeight() && src.getDepth() == dst.getDepth()' failed.
````
I have rebuilt with added output of what src and dst look like, and the result is:
````
src W/H/D: 500/340/1
dst W/H/D: 500/380/1
````
Well, the new background image really has only 340 pixels height.

The following patch fixed the issue for me:
````
--- a/Components/Bites/src/OgreGLXConfigDialog.cpp	2020-09-21 15:17:33.783741691 +0200
+++ b/Components/Bites/src/OgreGLXConfigDialog.cpp	2020-09-21 15:17:35.948741768 +0200
@@ -74,7 +74,7 @@
 class GLXConfigurator {
     /* GUI constants */
     static const int wWidth = 500;      // Width of window
-    static const int wHeight = 380;     // Height of window
+    static const int wHeight = 340;     // Height of window
     static const int col1x = 20;        // Starting x of column 1 (labels)
     static const int col2x = 230;       // Starting x of column 2 (options)
     static const int col1w = 200;       // Width of column 1 (labels)
````
*But*: The Window height is now so small, that the sRGB Gamma Conversion setting of the OpenGL 3+ Renderer is drawn over the cancel/accept buttons. Maybe better lengthen the background image?

**Comment by paroj** [comment]
the proper fix is to use a smaller pixelbox for conversion. see above.

**Comment by Yamakuzure** [comment]
> the proper fix is to use a smaller pixelbox for conversion. see above.

Well, basically you do the same and reduce dst.bottom. But after memory has been handled.
Is it wise to do this after memset() when, with that assignment, dst.bottom could have been raised instead? And if it was, wouldn't that lead to a stack smashing overflow? 
If the PNG is larger than anticipated, the initial pixelbox is too small. Manually raising it can be a problem.

To clarify:
````
    347         data = (unsigned char*)malloc(mWidth * mHeight * bpl); // Must be allocated with malloc
    348         PixelBox dst(mWidth, mHeight, 1, bpl == 2 ? PF_B5G6R5 : PF_A8R8G8B8, data);
    349 
    350         memset(data, 0, dst.getConsecutiveSize());
    351         dst.bottom = src.bottom;
    352         PixelUtil::bulkPixelConversion(src, dst);
````
347: data is allocated with pre-defined values
348: dst is created with tus pre-defined size
350: data is nullified
351: dst.mHeight is changed, effectively changing the size of `data` needed
352: src is to be copied into dst which might be too small

This *only* applies, of course, if src.bottom is larger than mHeight. Currently this is perfectly safe. But to be safe if any future changes introduce a larger PNG, `data` and `dst` should be created on the values of `src` and not something pre-defined which might be off.

This is totally theoretical, of course, unless the case where a larger PNG that is higher than mHeight really is introduced, which might never happen. I just felt this should be mentioned.

**Comment by paroj** [comment]
yes, I should have std::min that for proper box intersection. On the other hand it is the first time we change that png in 14 years..
