### ISSUE TITLE
OgreMesh - Bounding Sphere is nonoptimal when geometry is not centered

### ISSUE THREAD

**Issue by akacoding** [OGRECave/ogre#1726]
When using the bounding sphere I made the following observation.
Consider a geometry with some extent not centered around it's bounding box center.
The bounding sphere is now calculated in way that the local geometry coordinate system zero is the sphere center. That leads to a bigger sphere than actual needed to enclose the whole geometry.
I made a little figure of what I'am talking about.

![OgreBoundingSphere](https://user-images.githubusercontent.com/71983705/94849026-18204080-0425-11eb-939d-1e601e7e6d08.png)

If you look into the code it's obvious. The `OgreMesh` class does have a method to set the bounding sphere radius, but it's always referenced to the local zero of the geometry.
That also leads to a bigger world bounding sphere which is used for culling if I see it right, etc.
You get this behaviour too when you use `_setBounds` or `_updateBoundsFromVertexBuffer`.

I think the OP of this thread had the same problem: https://forums.ogre3d.org/viewtopic.php?t=8966. Because I made the same observation which lead to this founding.

My proposal to fix this is to set a sphere like the AABB. The AABB consists of a min and max point referenced to the geometry zero.
Instead of storing just the radius you can store a local sphere with a center referenced to the local zero and a radius.
That would lead to a optimal bounding sphere.

I hope it was understandable and right indeed.
Really appreciate your time.

**Comment by paroj** [comment]
yeah, we even got two different radius calculation methods because of that:
https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_math.html#a6beb574317f8085bab69587ef7dc72ed

I am all for computing a tight bounding sphere, but we need to go through all usages of `getBounding.*Radius` and make sure that the computations still work out with a different sphere origin.

Besides getting the math right, this would also break user code that is written against current behavior. Therefore we can do that 1.13 earliest. But the code changes can be prepared earlier in a separate PR/ branch.

**Comment by paroj** [comment]
[getBoundingRadius](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_movable_object.html#aed6d3f3856d030a967eb17d78a598807) is currently specified to be origin centered

**Comment by paroj** [comment]
there are several computations that go like
```cpp
Real rad = getBoundingRadius();
Real squaredDepth = mParentNode->getSquaredViewDepth(cam->getLodCamera());
Real maxDist = mUpperDistance + rad;
if (squaredDepth > Math::Sqr(maxDist))
```
these would have to take the shifted origin into account, which would slow them down.
Typically the bounding sphere is used for a coarse approximation.

**Comment by akacoding** [comment]
> [getBoundingRadius](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_movable_object.html#aed6d3f3856d030a967eb17d78a598807) is currently specified to be origin centered

Yes I've read that already. I opened this issue because I thought that it would be an improvement to use the origin that would lead to the smallest sphere. I also thought that the culling would take advantage of it because I saw that the AABB and the bounding sphere is used in that process.


> there are several computations that go like
> 
> ```c++
> Real rad = getBoundingRadius();
> Real squaredDepth = mParentNode->getSquaredViewDepth(cam->getLodCamera());
> Real maxDist = mUpperDistance + rad;
> if (squaredDepth > Math::Sqr(maxDist))
> ```
> 
> these would have to take the shifted origin into account, which would slow them down.
> Typically the bounding sphere is used for a coarse approximation.

Yes, I see. This would result into not being an improvement.
It would be a solution to save two sphere's. One origin centered and one bounding box centered sphere. But that would be a little bit messy and not really an improvement.

Seems like it's better to reject this issue, if there no better solution.

**Comment by paroj** [comment]
one could use "tight" bounding boxes for `getWorldBoundingSphere`, as this one is cached.  However, having different radii and interpretations inside the codebase will probably do more harm than good.
