### ISSUE TITLE
Build error by MCST lcc compiler + CMake 3.15 (on e2k architecture) when using OGRE_ENABLE_PRECOMPILED_HEADERS=TRUE option

### ISSUE THREAD

**Issue by r-a-sattarov** [OGRECave/ogre#1731]
#### System Information
- Ogre Version: 1.12.10 git-cf9fb1c1d (from Sep 29, 2020)
- Operating System / Platform: Linux 4.19 / e2k (MCST Elbrus 2000)
- RenderSystem: OpenGL

#### Detailled description
I have a build error with MCST lcc compiler + CMake 3.15 (when using OGRE_ENABLE_PRECOMPILED_HEADERS=TRUE option).
This error is caused by an empty argument for -isystem option.

#### Compilation log
[  1%] Generating OgreStableHeaders.h.gch/OgreMain_Release.gch
cd /root/dev/sattarov/ogre/build/OgreMain && /usr/bin/cmake -E make_directory /root/dev/sattarov/ogre/build/OgreMain/OgreStableHeaders.h.gch
cd /root/dev/sattarov/ogre/build/OgreMain && /usr/bin/c++ -O3 -DNDEBUG -fPIC -std=c++11 -DOgreMain_EXPORTS -isystem "/root/dev/sattarov/ogre/OgreMain/include/Threading" -isystem "/root/dev/sattarov/ogre/OgreMain/src" -isystem "/root/dev/sattarov/ogre/build/Dependencies/include" -isystem "/root/dev/sattarov/ogre/OgreMain/include/Threading" -isystem "/root/dev/sattarov/ogre/OgreMain/src" -isystem "/root/dev/sattarov/ogre/build/Dependencies/include" -isystem "/root/dev/sattarov/ogre/OgreMain/include" -isystem "/root/dev/sattarov/ogre/build/include" **-isystem ""** -isystem "/root/dev/sattarov/ogre/OgreMain/" -Wall -Winit-self -Wcast-qual -Wwrite-strings -Wextra -Wundef -Wmissing-declarations -Wno-unused-parameter -Wshadow -Wno-missing-field-initializers -Wno-long-long -msse -fPIC -x c++-header -c -o /root/dev/sattarov/ogre/build/OgreMain/OgreStableHeaders.h.gch/OgreMain_Release.gch /root/dev/sattarov/ogre/build/OgreMain/OgreStableHeaders.h
**lcc: error: no argument provided for the "-isystem" option**

**When using CMake version 3.16 and above, I have no such build error (in CMake 3.16 was added the PRECOMPILE_HEADERS target property - https://cmake.org/cmake/help/v3.16/prop_tgt/PRECOMPILE_HEADERS.html).**

#### P.S. 
E2K - this is VLIW/EPIC architecture, like Intel Itanium architecture.
- https://en.wikipedia.org/wiki/Elbrus_2000

**Comment by paroj** [comment]
use CMake 3.16 then..
