### ISSUE TITLE
Scene is lost when resizing window

### ISSUE THREAD

**Issue by IvanMaticad** [OGRECave/ogre#1744]
Good morning,
I made a simple app as described http://wiki.ogre3d.org/Simple+Win32+Program
With version 1.12.9 when I resize the window the scene disappears.
With version 1.12.8 the program works fine.
Ivan

**Comment by paroj** [comment]
```cpp
RenderSystem::setConfigOption("Multi device memory hint", "Auto hardware buffers management")
```

**Comment by IvanMaticad** [comment]
Thanks, now it works
Ivan
