### ISSUE TITLE
Tutorial is pointing to a non-existing file

### ISSUE THREAD

**Issue by jlHertel** [OGRECave/ogre#1817]
#### System Information
- Ogre Version: 1.12.10
- Operating System / Platform: Linux / Manjaro 
- RenderSystem: OpenGL

#### Detailled description
I'm following the tutorials but on tutorial 3 - [Terrain, Sky and Fog][1] there is a reference for `Samples/Terrain/include/Terrain.h` but I'm unable to find this source file. See the [relevant folder in Github][2].

[1]: https://ogrecave.github.io/ogre/api/latest/tut__terrain_sky_fog.html
[2]: https://github.com/OGRECave/ogre/tree/v1.12.10/Samples

**Comment by paroj** [comment]
https://github.com/OGRECave/ogre/blob/v1.12.10/Samples/Simple/include/Terrain.h

**Comment by jlHertel** [comment]
@paroj Thanks for pointing out. Can this be updated in the tutorial doc too?
