### ISSUE TITLE
overlay fails to build during swig on debian

### ISSUE THREAD

**Issue by simonschmeisser** [OGRECave/ogre#1822]
Hi Pavel,

I'm trying to update the debian packages once more but it fails to build:
https://salsa.debian.org/games-team/ogre/-/jobs/1290043/raw
(search for "error:")
the relevant error is:
```
/builds/games-team/ogre/debian/output/source_dir/obj-x86_64-linux-gnu/Components/Python/CMakeFiles/_Overlay.dir/OgreOverlayPYTHON_wrap.cxx: In function 'PyObject* _wrap_ImGuiIO_RenderDrawListsFnUnused_set(PyObject*, PyObject*)':
/builds/games-team/ogre/debian/output/source_dir/obj-x86_64-linux-gnu/Components/Python/CMakeFiles/_Overlay.dir/OgreOverlayPYTHON_wrap.cxx:92131:21: error: 'struct ImGuiIO' has no member named 'RenderDrawListsFnUnused'; did you mean 'RenderDrawListsFn'?
92131 |   if (arg1) (arg1)->RenderDrawListsFnUnused = arg2;
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                     RenderDrawListsFn
/builds/games-team/ogre/debian/output/source_dir/obj-x86_64-linux-gnu/Components/Python/CMakeFiles/_Overlay.dir/OgreOverlayPYTHON_wrap.cxx: In function 'PyObject* _wrap_ImGuiIO_RenderDrawListsFnUnused_get(PyObject*, PyObject*)':
/builds/games-team/ogre/debian/output/source_dir/obj-x86_64-linux-gnu/Components/Python/CMakeFiles/_Overlay.dir/OgreOverlayPYTHON_wrap.cxx:92153:30: error: 'struct ImGuiIO' has no member named 'RenderDrawListsFnUnused'; did you mean 'RenderDrawListsFn'?
92153 |   result = (void *) ((arg1)->RenderDrawListsFnUnused);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
      |                              RenderDrawListsFn

```
The relevant branch is https://salsa.debian.org/games-team/ogre/-/commits/ogre-1.12.9-updates
please note that we try to use a packaged version of imgui, so there are some small changes to the CMakeLists.txt in this patch:
https://salsa.debian.org/games-team/ogre/-/blob/ogre-1.12.9-updates/debian/patches/use-system-imgui.diff

Any idea? Thanks!

**Comment by paroj** [comment]
yeah, its this: https://github.com/ocornut/imgui/issues/3403#issuecomment-672934624

see https://github.com/OGRECave/ogre/blob/7d2aa8a4e7e03cc5a61080849439fa17076d055a/Components/Python/CMakeLists.txt#L22

I would suggest porting to the system imgui package independently of upgrading ogre (which is now at 1.12.10 BTW).

However, note that you should be very cautious about using the system imgui, as this effectively means that you have the code in one package and the Python bindings for that code in an rather unrelated one (ogre).
Therefore each imgui upgrade **must** trigger an ogre rebuild (also for compile flag changes) as it might affect the API & ABI. (like at hand)

**Comment by simonschmeisser** [comment]
> yeah, its this: [ocornut/imgui#3403 (comment)](https://github.com/ocornut/imgui/issues/3403#issuecomment-672934624)
> 
> see
> 
> https://github.com/OGRECave/ogre/blob/7d2aa8a4e7e03cc5a61080849439fa17076d055a/Components/Python/CMakeLists.txt#L22
> 
thanks, that fixed it indeed. Ideally the pkgconfig file from the imgui package would provide those flags but right now I just copied them

> I would suggest porting to the system imgui package independently of upgrading ogre (which is now at 1.12.10 BTW).
>
It now succeeds so I'll ask for this to be uploaded and then do 1.12.10
 
> However, note that you should be very cautious about using the system imgui, as this effectively means that you have the code in one package and the Python bindings for that code in an rather unrelated one (ogre).
> Therefore each imgui upgrade **must** trigger an ogre rebuild (also for compile flag changes) as it might affect the API & ABI. (like at hand)

I think/hope it's not as bad as you paint it since imgui is used as a static library here. (Which of course also limits the benefits of splitting it out in the first place ...)

**Comment by paroj** [comment]
yes, including imgui as a static lib alleviates the problem.

while you are at it, might I bring this package issue to your attention: https://forums.ogre3d.org/viewtopic.php?f=2&t=96117

you might want to cherry-pick these two commits:
- https://github.com/OGRECave/ogre/commit/19cade5cd8d1447bee61905b5b3a1cd81ea67b0e
- https://github.com/OGRECave/ogre/commit/7624a5692348257b9d9345fc78184335456fc239

you can verify this, by running cmake inside:
https://github.com/OGRECave/ogre/tree/master/Samples/Tutorials

**Comment by simonschmeisser** [comment]
you could also make a 1.12.11 release with those fixes and I can try to include that tutorial as a package test

I've had a hard time getting a package with even bigger issues fixed in Ubuntu LTS so I'm not sure I'll be able to help that guy but of course it should be fixed in Debian before the next release (and will then end up automatically in future Ubuntu releases)

**Comment by simonschmeisser** [comment]
Let's hope stuff now works: https://salsa.debian.org/games-team/ogre/-/commits/ogre-1.12.10-updates

**Comment by paroj** [comment]
there seems to be another issue with the debian package: SDL2 is apparently not picked up (at least in 1.12.4):
https://forums.ogre3d.org/viewtopic.php?p=549964#p549964

would you check that? Also, where are the issues for ogre in debian tracked? So we dont have to abuse this issue any more..

**Comment by simonschmeisser** [comment]
https://www.debian.org/Bugs/Reporting or https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=ogre-1.12

I'm not sure if Ubuntu bugs are propagated there in any way

```
[ 99%] Building CXX object Components/Bites/CMakeFiles/OgreBites.dir/src/OgreApplicationContextSDL.cpp.o
```
So the current packages don't have that issue. Unfortunately my request to import 1.12.5 back then was not reacted upon so Ubuntu has a very early stage of my packaging attempts. 20.10 includes 1.12.5 which should have this fixed already.

(for 1.12.4 salsa ci (the ci on that gitlab instance) was not yet activated, that's why there's no build log)
