### ISSUE TITLE
Missing license in Samples/Tutorial/0_bootstrap.cpp

### ISSUE THREAD

**Issue by simonschmeisser** [OGRECave/ogre#1824]
I wanted to use the Samples/Tutorial/ folder as a testcase for CMake in Debian packaging but it has no license header

you could use
```
// SPDX-License-Identifier: MIT
```
see https://spdx.dev/ids/

**Comment by paroj** [comment]
fixed by bd9182d9e4a8167e9c26b7804be21ac0173c2dbd
