### ISSUE TITLE
`Node::rotate(axis, angle)` cannot be reversed exactly

### ISSUE THREAD

**Issue by swebb2066** [OGRECave/ogre#1853]
Because`Quaternion::FromAxisAndAngle` does not normalise the resulting Quaternion, repeated calls to `pitch` and `yaw` generate some unwanted rotation in the third axis.

I believe `Node::rotate(axis, angle)` needs to be changed to include `q.normalise()`
```
    void Node::rotate(const Vector3& axis, const Radian& angle, TransformSpace relativeTo)
    {
        Quaternion q;
        q.FromAngleAxis(angle,axis);
        q.normalise()
        rotate(q, relativeTo);
    }
```

**Comment by paroj** [comment]
inside `Quaternion::FromAxisAndAngle` there is a comment about axis being required to be unit length. Is this the case for you? Maybe we should just need to improve documentation here.

Maybe you can provide some minimal code that demonstrates the case to help me understand the issue better.

**Comment by swebb2066** [comment]
I was only using Node::rotate as a side effect of using `pitch` and `yaw` (which always use a unit axis) in a mouse move event.

When I switched from Ogre::Camera in Ogre 1.9 to a camera attached to a Ogre::SceneNode in Ogre 1.12.9, the view orientation drifts slowly over many calls to `pitch` and `yaw`.

I have had to work around the problem using the following code in my `OgreWidget::mouseMoveEvent(QMouseEvent* ev)` function:
```
<snip/>
                Ogre::Degree yawAngle(-relPos.x() * 0.25f);
                Ogre::Degree pitchAngle(-relPos.y() * 0.25f);
#ifdef OGRE_ROTATE_BY_ANGLE_USES_NORMALIZED_QUATERNIONS
                m_cameraPosition->yaw(yawAngle, Ogre::Node::TS_PARENT);
                m_cameraPosition->pitch(pitchAngle, Ogre::Node::TS_PARENT);
#else
                Ogre::Quaternion yawRot;
                yawRot.FromAngleAxis(yawAngle, Ogre::Vector3::UNIT_Y);
                yawRot.normalise();
                m_cameraPosition->rotate(yawRot, Ogre::Node::TS_PARENT);
                Ogre::Quaternion pitchRot;
                pitchRot.FromAngleAxis(pitchAngle, m_cameraPosition->getOrientation() * Ogre::Vector3::UNIT_X);
                pitchRot.normalise();
                m_cameraPosition->rotate(pitchRot, Ogre::Node::TS_PARENT);
#endif
```

**Comment by paroj** [comment]
> I have had to work around the problem using the following code in my OgreWidget::mouseMoveEvent(QMouseEvent* ev) function:

and this does solve the problem?

**Comment by swebb2066** [comment]
Yes

On Jan 17, 2021 11:00 AM, Pavel Rojtberg <notifications@github.com> wrote:

I have had to work around the problem using the following code in my OgreWidget::mouseMoveEvent(QMouseEvent* ev) function:

and this does solve the problem?

**Comment by paroj** [comment]
just took a closer look at your code and noticed that you do
```cpp
m_cameraPosition->getOrientation() * Ogre::Vector3::UNIT_X
```
in your #else block, which does not happen in the #if block. Are you sure, you are not merely missing a call to `SceneNode::setFixedYawAxis`?

**Comment by swebb2066** [comment]
I do not get the correct (Ogre::Camera 1.9) behaviour without the `m_cameraPosition->getOrientation() * Ogre::Vector3::UNIT_X`.

I do call `SceneNode::setFixedYawAxis` on `m_cameraPosition` immediately after creation:
```
   m_cameraPosition = m_sceneManager->getRootSceneNode()->createChildSceneNode("CameraPosition");\
   m_cameraPosition->setFixedYawAxis(true, Ogre::Vector3::UNIT_Y);
```

The `m_cameraPosition->getOrientation() * Ogre::Vector3::UNIT_X` is undoing the code in `Node::rotate(const Quaternion& q, TransformSpace relativeTo)` 
```
        case TS_PARENT:
            // Rotations are normally relative to local axes, transform up
            mOrientation = q * mOrientation;
            break;
```
So maybe that is the problem instead of an unnormalised quaternion.

**Comment by paroj** [comment]
can you drop the `.normalise();` calls in your code to confirm, that they actually are not part of the problem?

**Comment by swebb2066** [comment]
Yes, I did that and can see that a missing normalise is not the problem.

**Comment by paroj** [comment]
try:
```cpp
                m_cameraPosition->yaw(yawAngle, Ogre::Node::TS_PARENT);
                m_cameraPosition->pitch(pitchAngle, --> Ogre::Node::TS_LOCAL <--);
```
instead of your code

**Comment by swebb2066** [comment]
Yes, that seems to do the same as my work-around code.
