### ISSUE TITLE
OverlayElement setMaterial and setMaterialName affect the passed material

### ISSUE THREAD

**Issue by akacoding** [OGRECave/ogre#1864]
The signature of the setMaterial method of OverlayElement suggests that it does not affect the passed material as it's a reference to a const MaterialPtr, but it actually does, [see setMaterial in OgreOverlayElement.cpp](https://github.com/OGRECave/ogre/blob/2c16eda34d64f593eb88f412996bfb60bf7838d0/Components/Overlay/src/OgreOverlayElement.cpp#L333).

The method documentation states this behaviour, [see OgreOverlayElement.h](https://github.com/OGRECave/ogre/blob/master/Components/Overlay/include/OgreOverlayElement.h#L266).

But I think the current behaviour is very error prone by changing a given material that may shared with other entities.
Wouldn't it be better to throw an exception if the material doesn't meet the actual requirement.

**Comment by paroj** [comment]
`const MaterialPtr` actually means `Material* const` and not `const Material*` - but that aside, I think this is a question of convenience vs. consistency.

Generally, I agree that it is unexpected that method to changes the material, as no other setMaterial behaves that way.
But for backwards-compatibility reasons we cannot simply drop this behavior.

Instead I suggest to add a warning if we are about to change the material, and keep it that way for at least one full release cycle.

**Comment by akacoding** [comment]
> const MaterialPtr actually means Material* const and not const Material* - but that aside, I think this is a question of convenience vs. consistency.

Yes, I misread it first and corrected myself with the second comment about the `SharedPtr`.

> Instead I suggest to add a warning if we are about to change the material, and keep it that way for at least one full release cycle.

I think that's a good solution because it's a breaking change.
