### ISSUE TITLE
GL2 Render System crash with Intel GMA X4500 on Windows 7

### ISSUE THREAD

**Issue by B-Keeper** [OGRECave/ogre#1867]
Built Ogre version 1.12.10 under Windows 7 64-bit with MinGW/MSYS2. With the GL2 render system, SampleBrowser crashes on startup, with the following Windows error report:

 Problem Event Name:	APPCRASH
  Application Name:	SampleBrowser.exe
  Application Version:	0.0.0.0
  Application Timestamp:	60130f9a
  Fault Module Name:	ig4icd64.dll
  Fault Module Version:	8.15.10.2302
  Fault Module Timestamp:	4d5586e7
  Exception Code:	c0000005
  Exception Offset:	0000000000073039
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0862
  Additional Information 2:	0862b4dd0d5455f17e9f9040def06146
  Additional Information 3:	4464
  Additional Information 4:	4464365c8b99e8a623a61b72f3fff1f2

I tested the official pre-built demo package, and its SampleBrowser crashes exactly the same way, therefore it's definitely not related to my compiler or build environment.

**Comment by paroj** [comment]
can you attach the log, which should be at `Documents/OGRE Sample browser/ `

**Comment by B-Keeper** [comment]
Thank you for the quick response. Here's the log file: [ogre.log](https://github.com/OGRECave/ogre/files/5890154/ogre.log)

**Comment by paroj** [comment]
that does not tell much, unfortunately.
Can you obtain a stack-trace of the crash with a debugger?

**Comment by B-Keeper** [comment]
Sure thing. Tomorrow, I'm going to compile a debug build and run it through GDB, then get back with the results.

**Comment by B-Keeper** [comment]
Okay, I had some time so I made the debug build. However, when run from GDB, it doesn't crash, therefore I can't provide a backtrace. (And even though it does run when invoked from the debugger, it runs terribly, and with glitches all around the place.)

Any ideas what I could do next?

**Comment by paroj** [comment]
are there any additional messages in the log?

**Comment by B-Keeper** [comment]
Here's a log file for the sample browser invoked from GDB: [ogre.log](https://github.com/OGRECave/ogre/files/5895747/ogre.log)

As for the D3D9 renderer, I cannot install the DX runtime right now, therefore I cannot tell you whether the aforementioned renderer works or not. However, while this GPU is rather dated (and was rather limited even when it was released), it is still fully OpenGL 2.1 compliant, and Ogre's GL renderer is so far the only software I had issues with, all the other apps/games I used ran flawlessly.

**Comment by paroj** [comment]
> it is still fully OpenGL 2.1 compliant

well if you google for "crash in ig4icd64", people tend to disagree :wink: 

the crash is inside the intel code and not ogre code. But still, if you can upload a screenshot of the corruption, I can maybe point you to some GL function that might be causing this.

Also try this older Ogre release, as I have a change in mind that could be causing this.
https://dl.bintray.com/ogrecave/ogre/:ogre-sdk-v1.12.8-vc15-x64.zip

**Comment by B-Keeper** [comment]
The release you linked crashes the same way, and so does the oldest version in the archives (1.10.12).

[Here are two screenshots](https://imgur.com/a/JZBnGrs). First one is the Sample Browser main screen, obviously, most of the elements won't even get rendered. Second is from the character demo, lighting is completely wrong, and, while I couldn't reproduce right now, during my last run the character shadow was clipping and glitching as well.

> well if you google for "crash in ig4icd64", people tend to disagree 

You are right, but I still found it strange that nothing else I tried had any issues with it so far. (And don't get me wrong, I'm not trying to start an argument - on the contrary, I am really grateful for your effort to try to help me with this one.)

**Comment by paroj** [comment]
the screenshot seem to indicate a problem with the texture format. Can you try the even older:
http://sourceforge.net/projects/ogre/files/ogre/1.9/1.9/OgreSDK_vc11_v1-9-0.exe/download

For debugging, rather use the RelWithDebinfo config. The Debug config can actually cover-up a class of bugs.

> You are right, but I still found it strange that nothing else I tried had any issues with it so far. 

most likely other engines have special intel workarounds in place. Also, older versions of ogre (pre 1.10) always allocated RGBA images on the GPU - regardless of the source format. Maybe this was the reason.

Also note that things work fine on Linux - I just tried with an old Laptop of mine that has a "Intel GMA HD 0x46" (whatever that is).

**Comment by B-Keeper** [comment]
That release you linked contains no prebuilt demos, but I might try to build them later on. I will get back to you once I'm done.

> For debugging, rather use the RelWithDebinfo config. The Debug config can actually cover-up a class of bugs.

I'll try that next time. In the meantime, to answer an earlier question, I did set up the DX runtime, built the D3D9 renderer, and it works flawlessly so far.

> Also note that things work fine on Linux - I just tried with an old Laptop of mine that has a "Intel GMA HD 0x46" (whatever that is).

Good to know, so it is definitely a driver issue.

**Comment by paroj** [comment]
without further information, there is not much we can do on the ogre side
