### ISSUE TITLE
Crash in OpenGL render system initialization

### ISSUE THREAD

**Issue by Borbitsoft** [OGRECave/ogre#1890]
#### System Information
- Ogre Version: v1.12.4
- Operating System / Platform: Ubuntu 18.04 LTS
- RenderSystem: OpenGL

#### Detailled description
The root cause of the crash is this line:
screenSizes = XRRConfigSizes(screenConfig, &nSizes);
https://github.com/OGRECave/ogre/blob/v1.12.4/RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp#L91
nSizes is 0 in case of the crash.
The returned pointer to an array of size infos is not a nullptr in that case, so the indexing wth currentSizeID still suceeds, although the data is all zeros in my case.
But the array mVideoModes is empty and then the array optVideoMode.possibleValues will also be empty here:
optVideoMode.currentValue = optVideoMode.possibleValues[0];
https://github.com/OGRECave/ogre/blob/v1.12.4/RenderSystems/GLSupport/src/OgreGLRenderSystemCommon.cpp#L70
That causes the crash.
I think you have to add a check on nSizes before you index into the screenSizes array and optVideoMode.possibleValues should be checked that it is not empty.
Why there are no size infos reported is still under investigation. May be it is related to power management.

**Comment by paroj** [comment]
should be fixed with https://github.com/OGRECave/ogre/pull/1889/commits/519a69927b4d66d4f1c3717e02295dce619d28b2
