### ISSUE TITLE
Doxygen API function inheritance

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre#1917]
In previous iterations of the OGRE API documentation, whenever a class had inherited functions they showed in the class documentation.

For example `Ogre::SceneNode` ([OGRE 1.8 - SceneNode](https://www.ogre3d.org/docs/api/1.8/class_ogre_1_1_scene_node.html)) showed functions inherited from `Ogre::Node` (like: `addChild (Node *child)`)

But now they are not showing unless one goes specifically to the `Ogre::Node` class [OGRE 1.12 - SceneNode](https://ogrecave.github.io/ogre/api/1.12/class_ogre_1_1_scene_node.html)

It would be nice to get back to that behaviour because sometimes it can be easy to forget to check the inheritance diagram.

Also another issue is that functions do not seem to be alphabetically ordered like in previous versions (but perhaps they are ordered by topic).

**Comment by paroj** [comment]
> It would be nice to get back to that behaviour because sometimes it can be easy to forget to check the inheritance diagram.

that change was on purpose as when showing all inherited members it is often impossible to see what a class actually does. 

See SimpleRenderable: [before](https://www.ogre3d.org/docs/api/1.8/class_ogre_1_1_simple_renderable.html) / [now](https://ogrecave.github.io/ogre/api/1.12/class_ogre_1_1_simple_renderable.html)

also at the end of SceneNode:
![](https://user-images.githubusercontent.com/4941802/110212978-49061500-7e9e-11eb-97d0-73f1a48cbe0b.png)

> Also another issue is that functions do not seem to be alphabetically ordered like in previous versions 

yes, thats required for grouping and @overload to work properly:
https://ogrecave.github.io/ogre/api/1.12/class_ogre_1_1_scene_node.html#a94ad2296a7da9a8ba0e3ac929b08f8c8

**Comment by sercero** [comment]
OK, I understand.

The changes are totally reasonable, I just have to get used to it.

Thanks!
