### ISSUE TITLE
RTSS OpenGL functions probably incorrect

### ISSUE THREAD

**Issue by VJigouline** [OGRECave/ogre#1920]
#### System Information
- Ogre Version: : master branch: 
- Operating System / Platform: : Any: 
- RenderSystem: : OpenGL RTSS shaders:

#### Detailled description
In the Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl RTSS functions 
`SGX_Light_Directional_Diffuse, SGX_Light_Directional_DiffuseSpecular, SGX_Light_Point_Diffuse, SGX_Light_Point_DiffuseSpecular, SGX_Light_Spot_Diffuse, SGX_Light_Spot_DiffuseSpecular` has colour clamping at the end like in this example
```GLSL
void SGX_Light_Directional_Diffuse(
				   in vec3 vNormal,
				   in vec3 vNegLightDirView,
				   in vec3 vDiffuseColour, 
				   inout vec3 vOut)
{
	vec3 vNormalView = normalize(vNormal);
	float nDotL = dot(vNormalView, vNegLightDirView);
	
	vOut += vDiffuseColour * clamp(nDotL, 0.0, 1.0);
	vOut = clamp(vOut, 0.0, 1.0);
}
```

When working with texturing I found that this clamping prevents correct transfer of lighting on the texture during **decal** stage so darker textures cannot be highlighted.

On my system I fixed the problem by removing clamping like this:
```GLSL
void SGX_Light_Directional_Diffuse(
				   in vec3 vNormal,
				   in vec3 vNegLightDirView,
				   in vec3 vDiffuseColour, 
				   inout vec3 vOut)
{
	vec3 vNormalView = normalize(vNormal);
	float nDotL = dot(vNormalView, vNegLightDirView);
	
	vOut += vDiffuseColour * clamp(nDotL, 0.0, 1.0);
	// vOut = clamp(vOut, 0.0, 1.0);
}
```
and everything begin working as expected.

The code in question has a long history so I am wondering, if this is a bug nobody noticed or there is some reason. I think that such a clamping shouldn't be done in the middle of the processing pipeline otherwise lighting can become non-linear, as I seen in my case, and some or all lighting can be lost.

**Comment by VJigouline** [comment]
![image](https://user-images.githubusercontent.com/6449956/110620295-c37db000-8190-11eb-918b-baf7986b35cc.png)
On the image attached left is with clamping present and right with removed.
Technique used:
```
	technique Textured
	{
		scheme Textured
		pass
		{
			cull_software none
			cull_hardware none
			lighting on
			shading phong
			ambient 0.6 0.6 0.6
			diffuse 1.5 1.5 1.5
			texture_unit decalmap
			{
				texture metalroof01.jpg
				scale 2000 2000
			}			
			rtshader_system Textured
			{
				lighting_stage ffp
			}
		}
	}
```

**Comment by paroj** [comment]
that clamp was introduced to match the fixed function lighting. So to verify whether the shader is wrong, you should compare with the OpenGL RenderSystem without RTSS.

Generally speaking, colours outside the 0..1 range are undefined as they are expected to be backed by uint8. Also, on GLES a `lowp float` as is typically used for colours has only a range of -2..2. So your `diffuse 1.5` statement is already invalid.

If your main goal is to just brighten the texture in the shader, without having to write one manually, you can use `colour_op_ex .. src_manual ..`.

**Comment by VJigouline** [comment]
Thank you for the explanation. I thought that I missed something.
