### ISSUE TITLE
OgreOverlayElement documentation is wrong about getWidth, etc.

### ISSUE THREAD

**Issue by akacoding** [OGRECave/ogre#1930]
The documentation about the following methods:

    void setDimensions(Real width, Real height);
    void setPosition(Real left, Real top);
    void setWidth(Real width);
    Real getWidth(void) const;
    void setHeight(Real height);
    Real getHeight(void) const;
    void setLeft(Real left);
    Real getLeft(void) const;
    void setTop(Real Top);
    Real getTop(void) const;

states that they are operating in relative screen space between 0 and 1.

That is the default case but not if it is changed with the according `setMetricsMode` call to `GuiMetricsMode::GMM_PIXELS`.

**Comment by paroj** [comment]
feel free to create a PR replacing the strings
```
...in relation to the screen (1.0 = screen width/height). 
```
by
```
...in relation to #GuiMetricsMode
```
