### ISSUE TITLE
ogre-sdk android not have shadows

### ISSUE THREAD

**Issue by ouxiang** [OGRECave/ogre#1953]
I'm working on ogre-sdk-android, but there are no shadow effects. Light Class have setDirection method in C ++,but Light Class not have setDirection method in sdk-android.What is the reason for this.

**Comment by paroj** [comment]
see https://www.ogre3d.org/2019/12/23/ogre-1-12-4-released

**Comment by ouxiang** [comment]
> see https://www.ogre3d.org/2019/12/23/ogre-1-12-4-released
![image](https://user-images.githubusercontent.com/7112672/113996296-9dc7f180-9889-11eb-9d46-3e720f71f729.png)
I test it by this way,but it not work

**Comment by paroj** [comment]
looks correct. what do you mean by "does not work"?

**Comment by ouxiang** [comment]
> looks correct. what do you mean by "does not work"?
no shadow effect added mesh in scene

**Comment by ouxiang** [comment]
> looks correct. what do you mean by "does not work"?

no  shadow effect added mesh in the scene

**Comment by paroj** [comment]
you must configure real time shadows separately:
https://ogrecave.github.io/ogre/api/latest/_shadows.html

note, that only texture shadows are supported on android.
