### ISSUE TITLE
Android SampleBrowserNDK crashs

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#1958]
#### System Information
- Ogre Version: 68fc4acfc18b69fb1e51ed0807df8435181a76ed
- Operating System / Platform: : Android / Arm7
- RenderSystem: Gles2.0 (I suppose)

#### Detailled description
It only crashs on first icon click, this is next the commit which says "Bites: Android - fix crash on surface recreation" 

#### Ogre.log
[logcat1.log](https://github.com/OGRECave/ogre/files/6254489/logcat1.log)

**Comment by paroj** [comment]
please comment out this line:
https://github.com/OGRECave/ogre/blob/68fc4acfc18b69fb1e51ed0807df8435181a76ed/Samples/Browser/CMakeLists.txt#L133

recompile and Run "Debug" via Android Studio to get a backtrace.

**Comment by Joilnen** [comment]
Still crashing after to comment that line in cmake file
[studio.log](https://github.com/OGRECave/ogre/files/6257502/studio.log)

**Comment by paroj** [comment]
could reproduce this with an old device of mine
