### ISSUE TITLE
The "Deferred Shading" sample crashs in SampleBrowserNDK

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#1962]
#### System Information
- Ogre Version:  bd097f77e06ee14a7c936ac4b346a21480edf588
- Operating System / Platform: Android/ Arm7 
- RenderSystem: GLES2

#### Detailled description
SampleBrowserNDK crashs when you choose "Deferred Shading" sample to run
[deferred_shading_mob.log](https://github.com/OGRECave/ogre/files/6264939/deferred_shading_mob.log)

**Comment by paroj** [comment]
to investigate this, I need the output of the debug tab when the crash occurs, like:
![debug](https://user-images.githubusercontent.com/4941802/113740658-341cdb80-9701-11eb-91ed-e67b27d1bea5.png)

**Comment by paroj** [comment]
probably fixed by 0e789c503b31d15bfc5893f708c7fcf18f605576

**Comment by Joilnen** [comment]
I having some problems with AndroidStudio, could I to try ndk-debug, some other ndk/sdk command line to check that ?

**Comment by paroj** [comment]
no idea. I guess it worth trying.

Keep in mind that you still have to remove this line to get debug symbols:
https://github.com/OGRECave/ogre/blob/68fc4acfc18b69fb1e51ed0807df8435181a76ed/Samples/Browser/CMakeLists.txt#L133
