### ISSUE TITLE
ogre-sdk-android  setConfigOption  FSAA  param  anti-aliasing  not work

### ISSUE THREAD

**Issue by ouxiang** [OGRECave/ogre#1965]
I'm working on ogre-sdk-android, setConfigOption("FSAA", "4")   anti-aliasing  not work

**Comment by ouxiang** [comment]
![image](https://user-images.githubusercontent.com/7112672/114117997-79682580-991a-11eb-8c32-5e327bafc90a.png)
I dont understand  the setConfigOption("FSAA", "4")  method working on the Android Devices

**Comment by paroj** [comment]
```java
	public class MyAppContext extends ApplicationContext
	{
		public boolean oneTimeConfig()
		{
			super.oneTimeConfig();
			getRoot().getRenderSystem().setConfigOption("Content Scaling Factor", "4");
			getRoot().getRenderSystem().setConfigOption("FSAA", "4");
			return true;
		}
	};
```

**Comment by ouxiang** [comment]
> ```java
> 	public class MyAppContext extends ApplicationContext
> 	{
> 		public boolean oneTimeConfig()
> 		{
> 			super.oneTimeConfig();
> 			getRoot().getRenderSystem().setConfigOption("Content Scaling Factor", "4");
> 			getRoot().getRenderSystem().setConfigOption("FSAA", "4");
> 			return true;
> 		}
> 	};
> ```

I add this code  of 'getRoot().getRenderSystem().setConfigOption("Content Scaling Factor", "4");' . The app  does not work, and 
 Option named Content Scaling Factor does not exist.
![image](https://user-images.githubusercontent.com/7112672/114176112-54e96900-996d-11eb-8122-65df92683aeb.png)

**Comment by paroj** [comment]
you need a build containing the changes mentioned above:
https://dl.cloudsmith.io/public/ogrecave/ogre/raw/files/ogre-sdk-android-master-arm64-v8a.zip

**Comment by ouxiang** [comment]
> you need a build containing the changes mentioned above:
> https://dl.cloudsmith.io/public/ogrecave/ogre/raw/files/ogre-sdk-android-master-arm64-v8a.zip

It still made the same error in this  android sdk.What is the reason？

**Comment by paroj** [comment]
must be on your end. I just re-downloaded the SDK and it works.
