### ISSUE TITLE
OSX build notes (possible doc update needed)

### ISSUE THREAD

**Issue by ephdot** [OGRECave/ogre#1971]
#### System Information
- Ogre Version: 1.12.11
- Operating System / Platform: OSX 11.2.3
- RenderSystem: openglES3+?

#### Detailled description
Hi there,
Needed some (undocumented?) changes to build:
in cmake-gui (v3.20), added:
BUILD_WITH_PCH=OFF
SWIG_USE_FILE=UseSWIG

In BuildOgre.md:
cmake --build . --config release  # Release (case sensitive) for OSX (as is Debug)
and
cmake --build . --config release --target INSTALL   # Release (case sensitive), install (lower case) for OSX

Was then able to run samples from xcode project - very cool!

Unable to run python sample.py, no matter how many path hints I could give it, always ends with ImportError:
 2): Library not loaded: @rpath/Ogre.framework/Versions/1.12.11/Ogre
and
Reason: image not found

First time building OGRE, hope these hints help others.

**Comment by paroj** [comment]
thanks for the case-sensitivity hints.

Regarding python - there are some changes in master that make it work on OSX. Furthermore, you can try the new pip packages:
```
pip install ogre-python
```
