### ISSUE TITLE
setDebugDisplayEnabled doesn't display anything with 1.12.12

### ISSUE THREAD

**Issue by corentinjaffre** [OGRECave/ogre#1981]
In my level editor, I'm displaying cameras using frustum and setDebugDisplayEnabled , and it worked until the last Ogre update.

![debug](https://user-images.githubusercontent.com/6184263/115989680-c6f1bd00-a5bf-11eb-91af-30b2095dce5a.jpg)
On the left, the frustum with 1.12.11, on the right with 1.12.12 (dx9)

I'm doing:
```
mDecalFrustum = new Ogre::Frustum();
mDecalFrustum->setDebugDisplayEnabled(true);
```

**Comment by paroj** [comment]
thats strange - there were no changes related to this between 1.12.11 and 1.12.12

**Comment by corentinjaffre** [comment]
Oh, my mistake. The previous ogre version I used was 1.12.5.

**Comment by paroj** [comment]
you probably need to call `mDecalFrustum->_notifyManager`

**Comment by corentinjaffre** [comment]
Thanks! It worked.
Just curious: why do I need to do this? Is it because I have several sceneManagers in my tool?

**Comment by paroj** [comment]
its part of the `SceneManager::createMovableObject` API, which you are supposed to follow even if you bypass the Manager.
Recently, debug drawing was accelerated by being done inside the SceneManager, but your frustum was in a "detached" state.
