### ISSUE TITLE
class ParticleVisualData is not define any where

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2021]
#### System Information
- Ogre Version: :grey_question: 1.13.0 
- Operating System / Platform: :grey_question: ParticleSystem 
- RenderSystem: :grey_question: any

#### Detailled description

class ParticleVisualData is not define any where

**Comment by 36yang** [comment]
How to attache ParticleVisualData to a particle now?

**Comment by paroj** [comment]
`ParticleVisualData` was removed for performance reasons. If you could elaborate on how you were using that, we can probably find a better alternative

**Comment by paroj** [comment]
no details provided
