### ISSUE TITLE
Ogre 1.x Android touch screen operation

### ISSUE THREAD

**Issue by ouxiang** [OGRECave/ogre#2028]
How can I touch moved or touch pressed  on android  devices? Please give a example

**Comment by paroj** [comment]
https://github.com/OGRECave/ogre/blob/d7845297d6c00785d09eebe493798dc64b5748ad/Samples/Browser/src/android_main.cpp#L47

**Comment by ouxiang** [comment]
> https://github.com/OGRECave/ogre/blob/d7845297d6c00785d09eebe493798dc64b5748ad/Samples/Browser/src/android_main.cpp#L47

It is c++,please give a java example.ok?

**Comment by paroj** [comment]
https://developer.android.com/guide/topics/ui/ui-events

**Comment by ouxiang** [comment]
> https://developer.android.com/guide/topics/ui/ui-events

I know android has a lot of ui-events. My question is that  haw to operate touchmoved event in ogre-sdk-android. For example,i execute the following code,the mousemove or mousewheel event are work on window.
![image](https://user-images.githubusercontent.com/7112672/122495094-4a59e880-d01c-11eb-9923-0d736216b5a8.png)
However，the touchmove event is not work on android.

**Comment by paroj** [comment]
you can modify `camnode` in the ui-event callbacks to control the camera.

I will take a look on whether you can do `_fireInputEventAndroid` from java to use CameraMan etc.

**Comment by paroj** [comment]
see https://github.com/OGRECave/ogre/pull/2090/commits/b005860eb824d1a7e9fe95c0bd49b9f2325aa695

**Comment by ouxiang** [comment]
> see [b005860](https://github.com/OGRECave/ogre/commit/b005860eb824d1a7e9fe95c0bd49b9f2325aa695)

it can work,thanks.

**Comment by ouxiang** [comment]
> > see [b005860](https://github.com/OGRECave/ogre/commit/b005860eb824d1a7e9fe95c0bd49b9f2325aa695)
> 
> it can work,thanks.

I find ogre event is MouseMotionEvent  from the example. I want to use ogre TouchFingerEvent,but it dose not work.Here is my code.
![image](https://user-images.githubusercontent.com/7112672/122726630-c6686080-d2a8-11eb-8383-69ae15e59478.png)
Please take a look at it.

**Comment by ouxiang** [comment]
> > > see [b005860](https://github.com/OGRECave/ogre/commit/b005860eb824d1a7e9fe95c0bd49b9f2325aa695)
> > 
> > 
> > it can work,thanks.
> 
> I find ogre event is MouseMotionEvent from the example. I want to use ogre TouchFingerEvent,but it dose not work.Here is my code.
> ![image](https://user-images.githubusercontent.com/7112672/122726630-c6686080-d2a8-11eb-8383-69ae15e59478.png)
> Please take a look at it.

I reference the  _fireInputEventAndroid  method  in the  OgreApplicationContextAndroid.cpp file.

**Comment by ouxiang** [comment]
> see [b005860](https://github.com/OGRECave/ogre/commit/b005860eb824d1a7e9fe95c0bd49b9f2325aa695)

The MouseMotionEvent  is work. Why didn't the other events work. for example:TouchFingerEvent
