### ISSUE TITLE
GCC11 fails with Werror 

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2047]
maybe not ogre3d related but it happen in the last commit ef05422f5c5733b66a240743333ce0827562e1dc
on "cmake -P ci-build.cmake build" in linux x86_64

-- Build files have been written to: /home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x
[ 25%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x/googletest/src/gtest-all.cc:42:
/home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x/googletest/src/gtest-death-test.cc:1224:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1224 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x/googletest/src/gtest-death-test.cc:1214:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1214 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/joilnen/ogre3d_devel/my/ogre3d-1.13.x/build/googletest-1.8.x/googletest/src/gtest-death-test.cc:1222:7: note: ‘dummy’ declared here
 1222 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [googletest/CMakeFiles/gtest.dir/build.make:76: googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:126: googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
-- Looking for pthread.h

**Comment by paroj** [comment]
I suggest disabling Werror

**Comment by Joilnen** [comment]
It happens when I compile with this changes in ci-build.cmake

@[joilnen@dijkstra ogre3d-1.13.x]$ head ci-build.cmake 
set(GENERATOR)
# set(OTHER -DCMAKE_CXX_FLAGS=-Werror)
set(CROSS)

set(CMAKE_BUILD_TYPE Debug)
set(BUILD_DEPS FALSE)
set(SWIG_EXECUTABLE /usr/bin/swig3.0)

set(RENDERSYSTEMS
    # tests only run with the legacy GL rendersystem as MESA is too old on buildbot

**Comment by paroj** [comment]
probably the Werror flag is still in some CMakeCache. Anyway.. this is a issue with gtest and not ogre. Therefore closing.
