### ISSUE TITLE
gradle greater than 6.9 is failing to build SambleBrowserNDK

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2059]
I got this error gradle 7.0.1 and gradle 7.0.2, seems some deprecated tags in build files.
One possible work around, is to create "gradlew" to build with gradle 6.9 
[output.txt](https://github.com/OGRECave/ogre/files/6591871/output.txt)

**Comment by paroj** [comment]
not sure what exactly is triggering this
