### ISSUE TITLE
function addLinkedSkeletonAnimationSource()  not work now

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2071]
#### System Information
- Ogre Version: :grey_question: 1.13.0
- Operating System / Platform: :grey_question: Win10
- RenderSystem: :grey_question:gl3+

#### Detailled description

the code below in ogre_1.12.5 is work fine, but don't work in ogre_1.13.0
the animationstate in other skeleton can't get now.

//mNode->yaw(Ogre::Degree(90), Ogre::Node::TS_PARENT);
	//mNode->setInheritOrientation(false);
	mEntity = appMgr->mSceneMgr->createEntity("ShuShanNan.mesh");
	mEntityNode->attachObject(mEntity);
	mEntityNode->setInheritOrientation(true);
	mEntityNode->setScale(0.00002, 0.00002, 0.00002);

	mEntity->getSkeleton()->addLinkedSkeletonAnimationSource("walk.skeleton");
	mEntity->getSkeleton()->addLinkedSkeletonAnimationSource("run.skeleton");
	mEntity->getSkeleton()->addLinkedSkeletonAnimationSource("attack_walk.skeleton");
	mEntity->getSkeleton()->addLinkedSkeletonAnimationSource("attack_run.skeleton");
	//mEntity->getSkeleton()->prepare();
	//mEntity->refreshAvailableAnimationState();
	mEntity->getSkeleton()->_refreshAnimationState(mEntity->getAllAnimationStates());
	
	auto as = mEntity->getAllAnimationStates();
	auto sis = as->getAnimationStateIterator();
	while (sis.hasMoreElements())
	{
		auto s = sis.getNext();
		Ogre::LogManager::getSingletonPtr()->logError(s->getAnimationName());
	}
	//mEntity->getSkeleton()->setBlendMode(ANIMBLEND_CUMULATIVE);

	const char* animNames[NUM_ANIMS] = { "idle", "walk", "run", "attack_walk", "attack_run", "idle", "idle", "idle" };
	for (int i=0; i< NUM_ANIMS; i++)
	{
		mAnims[i] = mEntity->getAnimationState(animNames[i]);
		mAnims[i]->setLoop(true);
	}
	mAction = AnimID::ANIM_IDLE;
	mAnims[mAction]->setEnabled(true);

**Comment by 36yang** [comment]
the media is there a zip file
[mesh.zip](https://github.com/OGRECave/ogre/files/6615007/mesh.zip)

**Comment by 36yang** [comment]
help help help!!   How to make it work now?

**Comment by paroj** [comment]
introduced in 638b7505b6a9161170f4fc2d930d842b1636e88e

**Comment by 36yang** [comment]
yes, it's good now
