### ISSUE TITLE
when building with assimp, error occurs for libIrrXML.a

### ISSUE THREAD

**Issue by brightprogrammer** [OGRECave/ogre#2072]
[ 45%] Linking CXX shared library ../../lib/Plugin_PCZSceneManager.so
[ 45%] Built target Plugin_PCZSceneManager
make[2]: *** No rule to make target 'Dependencies/lib/libIrrXML.a', needed by 'lib/Codec_Assimp.so.1.12.12'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object PlugIns/Assimp/CMakeFiles/Codec_Assimp.dir/src/AssimpLoader.cpp.o
[ 45%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgrePageContent.cpp.o
[ 46%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgrePageContentCollection.cpp.o
[ 46%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgrePageManager.cpp.o
[ 46%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgrePagedWorld.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1141: PlugIns/Assimp/CMakeFiles/Codec_Assimp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgrePagedWorldSection.cpp.o
[ 46%] Building CXX object Components/Paging/CMakeFiles/OgrePaging.dir/src/OgreSimplePageContentCollection.cpp.o
[ 46%] Linking CXX shared library ../../lib/libOgrePaging.so
[ 46%] Built target OgrePaging
make: *** [Makefile:156: all] Error 2

I use the following commands to build on manjaro linux : 
`cmake .. -DCMAKE_BUILD_TYPE=Release && make -j2`

Please help

**Comment by paroj** [comment]
set `OGRE_BUILD_DEPENDENCIES=OFF` and build it manually

**Comment by brightprogrammer** [comment]
I think I tracked down the problem to be in this cmake file : `ogre/PlugIns/Assimp/CMakeLists.txt`

here it assumes that libIrrXML.a is already present

`file(GLOB HEADER_FILES "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")
list(APPEND HEADER_FILES ${PROJECT_BINARY_DIR}/include/OgreAssimpExports.h)

add_library(Codec_Assimp ${OGRE_LIB_TYPE} ${HEADER_FILES} src/AssimpLoader.cpp)
target_include_directories(Codec_Assimp PUBLIC
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
    $<INSTALL_INTERFACE:include/OGRE/Plugins/Assimp>)
target_link_libraries(Codec_Assimp PUBLIC OgreMain PRIVATE fix::assimp)
if(OGRE_BUILD_DEPENDENCIES)
    # hack to get our CI build going, despite horribly broken assimp cmake
    if(UNIX)
        target_link_libraries(Codec_Assimp PUBLIC ZLIB::ZLIB ${OGREDEPS_PATH}/lib/libIrrXML.a)
    else()
        target_link_libraries(Codec_Assimp PRIVATE ZLIB::ZLIB ${OGREDEPS_PATH}/lib/IrrXML.lib)
    endif()
endif()

ogre_config_framework(Codec_Assimp)
ogre_config_plugin(Codec_Assimp)
generate_export_header(Codec_Assimp
    EXPORT_MACRO_NAME _OgreAssimpExport
    EXPORT_FILE_NAME ${PROJECT_BINARY_DIR}/include/OgreAssimpExports.h)
install(FILES ${HEADER_FILES} DESTINATION include/OGRE/Plugins/Assimp)`

**Comment by brightprogrammer** [comment]
Maybe if you can provide a rule to download and build IrrXML then the problem won't be there anymore

**Comment by paroj** [comment]
fixed by #2318

**Comment by hsc0320** [comment]
hello，so how you fix the problem finally.
