### ISSUE TITLE
glsl array type uniform can't find in NamedConstants

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2078]
#### System Information
- Ogre Version: :grey_question: 1.13.0
- Operating System / Platform: :grey_question: win10
- RenderSystem: :grey_question:gl3+

#### Detailled description

glsl array type uniform can't find in NamedConstants。
the reason is in OgreGpuProgramParams.cpp 
function of: GpuProgramParameters::_findNamedConstantDefinition(...)

line:
 if (i == mNamedConstants->map.end() || (i->second.arraySize == 1  && arrStart != String::npos))

Why the arraSize can't be 1

**Comment by paroj** [comment]
we use `arraySize == 1` for non-array uniforms. This means that we cannot differentiate `uniform int foo` from `uniform int foo[1]`, but we still want to flag wrong usage like `param_named bar[3] int 1` for `uniform int bar`.

In short, just use `param_named foo 1`, if you insist on using a one-element array.

**Comment by 36yang** [comment]
but my arraySize is variable,  I  set it by uniform foram like  foo[i]

**Comment by paroj** [comment]
GLSL does not allow variable sized arrays. Please provide a full example.

**Comment by paroj** [comment]
no reproducer provided
