### ISSUE TITLE
How to make the background/skybox/Viewport.background transparent

### ISSUE THREAD

**Issue by RockVampire** [OGRECave/ogre#2087]
I'm running something based on the newest Release of Android like the Demo in the Release.
Now ,I'm rendering the Scene on the SurfaceView.
In the Scene ,I have a model.And I want the background of the model transparent so I can see the view under the SurfaceView.
I tried to use Viewport.setBackground(new ColourValue(0f, 0f, 0f,0f)) and make a material ,set its enable Transparent , then create the skybox  by this material.
But they are all useless.
So , how can I do to achieve that?

**Comment by paroj** [comment]
you need a context that has an alpha channel. Try setting minColourBufferSize=32. See https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_render_system.html#a695ab7d97e8d2f2c648cf3bb95b4ed23

**Comment by RockVampire** [comment]
I Know that way.
But in Android , I use ApplicationContext.initAppForAndroid(AssetManager,Surface) to init ,and the 'surface' from the SurfaceView will be a ANativeWindow as know as the RenderWindow.
How and when can I recreate the RenderWindow?

**Comment by paroj** [comment]
just as everywhere else, you can override createWindow to inject miscParams

**Comment by RockVampire** [comment]
OK!
It helps a lot! Thank you!
