### ISSUE TITLE
1.12.12 - shadow sample crashes on dx11 when selecting "texture" instead of "stencil" based shadows

### ISSUE THREAD

**Issue by creadmefford** [OGRECave/ogre#2122]
![image](https://user-images.githubusercontent.com/976243/126047019-fe3a0ee3-9911-41b5-b2f5-1a9ba978170c.png)

when switching from stencil to texture shadows using dx11 the RTSS crashes with an error:

error X3017: 'FFP_VertexFog_Linear': cannot implicity convert from 'float4' to 'column_major float4x4' in D3D11HLSLProgram::compileMicrocode.

i saw this when trying to use RTSS in a custom tool but figured it was something i was doing wrong.  seeing it in the sample browser makes it appear more like a bug in RTSS.

**Comment by creadmefford** [comment]
workaround: change lighting to "additive" before changing "stencil" to "texture".  the crash still happens when you close the sample but so far makes the sample work.

**Comment by creadmefford** [comment]
shadows appear to be broken on dx11 when choosing the depth shadow material options.

**Comment by creadmefford** [comment]
i'm not sure the depth shadows are working on dx9 either.  the athena model is very dark whereas i recall it used to show the self-shadowing.

**Comment by paroj** [comment]
can you try the stable branch? I recall fixing something shadow related there.

As for the depth shadows - yes they are broken in the shadows sample. However, they should work in the RTSS sample, where they are implemented using the RTSS (the shadows sample still uses hand-written shaders there).

**Comment by creadmefford** [comment]
1.12.12 RTSS sample fails like this:
![image](https://user-images.githubusercontent.com/976243/126242166-5d2fe64f-6fdc-498f-988d-5483c2135ac8.png)

**Comment by creadmefford** [comment]
![image](https://user-images.githubusercontent.com/976243/126242847-c5276d21-54ae-4f3d-98cb-ebd491c8a942.png)
looks like stable is working i.e. the taurus appears to be self shadowing -- i'll try switching to this for my own shadow issues and see if it helps.

**Comment by creadmefford** [comment]
btw the lighting on the taurus in the RTSS demo looks fantastic!  (the one pictured above)

**Comment by paroj** [comment]
its just standard normal mapping. Take a look at Offset Mapping in the "Bump Mapping" Sample.

**Comment by creadmefford** [comment]
gotcha, thanks!

**Comment by paroj** [comment]
closing as fixed in stable & master
