### ISSUE TITLE
1.12.12 - memory leak in D3D11HLSLProgram if program->prepare() is called without later calling program->load()

### ISSUE THREAD

**Issue by creadmefford** [OGRECave/ogre#2139]
D3D11HLSLProgram frees memory for mSerStrings when D3D11HLSLProgram::unloadHighLevelImpl () is called:
for(unsigned int i = 0 ; i < mSerStrings.size() ; i++)
{
    delete mSerStrings[i];
}

this function is not called, however, if load () is never called.   this is because ResourceGroupManager::unloadResourceGroup () only calls unload if the program as a resource->isReloadable().

the fix is probably just to add the delete loop into the D3D11HLSLProgram destructor:
for(unsigned int i = 0 ; i < mSerStrings.size() ; i++)
{
    delete mSerStrings[i];
}

**Comment by creadmefford** [comment]
i can impl and test this out if this is the approach you want.

**Comment by paroj** [comment]
does https://github.com/OGRECave/ogre/pull/2142/commits/5bc0a2faeb80e74fd216359525973b16d3c46360 also work?

**Comment by creadmefford** [comment]
yes that will work great.
