### ISSUE TITLE
Error compiling for android  

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2140]
No rule to make target 'Dependencies/lib/libIrrXML.a', needed by 'lib/Codec_Assimp.so.13.
#### System Information
- Ogre Version: :grey_question: 8cdf0c26291cf8623a3544a98f04facae3252901
- Operating System / Platform: :grey_question: Android/ARM7
- RenderSystem: :grey_question: not important

**Comment by paroj** [comment]
duplicate of #2072
