### ISSUE TITLE
osx compile error when link to OgreOverlay

### ISSUE THREAD

**Issue by dandingol03** [OGRECave/ogre#2141]
Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      _FT_Gzip_Uncompress in libfreetype.a(ftgzip.o)
      _ft_gzip_file_fill_output in libfreetype.a(ftgzip.o)
  "_inflateEnd", referenced from:
      _FT_Stream_OpenGzip in libfreetype.a(ftgzip.o)
      _ft_gzip_stream_close in libfreetype.a(ftgzip.o)
      _FT_Gzip_Uncompress in libfreetype.a(ftgzip.o)
  "_inflateInit2_", referenced from:
      _FT_Stream_OpenGzip in libfreetype.a(ftgzip.o)
      _FT_Gzip_Uncompress in libfreetype.a(ftgzip.o)
  "_inflateReset", referenced from:
      _FT_Stream_OpenGzip in libfreetype.a(ftgzip.o)
      _ft_gzip_file_io in libfreetype.a(ftgzip.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paroj** [comment]
please fill out the issue template
