### ISSUE TITLE
Particle emitter can't burst particles

### ISSUE THREAD

**Issue by corentinjaffre** [OGRECave/ogre#2143]
Emitters uses an emission_rate  and a duration, which is good for smoke, or fire...
But a lot of particle effects should use a Burst emission type and a ParticleCount: 
ParticleCount particles are spawned at the same time for one frame, then the emitter stops emitting.
This is the only way to control the number of particles emitted for an explosion, or a flash,  for instance.

With an emission_rate, there is no way to really burst something without some hackish settings: a very big emission_rate and a very small emitter duration, which sometimes doesn't spawn anything, and doesn't look as good.
(And also there is no way to randomise the particle scale at its birth, which is a very basic requirement for any particle engine)

**Comment by paroj** [comment]
> With an emission_rate, there is no way to really burst something without some hackish settings: a very big emission_rate and a very small emitter duration, which sometimes doesn't spawn anything, and doesn't look as good.

you could also spawn the particles manually with:
https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_particle_system.html#af2a2e5a5d1356272a8fd12faa4aa8b85

Here, you can not only control the amount, but also the initial parameters like scale.

Alternatively, we could also add a `ParticleEmitter::burst(int count)` method, which adds count particles to the next tick (single shot).

> And also there is no way to randomise the particle scale at its birth

this could be easily implemented, by extending the Scaler Affector with an scale range - similar to what the Rotator offers:
https://ogrecave.github.io/ogre/api/latest/_particle-_scripts.html#Rotator-Affector

**Comment by corentinjaffre** [comment]
Thanks for your answers! I have to use particle scripts in my project and can not spawn the particles programmatically .

However I really think a burst/single shot should be added to particle scripts. (I was a FX artist, and with other engines I tend to use a lot more bursts emitters than continuous one).

As for the Scaler scale range, that would be perfect.

**Comment by paroj** [comment]
scale_range implemented in #2146

will think about how to do burst from particle script efficiently

**Comment by paroj** [comment]
> I have to use particle scripts in my project and can not spawn the particles programmatically

but you must have some code to trigger the effect and to reset the emitter afterwards, right?

**Comment by corentinjaffre** [comment]
Yes, the way I start/restart a particle effect in my code is (don't know if there is a better way):
```
Peffect->getEmitter(0)->setEnabled(false);
Peffect->getEmitter(0)->setEnabled(true);
```

**Comment by paroj** [comment]
what is your issue with doing
```cpp
for(int i; i<100;i++)
    Peffect->createParticle()
// or proposed API
Peffect->getEmitter(0)->burst(100);
```
there?

**Comment by corentinjaffre** [comment]
> 
> 
> what is your issue with doing
> 
> ```c++
> for(int i; i<100;i++)
>     Peffect->createParticle()
> // or proposed API
> Peffect->getEmitter(0)->burst(100);
> ```
> 
> there?

Thanks a lot for this new API!

Maybe I don't understand how it works, but I can't know in my engine if a particle emitter from a script need to burst or not (as the user will create its own particle script with the tool).

The only way I can think of to make that work, is to add a dummy "burst modifier" to the engine, add it to the particle scripts which need to burst, check in the engine if the modifier exists or not in a particle script, and if yes use the burst api getEmitter(0)->burst(100) (or the createParticle())
(which is okay by me for my particular project)

But as a general way, the result would be to hardcode in a game some particle emitter properties (burst or continuous?) and use the script for the other, which breaks Ogre data driven script philosophy in this case.

**Comment by paroj** [comment]
> Maybe I don't understand how it works, but I can't know in my engine if a particle emitter from a script need to burst or not 

it might also be that I dont understand the requirements :wink:
As I got it, "burst" is different to normal (time controlled) operation as it is time-less. So instead of talking about duration, we talk about events here. Like "an explosion, or a flash" you mentioned earlier.

Then the "burst" property is determined by an event path in your engine leading to the emitter and does not need to be declared anywhere.
The only information missing is the number of particles to burst, but that needs some thoughts as sometimes you want to say "this thing should burst into 3 parts" but sometimes you want to say "this explosion should create a FPS dependent number of particles to keep rendering smooth".

**Comment by corentinjaffre** [comment]
Actually, what I'm trying to very akwardly say is:
Burst should works within a particle script. So I guess the missing part is the ability to add inside an emitter script something like:
    emitter Point
    {
        emission_type burst
        emission_count   75
        time_to_live    3
    }
    
    with a default emission_type: continuous.

**Comment by paroj** [comment]
how about? https://github.com/OGRECave/ogre/pull/2157/commits/fcfd74935e76f8efa293652dfa9c2b212df89a17

**Comment by corentinjaffre** [comment]
Seems good to me!
A question: can we use a duration<0 to burst the particles, and use a repeat delay to burst again after a while?
(Ex: sparks, where sparks are bursting and starting again after a random repeat delay)

**Comment by paroj** [comment]
>  A question: can we use a duration<0 to burst the particles, and use a repeat delay to burst again after a while?

yes, that should work

**Comment by corentinjaffre** [comment]
I will test this very soon. Thanks a lot for your work!
