### ISSUE TITLE
1.12.12 - material file based sampler objects are not freed after call to Ogre::ResourceGroupManager::clearResourceGroup ()

### ISSUE THREAD

**Issue by creadmefford** [OGRECave/ogre#2145]
whenever a new scene is loaded i clear the scene resource group and reinitialize it:
Ogre::ResourceGroupManager::clearResourceGroup (GROUP);
Ogre::ResourceGroupManager::initialiseResourceGroup (GROUP);

i just started using material file sampler objects and when i re-initialize the resource group a duplicate exception is thrown.  i looked at Ogre::TextureManager::mDefaultSampler and don't see how it could be freed.

so repro steps:

1. when my app launches i call: Ogre::ResourceGroupManager::initialiseAllResourceGroups()
2. when i load a scene i call:
    Ogre::ResourceGroupManager::clearResourceGroup (GROUP);
    Ogre::ResourceGroupManager::initialiseResourceGroup (GROUP);

**Comment by paroj** [comment]
I indeed missed this use-case. It could be solved by inheriting from Resource in Sampler, so it they would be managed by ResourceGroupManager as well.
However, Samplers are tiny objects and adding the Resource API would increase their size by almost 4x.

Therefore I would rather go with a workaround like TextureManager::clearNamedSamplers(), that you would have to call additionally.

**Comment by creadmefford** [comment]
that would work great for me.

alternatively,  you could have a "newest definition wins" so that the most recent creation of a sampler releases the previous.  
so if i refresh a resource group the old samplers would just get overwritten.  i can't imagine these change often.  

then if someone needs more control they could call clearNamedSamplers () manually but everything would work as-is otherwise?

i'm happy with whatever you go with though.

**Comment by paroj** [comment]
>  so if i refresh a resource group the old samplers would just get overwritten.

however, if this happens by accident it would be hard to find bug. Therefore I prefer the explicit removeAllNamedSamplers() to allow "overwriting".
