### ISSUE TITLE
CMake Error: The source directory "E:/ogre/.0" does not exist.

### ISSUE THREAD

**Issue by hjhj111** [OGRECave/ogre#2158]
vs2019 CMake Error: The source directory "E:/ogre/.0" does not exist.

**Comment by paroj** [comment]
you have to add the path in the resources.cfg - see:
https://ogrecave.github.io/ogre/api/latest/setup.html#autotoc_md294

**Comment by hjhj111** [comment]
Where is resources.cfg? Does every project need one or shares one in a default folder?

**Comment by paroj** [comment]
closing as this is a vcpkg question
