### ISSUE TITLE
ogre-13 zlib.lib missing from OgreOverlay project after generating in cmake 3.2.1

### ISSUE THREAD

**Issue by creadmefford** [OGRECave/ogre#2167]
the OgreOverlay project needs a c++ linker reference to zlib.lib / zlibd.lib libraries to avoid linker errors on compile.

for some reason the cmake generated projects do not include this information.

**Comment by creadmefford** [comment]
workaround: manually add the zlib.lib / zlib_d.lib location paths manually to the visual studio projects.

**Comment by paroj** [comment]
should be fixed with https://github.com/OGRECave/ogre/commit/74c5ce3da1054b88a19f8e9f79d4492ec271ea1f
