### ISSUE TITLE
OgreRTShaderSystem.h cannot be found in MSBuild project

### ISSUE THREAD

**Issue by NancyLi1013** [OGRECave/ogre#2172]
#### System Information
- Ogre Version: 1.12.9
- Operating System / Platform: Windows 10 64-bit
- RenderSystem: N/A

#### Detailled description
After installed ogre via vcpkg, when using it in msbuild project, it build failed with `OgreRTShaderSystem.h
` cannot be found in `Bites/OgreSGTechniqueResolverListener.h` file.

The project like this https://github.com/celadaris/OgreTutorial/blob/main/OgreTutorial.cpp.
Related https://github.com/microsoft/vcpkg/issues/15333, https://github.com/microsoft/vcpkg/pull/19520

`OgreRTShaderSystem.h` is listed in https://github.com/OGRECave/ogre/blob/master/Components/RTShaderSystem/include/OgreRTShaderSystem.h in source codes.
`OgreSGTechniqueResolverListener.h` is listed in https://github.com/OGRECave/ogre/blob/master/Components/Bites/include/OgreSGTechniqueResolverListener.h in source codes.

While in vcpkg, all header files are installed in include/OGRE/ folder.

For `OgreRTShaderSystem.h`, it is listed in _include/OGRE/RTShaderSystem_ folfer.
For `OgreSGTechniqueResolverListener.h`, it is listed in _include/OGRE/Bites_ folder.

So we need to add update `"OgreRTShaderSystem.h"` as `"../RTShaderSystem/OgreRTShaderSystem.h"` in `Bites/OgreSGTechniqueResolverListener.h` file. In this case, the project can build fine.

Hi guys,
I'm vcpkg maintainer. Could you please help confirm if this is a upstream bug or something wrong in vcpkg? If possible, please help give some suggestion for this.

Thanks in advance!

**Comment by BillyONeal** [comment]
Effectively, this issue report is "ogre headers do not work when installed to the equivalent of `/usr/include`, headers in subdirectories that use quotes should use relative paths rather than expecting `/usr/include/ogre` to be on the include path".

**Comment by paroj** [comment]
The #incudes are correct. Ogre expects its individual components to be added to the include path, when used. e.g.
`include/OGRE/` for OgreMain, `include/OGRE/Bites` for OgreBites etc.

As OgreBites depends on OgreRTShader, both need to be added for OgreBites to work.

We handle this in Ogre by using CMake export targets, that have the include paths and any transient dependencies attached. (e.g. OgreBites might also use SDL2 libs).
See this for the recommended usage:
https://ogrecave.github.io/ogre/api/latest/setup.html#cmake

and this for the general technique:
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/Exporting-and-Importing-Targets

As this is pretty common nowadays, you probably already have ways to handle these inside vcpkg.

**Comment by BillyONeal** [comment]
>As this is pretty common nowadays, you probably already have ways to handle these inside vcpkg.

Not for non-CMake and non-pkgconfig customers, such as the original msbuild report. We strongly recommend ports not require modification of the include path to function as needing to add multiple include paths creates ambiguities (what if 2 ports use the same name?) and generally requires customers to modify their build systems.

@NancyLi1013 Since this is described as expected behavior by Ogre maintainers I don't believe there is anything reasonable vcpkg can do to fix it. MSBuild customers will need to do manual modifications to use Ogre.

**Comment by NancyLi1013** [comment]
Thanks for your help and information @paroj and @BillyONeal.
