### ISSUE TITLE
keyPressed doesn't works together frameStarted

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2183]
#### System Information
- Ogre Version: :grey_question: 34c970abfaa0ef308a2e6b03889cb82341b79ca0
- Operating System / Platform: :grey_question: linux x86_64
- RenderSystem: :grey_question:gl3plus

frameStarted makes the keyPressed doesn't work in project based on ApplicationContext, is this supposed a feature ?

**Comment by paroj** [comment]
https://github.com/OGRECave/ogre/blob/34c970abfaa0ef308a2e6b03889cb82341b79ca0/Components/Bites/include/OgreApplicationContextBase.h#L122-L125

**Comment by Joilnen** [comment]
Works, so should I pullEvents() in my own frameStarted method to make it works ?

**Comment by paroj** [comment]
> Works, so should I pullEvents() in my own frameStarted method to make it works ?

yes

**Comment by Joilnen** [comment]
Only as suggestion would be interesting to put this on documentation, to help others who gets similar issues ?

**Comment by paroj** [comment]
where would you, as a user, expect this documentation? i.e. did you look somewhere for it already?
