### ISSUE TITLE
Pssm shadow breaked implent by RtShaderSystem

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2197]
When the pssm shadow realized by RTShaderSystem is observed at a close distance, the shadow appears to be broken. And the shadow flickering problem at the junction of different levels

**Comment by 36yang** [comment]
This is my demo show the problem
[bugReport.zip](https://github.com/OGRECave/ogre/files/7199921/bugReport.zip)

**Comment by paroj** [comment]
thanks for the reproduces. However, please base your code on:
https://github.com/OGRECave/ogre/blob/master/Samples/Tutorials/Bootstrap.cpp

I am using Linux and porting your code would take too much time. Using `OgreBites::ApplicationContext` will ensure that the code is cross-platform.

**Comment by 36yang** [comment]
[bugReport2.zip](https://github.com/OGRECave/ogre/files/7205202/bugReport2.zip)
I make it run base on Bootstrap.cpp now.  
May I know the problem, it was because I changed  the camera near and far clip distance. Because I must fit the physics Engine unit。 So I can't set the near clip distance too much。 Can there has some solutions?

**Comment by paroj** [comment]
> And the shadow flickering problem at the junction of different levels

the split points in your material do not match what you specify in the code. User this to avoid such problems:

https://github.com/OGRECave/ogre/blob/75f5536496b3251b8937c49e528c7e5996dd6ae2/Samples/ShaderSystem/src/ShaderSystem.cpp#L1042

also your padding is too small:
https://github.com/OGRECave/ogre/blob/75f5536496b3251b8937c49e528c7e5996dd6ae2/Samples/ShaderSystem/src/ShaderSystem.cpp#L1033

> May I know the problem, it was because I changed the camera near and far clip distance. 

yes, if your object is clipped by the near plane like this

![screenshot](https://user-images.githubusercontent.com/4941802/134262539-9c170089-fcf6-4eb0-8356-c9ad636cfb43.jpg)

it is also clipped in PSSM, see:
https://docs.microsoft.com/en-us/windows/win32/dxtecharts/cascaded-shadow-maps#calculating-a-view-frustum-bound

**Comment by 36yang** [comment]
Yes, When I fixed the pssm distance in my Maiterial. But I still find a problem. At the Scene When the camera is far away. that large than the  shadow far distane (in my demo is 60) .  There should no shadow on the plan. But there has a shadow that Flickering
