### ISSUE TITLE
error while cmake configuring 

### ISSUE THREAD

**Issue by denk1** [OGRECave/ogre#2204]
Hello everybody! I have a some problem with building the release 13.0.1 
Why does it happen when I try to configure a project by **cmake** I get this error:

**CMake Error at /usr/local/lib/cmake/SPIRV-Tools/SPIRV-ToolsConfig.cmake:3 (get_target_property):
  get_target_property() called with non-existent target "SPIRV-Tools".
Call Stack (most recent call first):
  CMake/Dependencies.cmake:230 (find_package)
  CMakeLists.txt:290 (include)**

My platform is Ubuntu: Ubuntu 20.04.3 LTS, gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
I had already  installed SPIR-V Headers and SPIRV-Tools before I started doing a configure

**Comment by paroj** [comment]
use the `spirv-tools` package (instead of your local install) or set `OGRE_BUILD_PLUGIN_GLSLANG=OFF` in cmake.

The error caused by SPIRV-Tools installing broken cmake scripts and is not Ogre specific.

**Comment by denk1** [comment]
I have set OGRE_BUILD_PLUGIN_GLSLANG=OFF but nothing has changed. 
What do you mean the spirv-tools package? 
I set it from the ubuntu repositories and I also build it from sources however I got the same error.

**Comment by paroj** [comment]
it is always using the version you built yourself.
`rm -rf /usr/local/lib/cmake/SPIRV-Tools/` and it should work.

**Comment by denk1** [comment]
it actually works!
Many thanks to you!
