### ISSUE TITLE
Resource listener on Manual RTT stop working

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#2267]
#### System Information
- Ogre Version: :grey_question: 1.13 current master branch (but patched)
- Operating System / Platform: :grey_question: Windows
- RenderSystem: :grey_question: OpenGL

#### Detailled description
I was using resource listener on RTT for stereo implementation, but since I've updated to the current version 
loadingComplete and unloadingComplete are no longer called. It was initialized this way :

` viewportData->mLeftRenderTexture = Ogre::TextureManager::getSingleton().createManual(SO3_INTERNAL_RESOURCE_GROUP + Ogre::String("/STEREO/LEFT/RTT") + Ogre::StringConverter::toString(viewport->getZOrder() + 1), SO3_INTERNAL_RESOURCE_GROUP, Ogre::TEX_TYPE_2D, leftWidth, leftHeight, 0, rttFormat, Ogre::TU_RENDERTARGET);
    viewportData->mLeftRenderTexture->getBuffer()->getRenderTarget()->setAutoUpdated(false);
#if defined (RPI)
    viewportData->mLeftRenderTexture->getBuffer()->getRenderTarget()->setDepthBufferPool(Ogre::DepthBuffer::POOL_NO_DEPTH);
#endif
    viewportData->mLeftRenderTexture->addListener(viewportData->rttListener);`

**Comment by paroj** [comment]
introduced in 7f45c9cfd23e4a703f254031584b2d56655afd21

**Comment by arkeon7** [comment]
Ok thanks, so I should consider the manual texture loaded on create ?

**Comment by paroj** [comment]
yes - but Ogre also needs some fixes to notify the listener where it currently does not.

**Comment by arkeon7** [comment]
Ok thanks
