### ISSUE TITLE
Shader parameters

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#2312]
#### System Information
- Ogre Version: :grey_question:  Master
- Operating System / Platform: :grey_question: Windows
- RenderSystem: :grey_question: OpenGL

#### Detailled description
Some compositors samples like ASCII seems to be broken.
Another previously working shaders (in Ogre 1.11) stop to work, in CG or GLSL, I wonder if this is related to floats program parameters 

#### Ogre.log
No exception or error in logs

**Comment by paroj** [comment]
which revision are you at? with 3edfc05 ASCII works for me.

**Comment by arkeon7** [comment]
You're right, I just updated to the last revision and all is back correctly. thanks.
