### ISSUE TITLE
13.2.2+: RenderSystem_GL linking with "-Wl,--no-undefined" broken

### ISSUE THREAD

**Issue by susnux** [OGRECave/ogre#2316]
#### System Information
- Ogre Version: 13.2.4
- Operating System / Platform: openSUSE Tumbleweed (Linux)
- RenderSystem: :grey_question:

#### Detailled description
Compiling 13.1.1 works fine, but 13.2 is broken on openSUSE as of `undefined reference` error within the GLRenderSystem.
I attached a full build log, including cmake configuration and all packages that are installed.

#### Log
One example error, full log is [here build.log](https://github.com/OGRECave/ogre/files/7710701/build.log)

```
[  198s] /home/abuild/rpmbuild/BUILD/ogre-13.2.4/RenderSystems/GL/src/OgreGLRenderSystem.cpp: In member function '_setCullingMode':
[  198s] /home/abuild/rpmbuild/BUILD/ogre-13.2.4/RenderSystems/GL/src/OgreGLRenderSystem.cpp:1780:40: warning: 'cullMode' may be used uninitialized in this function [-Wmaybe-uninitialized]
[  198s]  1780 |         mStateCacheManager->setCullFace( cullMode );
[  198s]       |                                        ^
[  198s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccLEkj2R.ltrans0.ltrans.o: in function `PS_1_4::bindMachineInstInPassToFragmentShader(std::vector<unsigned int, std::allocator<unsigned int> > const&)':
[  198s] <artificial>:(.text+0xe8e): undefined reference to `glGetError'
[  198s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: <artificial>:(.text+0x1139): undefined reference to `glGetError'
[  198s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccLEkj2R.ltrans0.ltrans.o: in function `Ogre::ATI_FS_GLGpuProgram::bindProgram()':
[  198s] <artificial>:(.text+0x24fb): undefined reference to `glEnable'
```

**Comment by susnux** [comment]
I tried 13.2.1 and it compiles, so I think it is related to this commit, https://github.com/OGRECave/ogre/commit/aa9ffa7a51e52cb714f1bf5a3a00b9ef9f5a7dc2, introduced with 13.2.2.

**Comment by paroj** [comment]
just built v13.2.4 in a tubleweed docker container and everything worked fine
