### ISSUE TITLE
Building in Linux for Android issues after this commit

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2322]
Building 1dcb1b0049d56781c3acaeb6d3eb08987d9d04ee in linux I got this:
---
[  0%] Linking CXX static library ../lib/libOgreMainStatic.a
Error running link command: No such file or directory
make[2]: *** [OgreMain/CMakeFiles/OgreMain.dir/build.make:3354: lib/libOgreMainStatic.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:486: OgreMain/CMakeFiles/OgreMain.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by paroj** [comment]
works on CI: https://github.com/OGRECave/ogre/runs/4549011534?check_suite_focus=true

**Comment by Joilnen** [comment]
I mean building for android from linux

**Comment by paroj** [comment]
yes, thats what the CI does

**Comment by Joilnen** [comment]
Did you can to build it following documentations instructions ? Because I got linkeditation error, could you check if you can to build only like it is in docs.
---
cmake -DCMAKE_TOOLCHAIN_FILE=/path_to_ndk/build/cmake/android.toolchain.cmake -DANDROID_NDK=/path_to_ndk .
make -j 8

**Comment by paroj** [comment]
the log says you are doing a x86 build against the arm dependencies. I suggest doing `rm -rf build` and start over.

**Comment by Joilnen** [comment]
ok it seems works now, I am not sure what happened, at firsts times I tried this seems getting linkage problems, yes the last output is wrong, anyway I am closing this one time it is working fine to me again, thank you for your attention.
