### ISSUE TITLE
MyGUI incompatibility

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#2349]
@sercero I recently rebuild stuntrally against Ogre 13, which also included MyGUI:
https://github.com/paroj/stuntrally/blob/dd0adb1e61a66d66fecbe3a39f03d01bd4a47c64/snapcraft.yaml#L77

at least with `OGRE_RESOURCEMANAGER_STRICT=0`, it seemed to work fine. Did you encounter anything specific?

**Comment by sercero** [comment]
Hello @paroj,

Thanks for the info and I am glad that MyGUI works correctly. From what I have seen, Stunt Rally uses MyGUI extensively so this is great news!

I am not using Ogre 13 at the moment so I was being led by what some user posted on the Ogre forums.
Now I can't find the post, but here is the MyGUI issue:
https://github.com/MyGUI/mygui/issues/230

It seems we have to bug Altren to solve the Resource Manager issue, he did some work there but there is more to do apparently.

**Comment by corentinjaffre** [comment]
MyGUI is working perfectly for me with Ogre.13, on DX9c I didn't try it yet with 13.3.
Except for the issue above, and this one which may not be related to Ogre and was not fixed:
[](https://github.com/MyGUI/mygui/issues/229)

**Comment by paroj** [comment]
fixed in mygui
