### ISSUE TITLE
Use the proper 64-bit architecture detection code, not whitelisting.

### ISSUE THREAD

**Issue by ilyakurdyukov** [OGRECave/ogre#2359]
I think it's bad practice.

```c
/* Find the arch type */
#if defined(__x86_64__) || defined(_M_X64) || defined(_M_X64) || defined(_M_AMD64) \
 || defined(__ppc64__) \
 || defined(__arm64__) || defined(__aarch64__) || defined(_M_ARM64) \
 || defined(__mips64) || defined(__mips64_) \
 || defined(__alpha__) || defined(__ia64__) || defined(__s390__) || defined(__s390x__)
#   define OGRE_ARCH_TYPE OGRE_ARCHITECTURE_64
#else
#   define OGRE_ARCH_TYPE OGRE_ARCHITECTURE_32
#endif
```

Which is missing Elbrus 2000, which is `defined(__e2k__)`, but I think it's better to stop using whitelists. 

There are many ways to find out if an architecture is 64-bit even if the architecture is unknown to you, for example:

```c
#define _LP64 1
#define __LP64__ 1
#define __SIZE_WIDTH__ 64
#define __SIZEOF_POINTER__ 8
```

Using `__LP64__` and `_LP64` is the most common way to detect that.

**Comment by ilyakurdyukov** [comment]
Also, OGRE_ARCH_TYPE is set twice in this header, the previous one on line 73, and this one on line 187: 

```c
    /* Find the arch type */
#if defined(__x86_64__) || defined(_M_X64) || defined(_M_AMD64) || defined(_M_ARM64) || defined(__powerpc64__) || defined(__alpha__) || defined(__ia64__) || defined(__s390__) || defined(__s390x__) || defined(__arm64__) || defined(__aarch64__) || defined(__mips64) || defined(__mips64_) || (defined(__riscv) && (__riscv_xlen == 64))
#   define OGRE_ARCH_TYPE OGRE_ARCHITECTURE_64
#else
#   define OGRE_ARCH_TYPE OGRE_ARCHITECTURE_32
#endif
```

**Comment by ilyakurdyukov** [comment]
Thank you.

Just it the case if there exist compiler that doesn't set `__LP64__/_LP64` for a 64-bit architecture, "try_compile" detection can be done in comfigure/cmake.

This code shouldn't compile for 32-bit architectures: 

```c
#include <stddef.h>
int main(int argc, char **argv) {
	switch (argc) {
		case sizeof(int): return 1;
		case sizeof(size_t): break;
	}
	return 0;
}
```

With the "duplicate case value" error because `int` and `size_t` will be the same size.

So you can use this method if you ever find such a compiler.

**Comment by paroj** [comment]
there is also `CMAKE_SIZEOF_VOID_P` for that. However, all compilers we currently support seem to work for now. (tested via godbolt)
