### ISSUE TITLE
MeshLodGenerator have memory leak problem

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2365]
#### System Information
- Ogre Version: :grey_question:  latest  version > 1.13.2.4  
- Operating System / Platform: :grey_question: Win10
- RenderSystem: :grey_question:GL3+

#### Detailled description

  The MeshLodGenerator have memory leak problem, When I generate Some Mesh Lods then Changed  to other mesh,
the old  mesh lod IndexBuffer memory was not freed!   And there no way  to free it. 
The  problem also  exist in sample browser of  MeshLod samples!

**Comment by paroj** [comment]
can you provide a PR fixing this?

**Comment by paroj** [comment]
likely fixed by MeshLOD refactoring in Ogre 14
