### ISSUE TITLE
Can't compile with andoird ndk r21e

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2397]
Compiling from linux for android I got this error
[output.txt](https://github.com/OGRECave/ogre/files/8186002/output.txt)

**Comment by paroj** [comment]
https://developer.android.com/ndk/guides/graphics/shader-compilers#%E2%80%9Dgradle%E2%80%9D

**Comment by Joilnen** [comment]
would be worth to automatize this steps ? In cmake files maybe ?

**Comment by paroj** [comment]
the CI build does this:
https://github.com/OGRECave/ogre/blob/aa7604254ee07a9e95d339652eca0ee1aaf9c2f5/ci-build.cmake#L97-L99

the regular build, however, should not mess with the system-wide NDK. So no.
