### ISSUE TITLE
csharp is enabled uncoditionally on linux

### ISSUE THREAD

**Issue by rhaschke** [OGRECave/ogre#2408]
When building Ogre 13.3.2 on Ubuntu 20.04, I get:
[ 90%] Linking CXX shared module ../../csharp/libOgre.so
/bin/sh: 1: mcs: not found

Disabling C# resolves the issue for me. Looks like the dependency `mcs` should be checked for before enabling C# support.

**Comment by paroj** [comment]
cmake support for that is only present on windows:
https://gitlab.kitware.com/cmake/cmake/-/issues/16865

workaround: disable csharp in cmake
