### ISSUE TITLE
'Ogre::StringStream' has incomplete type and cannot be defined

### ISSUE THREAD

**Issue by susnux** [OGRECave/ogre#2424]
#### System Information
- Ogre Version: 13.2.4
- Operating System / Platform: Linux, openSUSE Tumbleweed, GCC11
- RenderSystem: -

#### Detailled description
Building something using `Ogre::StringStream` fails with `'Ogre::StringStream' has incomplete type and cannot be defined`.
So as `Ogre::StringStream` is a typedef of `std::stringstream`, the `<sstream>` header has to be included in `OgrePrerequisites.h`.

`OgrePrerequisites.h` includes `OgreStdHeaders.h`, but that is also only including `<ostream>` and not `<sstream>`.

**Comment by paroj** [comment]
users are supposed to include `<sstream>` themselves. The StringStream typedef is merely kept for backward compatibility.
