### ISSUE TITLE
StaticGeometry::setRenderingDistance(...) does not work as expected

### ISSUE THREAD

**Issue by stefanroellin** [OGRECave/ogre#2427]
#### System Information
- Ogre Version: 13.3
- Operating System / Platform: all
- RenderSystem: all

#### Detailled description

The description of the function StaticGeometry::setRenderingDistance says:
> Sets the distance at which batches are no longer rendered.
> @remarks
> This lets you turn off batches at a given distance. This can be useful for things like detail meshes (grass, foliage etc) and could be combined with a shader which fades the geometry out beforehand to lessen the effect.

However, tests have shown that the geometry is always rendered. In StaticGeometry::setRenderingDistance(...), two variables are set, which aren't used anywhere, which verifies that the function does not work as expected.

See also https://forums.ogre3d.org/viewtopic.php?t=56924

**Comment by paroj** [comment]
probably `StaticGeometry::Region::_notifyCurrentCamera` should look more like this:
https://github.com/OGRECave/ogre/blob/20b2da4361207a80104d72388acd28930b5035eb/OgreMain/src/OgreMovableObject.cpp#L202
