### ISSUE TITLE
Build Ogre on macOS 12.3.1

### ISSUE THREAD

**Issue by JuliusNmn** [OGRECave/ogre#2471]
Building Ogre fails on macOS 12.3.1 with the following error:

```
In file included from /tmp/pip-req-build-5p74vdz4/PlugIns/STBICodec/src/OgreSTBICodec.cpp:29:
  In file included from /tmp/pip-req-build-5p74vdz4/PlugIns/STBICodec/include/OgreSTBICodec.h:32:
  In file included from /tmp/pip-req-build-5p74vdz4/OgreMain/include/OgreImageCodec.h:31:
  In file included from /tmp/pip-req-build-5p74vdz4/OgreMain/include/OgreCodec.h:31:
  In file included from /tmp/pip-req-build-5p74vdz4/OgreMain/include/OgrePrerequisites.h:30:
  /tmp/pip-req-build-5p74vdz4/OgreMain/include/OgrePlatform.h:164:13: fatal error: 'Availability.h' file not found
  #   include "Availability.h"
              ^~~~~~~~~~~~~~~~
  1 error generated.
```

I am trying to build the python library using ```pip wheel . --verbose```

**Comment by JuliusNmn** [comment]
[ogre.log](https://github.com/OGRECave/ogre/files/8705912/ogre.log)

**Comment by paroj** [comment]
hello first user of Ogre on a M1 chip! Try removing this block from CMake:
https://github.com/OGRECave/ogre/blob/0a6d5f36ce8040c6db6fb6d72f430070e4e851d7/CMakeLists.txt#L284-L290

I will try to get access to a M1 machine..

**Comment by paroj** [comment]
jup, that helped. Uploaded an ARM64 build to PIP.
