### ISSUE TITLE
no package 'GLSL_Optimizer' 

### ISSUE THREAD

**Issue by EdwardVincentMa** [OGRECave/ogre#2488]
cmake -H. -B./build

-- Looking for GLSL_Optimizer...
-- GLSL_Optimizer_PREFIX_PATH changed.
-- Checking for module 'GLSL_Optimizer'
--   **No package 'GLSL_Optimizer' found**
-- Could not locate GLSL_Optimizer
-- Looking for HLSL2GLSL...
-- HLSL2GLSL_PREFIX_PATH changed.
-- Checking for module 'HLSL2GLSL'
--   **No package 'HLSL2GLSL' found**
-- Could not locate HLSL2GLSL

**Comment by paroj** [comment]
so what?
