### ISSUE TITLE
BULLET_XXXX_LIBRARY not found?

### ISSUE THREAD

**Issue by smu-sc-gj** [OGRECave/ogre#2511]
I've been working with the current version of Ogre (bc3221a5e582f8ffdad54eb35b6c015c4330a975). 

During the build process CMake can only find the BULLET_INCLUDE_DIRECTORY, it can't find any of the BULLET_xxxxx_LIBRARY entries.  After deleting my cache, debug directory, cloning a fresh copy etc. I noted the Bullet libraries being built and removed the QUITE from the Find for bullet, the error suggested that bullets .lib files couldn't be found.  I checked the .lib files for the missing libraries were present and they are but all have a postfix"_relWithDebug" which appears to be the reason for them (and hence bullet,) not being found.   I renamed the files and bullet is found and I get the option for the  bullet component.

**Comment by paroj** [comment]
please attach the info of the default issue template.

**Comment by smu-sc-gj** [comment]
**System Information** 

Ogre Version: 13.4.2
Operating System / Platform: Windows 10 Education / x64
RenderSystem: OpenGL 3+

CMake: 3.19.5

*Detailed Description*

On a fresh clone of the Ogre the dependencies are built, including Bullet.  

However, despite there being evidence of it being built CMake shows only the header files are found and none of the libraries. 

![BulletBuilding](https://user-images.githubusercontent.com/1557325/177734395-b232decc-73af-47b5-bcaa-9f88f294c3c3.PNG)

![BulletLibsNotFound](https://user-images.githubusercontent.com/1557325/177734405-c4c235a9-aea9-4de9-8401-217e664b1e7f.PNG)

Checking the directory where they are built they appear to have a postfix "_relWithDebug" if I rename the files and remove this this then the component is found and Ogre will compile.  

![BulletLibNames-postfix](https://user-images.githubusercontent.com/1557325/177734400-ca349242-e646-416e-98e1-6c0c44483d38.png)

I'm sure this is fairly recent, I was looking at this a few weeks ago and had no issues.   

Potential fixes:
1. Quick work around is to just rename the files and remove the postfix. 
2.  Modify the CMakeLists file that downloads and builds Bullet 

message(STATUS "Building Bullet")
    file(DOWNLOAD
        https://github.com/bulletphysics/bullet3/archive/refs/tags/3.24.tar.gz
        ${PROJECT_BINARY_DIR}/3.24.tar.gz)
    execute_process(COMMAND ${CMAKE_COMMAND}
        -E tar xf 3.24.tar.gz WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    execute_process(COMMAND ${BUILD_COMMAND_COMMON}
        -DBUILD_SHARED_LIBS=OFF
        -DINSTALL_LIBS=ON
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DUSE_MSVC_RUNTIME_LIBRARY_DLL=ON
        -DBUILD_PYBULLET=OFF
        -DUSE_DOUBLE_PRECISION=OFF
        -DBUILD_CPU_DEMOS=OFF
        -DBUILD_BULLET2_DEMOS=OFF
        -DBUILD_EXTRAS=OFF
        -DBUILD_EGL=OFF
        -DBUILD_ENET=OFF
        -DBUILD_UNIT_TESTS=OFF
        -DBUILD_CLSOCKET=OFF
# -----------  Added this line ----------------------------
	-DCMAKE_RELWITHDEBINFO_POSTFIX=
# ----------------------------------------------------------
        ${PROJECT_BINARY_DIR}/bullet3-3.24
        WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/bullet3-3.24)
    execute_process(COMMAND ${CMAKE_COMMAND}
        --build ${PROJECT_BINARY_DIR}/bullet3-3.24 ${BUILD_COMMAND_OPTS})
    set(BULLET_ROOT ${OGREDEPS_PATH})

**Comment by paroj** [comment]
could reproduce it here: https://ci.appveyor.com/project/paroj/ogre-bsrh7/builds/44106973?fullLog=true

a workaround is to run `cmake -DCMAKE_BUILD_TYPE=release ...` to build the deps as release while building Ogre as relwithdebinfo afterward
