### ISSUE TITLE
Cmake Can't find OgreBullet 

### ISSUE THREAD

**Issue by FierceJDM** [OGRECave/ogre#2515]
I'm trying to include OgreBullet in my project, but cmake doesn't seem to detect it.
After changing the find_package command to `find_package(OGRE REQUIRED COMPONENTS Bites Bullet CONFIG)` Cmake shows this error :
```
CMake Error at CMakeLists.txt:11 (find_package):
  Found package configuration file:

    D:/Ogre/ogre 2nd attempt/Build/cmake/OGREConfig.cmake

  but it set OGRE_FOUND to FALSE so package "OGRE" is considered to be NOT
  FOUND.  Reason given by package:

  Component 'Bullet' is required but was not found
```

**Comment by paroj** [comment]
please attach the info of the default issue template.

**Comment by FierceJDM** [comment]
Yes sure here it is : 
#### System Information

- Ogre Version: 13.4.1 (Tsathoggua)
- Operating System / Platform: Windows 7 64-bit
- RenderSystem: OpenGL

#### Detailled description

Can't bring OgreBullet included in my project (see first comment in this issue)

#### Ogre.log

Cmake GUI : 
```
CMake Error at CMakeLists.txt:11 (find_package):
  Found package configuration file:

    D:/Ogre/ogre 2nd attempt/Build/cmake/OGREConfig.cmake

  but it set OGRE_FOUND to FALSE so package "OGRE" is considered to be NOT
  FOUND.  Reason given by package:

  Component 'Bullet' is required but was not found



Configuring incomplete, errors occurred!
See also "D:/Ogre/Test Project/build/CMakeFiles/CMakeOutput.log".
```

**Comment by paroj** [comment]
> Ogre Version: 13.4.1 (Tsathoggua)

try current master (13.4.2)

**Comment by FierceJDM** [comment]
So i rebuild the whole ogre another time, right ?

**Comment by paroj** [comment]
there is also a prebuild SDK for master for quick testing: https://dl.cloudsmith.io/public/ogrecave/ogre/raw/versions/master/ogre-sdk-master-msvc141-x64.zip

**Comment by FierceJDM** [comment]
Okay ! But if someone even needs Bullet with Ogre, do i have to first install it manually from pybullet.org ?

**Comment by paroj** [comment]
> Now, you mentioned that the Ogre SDK comes with Bullet, do you mean like Bullet is already built and ready to use ?

OgreBullet links statically against Bullet, so you can directly use a subset of Bullet by using the Ogre SDK

Bullet itself is built like this:
https://github.com/OGRECave/ogre/blob/e535556dbd31955e9205f9282602047034171c0f/CMake/Dependencies.cmake#L164-L188

**Comment by FierceJDM** [comment]
After using the SDK, the Cmake error disappeared, and now Bullet is included in the the installed components : 
![image](https://user-images.githubusercontent.com/70458880/179134659-33beeb1f-8076-4c16-a107-1d10b38a35ff.png)

But while building my project, it shows an unexpected result for some reason : 
![image](https://user-images.githubusercontent.com/70458880/179135219-254d6aa7-b3be-4780-ab6e-d26b61833a97.png)

### **Is there any way to troubleshoot and get to know the source of the problem ?**




Here are some resources that may help ...

Cmake file :
![image](https://user-images.githubusercontent.com/70458880/179134957-3221514b-7b65-447d-b0fd-4dd5ec2c00c3.png)
C++ script :
![image](https://user-images.githubusercontent.com/70458880/179135006-c6df5763-f76f-4f95-a80e-de0292d1714d.png)

**Comment by paroj** [comment]
the prebuild SDK only works with MSVC. For MinGW you will still have to build Ogre yourself.
Closing as the initial CMake related error is fixed in master.
