### ISSUE TITLE
Linux TestContext failing

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2563]
commit f22949e7a2e13d7c6320de8bad63baf1a0e638ce
Linux Arch Linux
I am getting this in TestContext, could you confirm if that is happening to you ?
[saida.txt](https://github.com/OGRECave/ogre/files/9334295/saida.txt)

**Comment by paroj** [comment]
the Error is caused by GLSL that your driver (Mesa) does not like. I am on Nvidia right now, so I am currently not affected.

Try using the GL3+ rendersystem, maybe that will pass..

**Comment by Joilnen** [comment]
Unfortunately breaks in any driver, but my question here is because I sent a commit is breaking in linux test  #2564, is this related with that ?

**Comment by paroj** [comment]
no, in this log it fails due to an exception, while #2564 fails with a segfault

**Comment by paroj** [comment]
you could also try commenting out that particular test to see whether you can reproduce the CI issue:
https://github.com/OGRECave/ogre/blob/f22949e7a2e13d7c6320de8bad63baf1a0e638ce/Tests/VisualTests/PlayPen/src/PlayPenTestPlugin.cpp#L151

**Comment by Joilnen** [comment]
working and passing in linux ci tests
