### ISSUE TITLE
Blurry textures with DirectX 11

### ISSUE THREAD

**Issue by JanGeykenORGADATA** [OGRECave/ogre#2567]
#### System Information
- Ogre Version: :1.13.5
- Operating System / Platform: Windows 11 
- RenderSystem: DirectX 11

#### Detailled description
After the update from version 1.13.1 to 1.13.5 the textures are rendered blurry.
![texture_quality](https://user-images.githubusercontent.com/58724027/185413465-b755d4c1-7fc2-407b-aa1e-3443089fe6f3.png)

The problem was introduced with https://github.com/OGRECave/ogre/pull/2225

If I use TextureUnitState.setTextureMipmapBias and set the bias to -0.5 everything looks fine again

**Comment by JanGeykenORGADATA** [comment]
Thats a fair point.
But what is the best way to dissable the mipmaps and keep a good quality?

If I use TextureManager.createManual with numMipMaps = 0 I get some artifacts on the PanelOverlayElement, but its not blurry.
If I try numMipsMaps = TextureMipmap.MIP_UNLIMITED or TextureMipMap.MIP_DEFAULT I get the blurry picture from above.
The next step was testing Texture.setNumMipMaps(0) and TextureUnitState.setNumMipMaps(0), but I got no changes in the image quality.
I got a better result then I changed 
https://github.com/OGRECave/ogre/blob/3939761ab3dd96c5f083b262c45f9b22d08cd1d3/RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp#L374
to `mSRVDesc.Texture2D.MipLevels = 1;`

The best result was with the bias set to -0.5

**Comment by paroj** [comment]
> The next step was testing Texture.setNumMipMaps(0) and TextureUnitState.setNumMipMaps(0), but I got no changes in the image quality.

these must be called before you load() the texture to have any effect. But, this is the setting to disable mipmaps

> I get some artifacts on the PanelOverlayElement, but its not blurry.

can you post a screenshot? Maybe your images are of too high resolution and you used a downscaled mip level previously. Then the 0.5 mip bias might have made sense.

**Comment by JanGeykenORGADATA** [comment]
The artifacts with numMipMaps = 0 in createManual and the texture set to TU_CLAMP.
![grafik](https://user-images.githubusercontent.com/58724027/185904627-22510927-e3b8-4cf3-a90f-67447daa7491.png)
There are some additional pixels set a the bottem of the text.

I set the PanelOverlayElement to the same size as the texture.

> Maybe your images are of too high resolution and you used a downscaled mip level previously. Then the 0.5 mip bias might have made sense.

Most of the other textures have a high resolution, so I think you are right
