### ISSUE TITLE
Issue Setting up an OGRE project

### ISSUE THREAD

**Issue by body767** [OGRECave/ogre#2568]
I have installed Ogre using vcpkg as static lib
and im trying to follow the docs to set up my first project 
but everytime i try to build the project using Ninja or vs i get this error

cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/dev/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/dev/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OGRE
--   static     : ON
--   components : Bites;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;RenderSystem_Direct3D11;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : C:/dev/vcpkg/installed/x64-windows-static/Media
-- Configuring done
CMake Error at C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OgreTargets.cmake:122 (set_target_properties):
  The link interface of target "Codec_STBI" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OGREConfig.cmake:91 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package)
  CMakeLists.txt:7 (find_package)

CMake Error at C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OgreTargets.cmake:170 (set_target_properties):
  The link interface of target "Codec_Assimp" contains:

    fix::assimp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OGREConfig.cmake:91 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package)
  CMakeLists.txt:7 (find_package)

CMake Error at C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OgreTargets.cmake:178 (set_target_properties):
  The link interface of target "OgreBites" contains:

    SDL2::SDL2-static

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OGREConfig.cmake:91 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package)
  CMakeLists.txt:7 (find_package)

CMake Error at C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OgreTargets.cmake:234 (set_target_properties):
  The link interface of target "OgreOverlay" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows-static/share/ogre/OGREConfig.cmake:91 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:826 (_find_package)
  CMakeLists.txt:7 (find_package)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

Not sure what's wrong,

**Comment by paroj** [comment]
this seems to be rather an issue with vcpkg, so open an issue there. At this repo, we can only take care of issues when you build ogre yourself from source.

By the errors you posted, you probably need to add
```
find_package(ZLIB)
find_package(assimp)
```
to your project
