### ISSUE TITLE
No normalmap after commit 

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2637]
after this commit 3dc6462d64b910ca4dcfcd19f5d42bf5eddc5dbd
My models exported from blender are without normal map, before this worked fine, shouldn't necessary some shader update ?

archlinux
x86_64
master branch

**Comment by paroj** [comment]
does it work again, if you comment out the two added lines?

**Comment by Joilnen** [comment]
works ok with them commented.

**Comment by paroj** [comment]
could you provide some screenshots? before/ after

**Comment by Joilnen** [comment]
![p](https://user-images.githubusercontent.com/134140/197857347-d5967232-4aa5-44ea-9001-65aca93e838f.png)
![p1](https://user-images.githubusercontent.com/134140/197857429-9965dad0-6f0d-4f5f-adad-95650e34dbfe.png)

**Comment by paroj** [comment]
neither version seems to have a normal mapping. However, the lighting on the bottom one is definitely broken. Could you attach the exported mesh and maybe the source blend?

**Comment by Joilnen** [comment]
[station.zip](https://github.com/OGRECave/ogre/files/9864608/station.zip)

**Comment by paroj** [comment]
the material and, importantly, the textures are missing

**Comment by Joilnen** [comment]
[station.zip](https://github.com/OGRECave/ogre/files/9864876/station.zip)

**Comment by paroj** [comment]
hmm.. works for me
![screenshot_preview_20221026_171505871](https://user-images.githubusercontent.com/4941802/198066071-cdc6f02e-8742-4bcc-ae20-efd0f5358b9d.jpg)

also note the normal map effect, which is missing on your first screenshot too

**Comment by paroj** [comment]
unlikely.. it could only reject the shaders, but then rendering would be more broken.

Im attaching the mesh I exported for you to double-check 
[preview.zip](https://github.com/OGRECave/ogre/files/9871420/preview.zip)

**Comment by paroj** [comment]
yes, I used blender2ogre 0.8.3

**Comment by Joilnen** [comment]
could you to share the blend file ?

**Comment by paroj** [comment]
took another look at the mesh you initially uploaded. It lacks any tangents, which are required for normal mapping.

By default 0 is passed to the shader which causes a divide by zero in normalize and completely breaks lighting.

This is working as expected though.

**Comment by Joilnen** [comment]
ok thanks, after to turn on tangents this works now
