### ISSUE TITLE
EmscriptenSample keyboard inputs not working in fullscreen mode on Firefox

### ISSUE THREAD

**Issue by dennisferron** [OGRECave/ogre#2647]
Versions

I originally observed the issue in Ogre 13.4.3, however I just re-built Ogre from latest git master, and confirmed the issue is still present in that version (couple commits ahead of 13.5).  I don't truly know if the bug is in Ogre, Firefox, Emscripten, or SDL, but reporting it here as a starting point.

I compiled Ogre with Emscripten 3.1.22, which in turn seems to be using SDL 2.24.0.  Firefox 102.0.2 64-bit.  Chrome 106.0.5249.119.  Edge 107.0.1418.26.

Steps

I built Ogre from source using CLion configured for a Release-Emscripten build (see notes below for specifically what that means).  It built the EmscriptenSample.html, .data, .js, .wasm, files and media folder in output folder cmake-build-release-emscripten/bin.  I then started a Python webserver (ran `python3 -m http.server` in a Cmd window) in that directory, and browsed `http://localhost:8000/EmscriptenSample.html` using each browser on my Windows 10 laptop.  I used the "Fullscreen" button that is part of the "powered by emscripten" html template to switch between full screen and regular mode.

Results

In non-fullscreen mode, everything worked as expected in Firefox, Chrome, and Edge.  (Movement with ASWD, the Q and E animations, sword swing with left click, and mouse camera controls.)

In Edge and Chrome, everything also works in fullscreen mode.  However in Firefox, no keyboard inputs seem to be registered by the game sample after switching to fullscreen mode (using the Fullscreen button).  Mouse inputs are still recognized; I can move the camera and click to swing Sinbad's swords if I've already pressed Q to pull them out before going to fullscreen (but cannot pull out the swords by pressing Q after going fullscreen).  In fullscreen mode in Firefox, the only key input which has any effect is pressing Esc to exit fullscreen mode.  (Once returned to non-fullscreen mode, keyboard inputs work again.  The two modes can be cycled back and forth with the same effect or lack thereof of key input.)

Additionally, in Firefox when switching to fullscreen mode using the button, the viewable 3D area doesn't automatically fill the whole screen.  It retains the same size and position it had when non-fullscreen, now being letterboxed in black.  However if I check the "resize canvas" checkbox in the powered by emscripten html template bar, then fullscreen does take up the whole screen, in Firefox.  In Chrome and Edge, this checkbox is not needed and seems to have no effect either way (fullscreen takes up the fullscreen already on those two browsers).

The following is not important to the issue, but just being super specific on how I configured CLion for Emscripten build.  It might also be helpful for someone who wants to reproduce the issue, but didn't know before how to configure CLion to use Emscripten.

Toolchain

This is only done once per CLion install, not per-project.

Make a copy of the default (mingw) toolchain build, but the C compiler and C++ compiler get changed to:

	<somewhere>\emsdk\upstream\emscripten\emcc.bat
	<somewhere>\emsdk\upstream\emscripten\em++.bat

I'm still using the settings of bundled MinGW, bundled CMake, bundled GDB, because that's
what the tutorial said to.  (https://tech-en.netlify.app/articles/en522284/index.html)

`<somewhere>` of course being the location of your Emscripten sdk folder.  Installing Emscripten is outside the scope of these notes.  I will just say make sure you use the right Python and the Windows commandline (not Msys2 or Git Bash or Powershell) when running Emscripten's installation bat, and Cmd.exe "Run As Administrator" is needed (one time only) when running the command to permanently set path and environment variables.

CMake Profiles

Right underneath Toolchains is the CMake tab, which should be configured on each new project.  (This can also be done in the profiles pop-up window CLion gives when you first open a new project.)

Setting up a profile is required in order for a Release build option to be present in CLion's build/run options after the reload of a CMakeLists.txt.  If the configure step fails for any reason, the build option for it won't be present in the UI later.

Click the + for a new profile.  Use the following values:
Name: Release-Emscripten
Build Type: Release
Toolchain: Emscripten (what we configured in Toolchain, above)
Generator: Use default (Ninja)
CMake options: -DCMAKE_TOOLCHAIN_FILE=C:\Users\dferr\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake

**Comment by paroj** [comment]
I can reproduce this with our prebuild version: https://ogrecave.github.io/ogre/emscripten/

In Firefox it opens page-search in fullscreen, while chrome works as expected. It used to work in earlier firefox versions.

Closing this as not Ogre related. It is probably a bug in Firefox or in Emscripten/ SDL2.
