### ISSUE TITLE
Drop Frustum::OrientationMode

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#2669]
this option deals with viewport rotation for landscape/ portrait mode. However, the feature is implemented pre-projection and thus spills to user-code and touches multiple core classes. 

the same can be trivially achieved in`_convertProjectionMatrix`, like we already do with Vulkan:
https://github.com/OGRECave/ogre/blob/36cdbea7478f39be7b164a5a3d4b86e7b97a21d1/RenderSystems/Vulkan/src/OgreVulkanRenderSystem.cpp#L1240-L1241

current implementation introduced in 962f3964f0631924881dfacb4c9412ec22984345

**Comment by paroj** [comment]
@Tulon you seem to be the only user of this. What is your view?

**Comment by Tulon** [comment]
Yes, we do have `OGRE_CONFIG_ENABLE_VIEWPORT_ORIENTATIONMODE` turned on. No one on the team remembers why. I'll try turning it off and see what happens.

**Comment by Tulon** [comment]
I did a test on Android with `OGRE_CONFIG_ENABLE_VIEWPORT_ORIENTATIONMODE` set to `OFF` and I haven't noticed any behaviour or performance differences.

**Comment by Tulon** [comment]
I've made an iOS build with `OGRE_CONFIG_ENABLE_VIEWPORT_ORIENTATIONMODE=OFF` and asked our QA person to test it. Results are expected tomorrow.

**Comment by Tulon** [comment]
The QA person didn't observe any behaviour or performance differences on an iOS app built with `OGRE_CONFIG_ENABLE_VIEWPORT_ORIENTATIONMODE=OFF`. So I guess it's safe to remove.
