### ISSUE TITLE
OpenGL3Plus multi-window rendering

### ISSUE THREAD

**Issue by FillipMatthew** [OGRECave/ogre#2688]
Hi guys,
I seem to be having a problem with multi window rendering on OpenGL3Plus. This mostly looks like materials are not applied correctly to some items where for example textures will work on one window but not the other or some geometry is just black. I use render queue listeners to skip render groups depending on which viewport is currently being rendered. If I stop skipping invocations then everything renders perfectly but only on one window, the other one is blank.
This is on Ogre 13.4.4 x64 Windows.

This app was migrated from a 32bit app that used Ogre 1.12.9. It seemed fine on this version except on specific machines which I assume may just be incompatible shaders or something else unrelated.

**Comment by paroj** [comment]
try commenting out this line
https://github.com/OGRECave/ogre/blob/9dfd6c9dcdd304615d4e469e24cf130fa992af30/RenderSystems/GL3Plus/src/OgreGL3PlusStateCacheManager.cpp#L36

**Comment by FillipMatthew** [comment]
That doesn't seem to change anything. Note though that since we use vcpkg, I downloaded the same source version and built that separately and just copied the RenderSystem_GL3Plus.dll. Since the define is in the cpp I assume it doesn't affect any of the interface. I also pointed the cmake to use vcpkg for the other previously built dependencies.

**Comment by paroj** [comment]
thats strange, I found some multi-window issues that are resolved by removing this define.

Do you have the same issues when using GL (non 3+)?

**Comment by FillipMatthew** [comment]
No. GL (non 3+) and DirectX11 both work fine on Ogre 13.4.4 (x64). On Ogre 1.12.9 (x86), GL 3+, GL (non 3+) and DirectX11 all work fine.

The only strange thing is that lines with vertex colours are rendering on both windows. And it seems (visually) like the things that break are related to materials. Sometimes the alpha from the material is used but not the diffuse, other times it works fine (at least on one window anyways but some things are only supposed to render on one window). Textured triangle lists only work on one window.

Also the first thing I display is normally a texture. On the broken version the second window has a white quad instead and displaced (not centered as it should be). The position (not colour) gets resolved if I go back to that view but is initially incorrect.

If it helps at all, I don't use material scripts. As much as possible was done in code.

**Comment by paroj** [comment]
that still hints in the direction of the state cache. Can you try GL3+ 13.2.4? This is the last version before some state cache changes.

**Comment by FillipMatthew** [comment]
I'll try that on Monday, it's a bit difficult to swap Ogre versions out of our build environment at the moment.

Will this test require any code changes before building?

**Comment by FillipMatthew** [comment]
Unfortunately still no luck.
That version also caused issues loading some images outputting 'Ogre::FileNotFoundException::FileNotFoundException: Cannot locate...' type exceptions. It was also difficult to build because of build environment conflicts.

**Comment by FillipMatthew** [comment]
Is the state cache enabled by default on that version? Do I need to turn it off and how do I do that?

**Comment by paroj** [comment]
> Is the state cache enabled by default on that version? Do I need to turn it off and how do I do that?

no, in that version state cache is controlled via cmake OGRE_CONFIG_ENABLE_GL_STATE_CACHE_SUPPORT.

In later versions parts of state cache were unconditionally enabled, as I thought those were safe

**Comment by paroj** [comment]
another change in Ogre 13 GL3+ are Separate Shader Objects, which are enabled by default now. You can disable them via a RenderSystem Option.

**Comment by FillipMatthew** [comment]
That fixes it on Ogre 13.2.4.

**Comment by FillipMatthew** [comment]
I'll still test on the later version of course.
Thanks for the help.

**Comment by FillipMatthew** [comment]
On version 13.4.4 setting "Separate Shader Objects"="No" is all that was needed.

Is the "Separate Shader Objects" going to support multiple windows in future? If so at that point should I prefer to enable it or does it not really make a difference?

**Comment by paroj** [comment]
Separate Shader Objects are actually totally unrelated to multiple windows. Do you write your own GLSL shaders or are you using the RTSS?

**Comment by FillipMatthew** [comment]
Wrote my own shaders for everything.

**Comment by FillipMatthew** [comment]
[Shaders.zip](https://github.com/OGRECave/ogre/files/10218990/Shaders.zip)
Each fragment shader is paired with the vertex shader that outputs the parameters it needs.

Would there be a problem if I didn't create an input for vertex colours or texture coordinates and used that shader on an object that had that in it's buffers?

**Comment by FillipMatthew** [comment]
Does Ogre have a way to detect issues? As far as I could tell I had matched everything correctly. DirectX had issues with matching buffers and input data which is why I created the shaders I did. The OpenGL shaders are a mirror of that basically.

**Comment by paroj** [comment]
this is up to the OpenGL driver. If it generates any warnings, Ogre is already reporting that.

**Comment by FillipMatthew** [comment]
That's what's strange to me, I wasn't getting errors but the vertColour was not getting through to the fragment shader from the vertex shader. This was before I added layout(location). Adding layout(location) didn't fully fix the problem either. Intel UHD Graphics 630 OpenGL drivers seem to fail silently then? That's frustrating.

Also running this on Windows 11 on parallels has some other issues also, I had to remove the layout(position) except for input on the vertex shader and it still had an issue with getting the vertex colour to the fragment shader. These changes tested because of an error in the logs.

**Comment by FillipMatthew** [comment]
Does the order of specifying uniforms parameters relative to 'in' and/or 'out' parameters matter?
Can ignoring uniforms also cause issues relating to VS/FS matching? If so is ACT_WORLDVIEWPROJ_MATRIX already defined by Ogre? I currently pass it manually.

Sorry about all the questions, I really though I was beginning to understand the basics of shaders and render systems, now I'm not so sure what I actually understand :)

**Comment by FillipMatthew** [comment]
With SSOs can you use it in glsl330 so long as the extension is available? Or is this also dependent on the driver and possibly only available on a newer shader?
