### ISSUE TITLE
Terrain shadows problem with 6 texture layers 

### ISSUE THREAD

**Issue by CuriousMike56** [OGRECave/ogre#2706]
#### System Information
- Ogre Version: 13.6.0
- Operating System / Platform: Windows
- RenderSystem: OpenGL

#### Detailled description
With RTSS terrain, all terrains we have featuring 6 texture layers appear dark with no shadows:
```
31-heightmap.png
6
; worldSize, diffusespecular, normalheight, blendmap, blendmapmode, alpha
3.3  , 31-gravel_diffusespecular.dds , 31-gravel_normalheight.dds
6    , 31-rock_diffusespecular.dds   , 31-rock_normalheight.dds   , 31-surfaces2.png, B, 0.9
5    , 31-sand_diffusespecular.dds   , 31-sand_normalheight.dds   , 31-surfaces2.png, G, 0.9
4    , 31-grass_diffusespecular.dds  , 31-grass_normalheight.dds  , 31-surfaces1.png, G, 0.8
3    , 31-asphalt_diffusespecular.dds, 31-asphalt_normalheight.dds, 31-surfaces1.png, R, 0.95
1024 , 31-shadow_diffusespecular.dds , 31-shadow_normalheight.dds , 31-shadow.png   , R, 0.8
```
![RoR_2022-12-23_17-59-57](https://user-images.githubusercontent.com/46073351/209438147-bb034f1f-b0b4-4f8f-aa34-b8a2a3e6fd0e.png)
![RoR_2022-12-23_18-01-20](https://user-images.githubusercontent.com/46073351/209438149-a4123e26-7e00-45aa-8a34-bacf4f3704aa.png)

Issue doesn't occur after removing one layer:
![RoR_2022-12-24_08-29-39](https://user-images.githubusercontent.com/46073351/209438215-de277a11-278a-489c-b53a-dc2a84a83c6d.png)
Also tried removing a different layer instead of the bottom 'shadow' layer just to make sure:
![RoR_2022-12-23_17-57-41](https://user-images.githubusercontent.com/46073351/209438393-ace30169-ca55-4a8a-acd9-37420750f55b.png)

Another terrain with the same issue:
![RoR_2022-12-23_18-10-35](https://user-images.githubusercontent.com/46073351/209438634-041138c5-0c2e-430d-83ce-f6b1a5ef3c94.png)

#### Ogre.log (RoR.log)
[Pastebin](https://pastebin.com/raw/xYy8LwAt) (Log is too long to paste here)

**Comment by paroj** [comment]
```
08:38:47:  * Textures
08:38:47:    - Number of texture units: 16
```
however
```
6*(diffusespecular + normalheight) + 2*blendmap + globalnormal + 3*PSSM = 18
```

**Comment by tritonas00** [comment]
https://github.com/OGRECave/ogre/pull/2707 improved the situation a lot, there still dark areas though:

![screenshot_2022-12-28_13-05-10_1](https://user-images.githubusercontent.com/2660424/209802580-9e1924da-a3fd-43d3-9f6a-4fc1cf860d5d.png)

**Comment by paroj** [comment]
can you provide a renderdoc capture?

**Comment by tritonas00** [comment]
> can you provide a renderdoc capture?

https://www.dropbox.com/s/5s6mxcz1q2qt0hh/cap2.rdc?dl=1

**Comment by paroj** [comment]
could you do another capture with "Separate Shader Objects=No" in the RenderSystem settings? I think this is what breaks rendering for me when capturing on Intel.

it looks like this is what your lightmap tells to do, though:
![image](https://user-images.githubusercontent.com/4941802/209855893-bc23da9a-03e3-4883-bfee-1d7024855fe7.png)

**Comment by tritonas00** [comment]
> could you do another capture with "Separate Shader Objects=No" in the RenderSystem settings? I think this is what breaks rendering for me when capturing on Intel.

Sure: https://www.dropbox.com/s/ag2od5mksyzp7pr/cap3.rdc?dl=1

That made things worse though:

![kk](https://user-images.githubusercontent.com/2660424/209857653-fa292d9c-97b1-4f1f-b626-2370c11f1f51.png)

and a lot of spam:

```
CaelumLayeredCloudsVP/Delegate
CaelumLayeredCloudsFP/Delegate
 GLSL link result : 
error: uniform `sunDirection' declared as type `vec4' and type `vec3'
```

**Comment by tritonas00** [comment]
Tried https://github.com/OGRECave/ogre/pull/2709

Dark areas fixed it seems, but asphalt layer is missing now:

![screenshot_2022-12-28_20-59-52_1](https://user-images.githubusercontent.com/2660424/209859961-d6fa1e4d-7dc5-45ab-a786-01948e98b42d.png)

**Comment by paroj** [comment]
> That made things worse though:

it just the last few drawcalls that break it (caelum postproc or something). Actually I can see the terrain if I step before that. You could also try whether this

https://github.com/OGRECave/ogre/blob/1f9495655b6de93151fcfc934ae072c06dd1f8a8/RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp#L372

is still needed with SSO enabled on Intel.

Can you give me another renderdoc capture with #2709 applied?

**Comment by tritonas00** [comment]
> Can you give me another renderdoc capture with #2709 applied?

https://www.dropbox.com/s/tcgdoqclpgz45iu/cap4.rdc?dl=1

Disabled caelum this time. "Separate Shader Objects=No" again.

**Comment by paroj** [comment]
ah yes.. there was a -1 missing in the fix https://github.com/OGRECave/ogre/pull/2709/commits/e6e3136f38f32c05ab77b42ba7f41e8cf89abe38#

**Comment by tritonas00** [comment]
:+1: 

![screenshot_2022-12-28_22-03-50_1](https://user-images.githubusercontent.com/2660424/209866332-328f11bd-955d-4208-afa3-844c8d23f5a4.png)

![screenshot_2022-12-28_22-05-34_1](https://user-images.githubusercontent.com/2660424/209866462-9a23abf5-4161-49bf-be67-3cdece72f3ab.png)
