### ISSUE TITLE
"Plastic" look with RTSS Terrain

### ISSUE THREAD

**Issue by tritonas00** [OGRECave/ogre#2719]
We get this "plastic" look with RTSS terrain (ogre master branch):

![screenshot_2023-01-01_23-54-35_1](https://user-images.githubusercontent.com/2660424/210185749-a6d0f9cd-0b59-4df0-881e-1d372dd54c1b.png)

It should be like:

![screenshot_2023-01-01_23-58-51_1](https://user-images.githubusercontent.com/2660424/210185807-1009e90f-be91-4d27-be78-d4b38d6861d3.png)

We think its a specular issue.

[RoR.log](https://github.com/OGRECave/ogre/files/10329529/RoR.log)

Do tell if you want a RenderDoc capture.

**Comment by paroj** [comment]
I would argue that the lighting equations are correct now, whereas they were not before.

But if you add a renderdoc capture, I can take another look.

**Comment by tritonas00** [comment]
https://www.dropbox.com/s/z30bn5bxsuen1by/cap5.rdc?dl=1

Please ignore the black ground, its from caelum.

We think its not loading the specular from the image .

**Comment by paroj** [comment]
> We think its not loading the specular from the image.

thanks for the hint. It was loading specular from the image, but from the wrong channel. Another off by one: https://github.com/OGRECave/ogre/pull/2720/commits/8caa9b695fa5499c930f49e312c2eea55d0afafd

**Comment by tritonas00** [comment]
https://github.com/OGRECave/ogre/pull/2720 fixed the shininess issue we had but i can't see any difference on that map mountains:

![screenshot_2023-01-02_21-09-47_1](https://user-images.githubusercontent.com/2660424/210270766-620716e4-252a-4254-aa68-b8a11027e3b6.png)
