### ISSUE TITLE
RTSS crashes on some materials

### ISSUE THREAD

**Issue by tritonas00** [OGRECave/ogre#2721]
#### System Information
- Ogre Version: latest master
- Operating System / Platform: Arch linux
- RenderSystem: OpenGL

We get a crash with RTSS on some materials.

```
RTSS: using e7bfdf69e92ba4ff402b8e7fe1673146_FS for Pass 0 of 'semaforogris2'
InvalidParametersException: Can not resolve parameter due to type mismatch: semantic: 7, index: 0 in resolveInputParameter at /home/babis/Downloads/ror-dependencies/Source/ogre/Components/RTShaderSystem/src/OgreShaderFunction.cpp (line 309)
```

This isn't a segfault so i don't have a backtrace for it.

The material:

```
material semaforogris2: RoR/Managed_Mats/Base
{
	technique BaseTechnique
	{
		pass BaseRender
		{
         texture_unit Diffuse_Map
         {
            texture semaforogris2.png
         }
      }
   }
}
```

`RoR/Managed_Mats/Base`: https://github.com/tritonas00/rigs-of-rods/blob/ogre13/resources/managed_materials/managed_mats.material#L4-L17

#### Log
[RoR.log](https://github.com/OGRECave/ogre/files/10333796/RoR.log)

**Comment by paroj** [comment]
> This isn't a segfault so i don't have a backtrace for it.

then either set a breakpoint on that line or add a call to `abort()` to make it crash - whatever is easier for you.
Without a backtrace, there is not enough insight on what it is trying to do

**Comment by tritonas00** [comment]
> edit: also print param->getType(), type

`param->getType()` 2
`type` 3

will try `abort()` tomorrow

**Comment by paroj** [comment]
this seems to be a similar problem to
```
01:33:57: Program '5a3d802f11237fad59f29ba74c046ee4_VS' is not supported: '5a3d802f11237fad59f29ba74c046ee4_VS' 0:40(2): error: value of type vec3 cannot be assigned to variable of type vec2

01:33:57: Program 'dd5e3b5b0ef8c3f916756a83439306c3_FS' is not supported: 'dd5e3b5b0ef8c3f916756a83439306c3_FS' 0:54(12): error: no matching function for call to `texture(samplerCube, vec2)'; candidates are:

...

01:33:57: Error: RTSS: failed to create GpuPrograms for Pass 0 of 'parabus'
```

how does `parabus` look like? `semaforogris2` is probably the last successful program and not the problematic one.
Try logging the name at the start of `SGTechniqueResolverListener::handleSchemeNotFound` to find the correct one.

**Comment by tritonas00** [comment]
```
material parabus
{
	technique
	{
		pass
		{
			texture_unit
			{
				//texture parabus.png
				cubic_texture EnvironmentTexture combinedUVW
				env_map planar 
			}
		}
	}
}
```

> Try logging the name at the start of SGTechniqueResolverListener::handleSchemeNotFound to find the correct one.

You are probably right, will try that soon.

**Comment by paroj** [comment]
yeah, env_map planar is wrong for cubemaps:
https://ogrecave.github.io/ogre/api/latest/_material-_scripts.html#autotoc_md172

**Comment by tritonas00** [comment]
like

```
material semaforogris3: RoR/Managed_Mats/Base
{
	technique BaseTechnique
	{
		pass BaseRender
		{
			texture_unit Diffuse_Map
			{
                     texture semaforogris.png
			}
			texture_unit
			{
				cubic_texture EnvironmentTexture combinedUVW
				env_map planar 
			}
		}
	}
}
```

thats why it stops on `semaforogris2`.

**Comment by tritonas00** [comment]
`env_map cubic_reflection` works.

**Comment by paroj** [comment]
actually, it should not fail that hard in this case. There was code in-place, but again incomplete as it turns out..

**Comment by tritonas00** [comment]
That works also :+1:
