### ISSUE TITLE
Viewport and ImGuiOverlay issue

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2725]
this is 18acb9395d46bee1da5ca91b9ca9137e8ddceedd in linux
after I create an additional viewport this seems changes my ImGuiOverlay, is there a way to render a ogre viewport inside a imgui window ?
![vperror_00](https://user-images.githubusercontent.com/134140/210477713-27b3cea2-f876-457b-99a3-6a9326dde51d.png)
![vperror_01](https://user-images.githubusercontent.com/134140/210477702-8b20b928-8c62-4ed1-9379-7fa00bf67eb9.png)

**Comment by paroj** [comment]
do you check in your `preViewportUpdate` callback that you are targetting the main viewport?

**Comment by Joilnen** [comment]
I tried this but without success, 0 is the bigger vp 
void Polyfly::preViewportUpdate(const RenderTargetViewportEvent &evt) {    
    if(!evt.source->getOverlaysEnabled()) return;                                                           
    if (evt.source == getRenderWindow()->getViewport(0)) {                            
        ImGuiOverlay::NewFrame();                                                              
        ImGui::ShowDemoWindow();                                                                                 
    }    
    RenderTargetListener::preViewportUpdate(evt);    
}

**Comment by Joilnen** [comment]
Ok I figured it out, I need to setOverlaysEnabled(false) in smaller vp, after this worked ok
