### ISSUE TITLE
Extra shininess with RTSS Terrain

### ISSUE THREAD

**Issue by tritonas00** [OGRECave/ogre#2735]
#### System Information
- Ogre Version: latest master branch
- Operating System / Platform: Arch linux
- RenderSystem: OpenGL

#### Detailled description
Not sure if this is an issue or a feature lol. Just noticed and wanted to report. With some maps we get extra shininess. Example:

![screenshot_2023-01-10_22-42-13_1](https://user-images.githubusercontent.com/2660424/211660640-f50418f7-878e-4bac-955d-1cd2b1d13d88.png)

It used to be like:

![image](https://user-images.githubusercontent.com/2660424/211660710-21946cde-b54e-4335-af24-e3bdd8882aa8.png)

#### RoR.log
[RoR.log](https://github.com/OGRECave/ogre/files/10386761/RoR.log)

**Comment by paroj** [comment]
I would argue that the lighting equations are correct now, whereas they were not before.

But if you add a renderdoc capture, I can take another look.

**Comment by tritonas00** [comment]
https://www.dropbox.com/s/1gm77n0fzamwt70/cap6.rdc?dl=1

Again please ignore the black spots, they come from caelum and Separate Shader Objects=No setting

**Comment by paroj** [comment]
the mipmap levels of rdesv3_gravel_tex.dds have alpha set to 1 (=specularity), while the base layer has alpha = 0.
At the rendering distance, the higher mip levels get used and you get high specularity.
Dont know why it used to be wrong.

**Comment by tritonas00** [comment]
So now we get the correct behaviour?

**Comment by paroj** [comment]
yes
