### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [OGRECave/ogre#2737]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [SAFE_DELETE](https://github.com/OGRECave/ogre/blob/9dfd6c9dcdd304615d4e469e24cf130fa992af30/RenderSystems/Direct3D11/include/OgreD3D11Prerequisites.h#L55 "SAFE_DELETE macro")
- [lwEnvelope](https://github.com/OGRECave/ogre/blob/9dfd6c9dcdd304615d4e469e24cf130fa992af30/Tools/LightwaveConverter/include/lwEnvelope.h#L51 "Destructor for lwEnvelope")
- [MaterialSet](https://github.com/OGRECave/ogre/blob/9dfd6c9dcdd304615d4e469e24cf130fa992af30/Tools/MayaExport/include/materialSet.h#L42 "Destructor for MaterialSet")

**Comment by paroj** [comment]
this is a purely cosmetic issue, as compilers optimize the check away. However, if you feel like it, you can provide a PR fixing this
