### ISSUE TITLE
Bullet component collison only

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2761]
If I need to use only collision feature(no dynamics or extras), is there a way to make it from bulletOgre component, or should to patch it ?

**Comment by paroj** [comment]
OgreBullet currently only wraps DynamicsWorld, so you would need to extend it for CollisionWorld to get collision only

**Comment by Joilnen** [comment]
I started this changes, please could to help me to polish this ?  #2763

**Comment by paroj** [comment]
fixed by #2764
