### ISSUE TITLE
OgreAssimpExports.h missing!

### ISSUE THREAD

**Issue by LuchoLucho** [OGRECave/ogre#2783]
I tried to compile the AssimpConverter but it depends on OgreAssimpExports.h by :+1: 
./PlugIns/Assimp/include/OgreAssimpLoader.h:41:10: fatal error: OgreAssimpExports.h: No such file or directory
   41 | #include <OgreAssimpExports.h>

**Comment by paroj** [comment]
works fine on the CI:
https://github.com/OGRECave/ogre/actions/runs/4152508666/jobs/7183511773#step:4:2481
