### ISSUE TITLE
RenderSystem_Tiny could not be loaded on greek or turkish Windows 11

### ISSUE THREAD

**Issue by JanGeykenORGADATA** [OGRECave/ogre#2793]
#### System Information
- Ogre Version: 13.6.1
- Operating System / Platform: Windows 11
- RenderSystem: Tiny

#### Detailled description
On a greek or turkish Windows 11 RenderSystem_Tiny could not be loaded and throws the following exception

Ogre::InternalErrorException::InternalErrorException: Could not load dynamic library D:/RC12.2.8/bin/.\RenderSystem_TINY.  System Error: The specified module could not be found.
in DynLib::load at D:\THRDP-OGRE-JOB1\OgreMain\src\OgreDynLib.cpp (line 140).
The program is aborted.
The specified module could not be found

Other Rendersystems like DirectX 11 oder OpenGL3+ are loaded successfully. All Ogre dll files are in the same directory.
Then Tiny is removed from the plugins config the program runs fine.

On an english or german Windows 11 RenderSystem_Tiny could bei loaded.

Ogre was build with OGRE_CONFIG_FILESYSTEM_UNICODE = false and the C# Swig wrapper is used.

**Comment by paroj** [comment]
windows is notoriously bad about reporting dll errors.

Can you run https://www.dependencywalker.com/ on RenderSystem_TINY.dll and report whether any of its dependencies are missing?
Tiny uses SDL2 and OpenMP internally, which sets it apart from the other rendersystems.

**Comment by JanGeykenORGADATA** [comment]
OpenMP was missing on some of our testsystems.

Thank you.

I think you are not really using OpenMP in RenderSystem_TINY, at least then compiled with Visual Studio 2019. I could deactivate it in the compiler settings and I couldn't find the `#pragma omp` directives like in this example https://learn.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-170#example

**Comment by JanGeykenORGADATA** [comment]
Tinyrenderer.h doesn't show up in the Visual Studio project, thats the reasen why I didn't found it
![grafik](https://user-images.githubusercontent.com/58724027/220907491-2278af14-a9e2-4599-b66c-186c36b7dd30.png)
