### ISSUE TITLE
Exported cmake target Codec_Assimp depends on missing fix::assimp

### ISSUE THREAD

**Issue by asherikov** [OGRECave/ogre#2796]
#### System Information
- Ogre Version: 13.6.2
- Operating System / Platform: Ubuntu 20.04

#### Detailled description
Exported cmake target `Codec_Assimp` depends on missing workaroud target `fix::assimp`, which breaks compilation of applications that depend on this plugin.

Replacing `fix::assimp` with `assimp` in https://github.com/OGRECave/ogre/blob/master/PlugIns/Assimp/CMakeLists.txt#L8 just works on Ubuntu 20.04.

**Comment by paroj** [comment]
applications should not link against Codec_Assimp, as it is a plugin

**Comment by asherikov** [comment]
This is the only target that specifies include path to `OgreAssimpExports.h`:
```
set_target_properties(Codec_Assimp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/OGRE/Plugins/Assimp"
```
Without it the header cannot be found during compilation (I guess the same issue is reported in https://github.com/OGRECave/ogre/issues/2783).

**Comment by paroj** [comment]
yeah.. you should not use the header either.

```
sceneManager->createEntity("Bike.obj")
```
should be sufficient, of the plugin is loaded.

**Comment by asherikov** [comment]
The goal is to load remote resources dynamically. Using `AssimpLoader` seems to be a natural choice for loading resourses from memory after fetching, is there a better way?

**Comment by paroj** [comment]
this would be more idiomatic: https://wiki.ogre3d.org/URLArchive
