### ISSUE TITLE
Question: `OgreShaderGLSLProgramWriter.h` header is private or public? 

### ISSUE THREAD

**Issue by talregev** [OGRECave/ogre#2813]
I compile ogre 13.2.6 in vcpkg for compiling gazebo. 
I see gazebo is using this include files:
https://github.com/OGRECave/ogre/blob/v13.6.2/Components/RTShaderSystem/src/OgreShaderGLSLProgramWriter.h

They use it here:
https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/rendering/ogre_gazebo.h#LL69

This header `OgreShaderGLSLProgramWriter.h` is private or public?

I also open a issue on vcpkg to discuss it. 
https://github.com/microsoft/vcpkg/issues/30376

**Comment by paroj** [comment]
it is a private header. most likely gazebo never actually used it.

**Comment by talregev** [comment]
> it is a private header. most likely gazebo never actually used it.

Gazebo do use it.
Can you suggest other solution other then ignore me and close the issue?

**Comment by paroj** [comment]
https://github.com/gazebosim/gazebo-classic/blob/4214fda9177ed99ddbc3e48c37657a98374d685b/gazebo/rendering/CustomPSSMShadowCameraSetup.hh#L127-L129
```
    /// \brief This overrides ogre's default GLSLProgramWriter to fix
    /// a bug in ogre versions <= 1.8 where 'sampler2DShadow' sampler type
    /// is missing
```
sound like this should be #ifdefed for later Ogre versions.

**Comment by talregev** [comment]
> https://github.com/gazebosim/gazebo-classic/blob/4214fda9177ed99ddbc3e48c37657a98374d685b/gazebo/rendering/CustomPSSMShadowCameraSetup.hh#L127-L129
> 
> ```
>     /// \brief This overrides ogre's default GLSLProgramWriter to fix
>     /// a bug in ogre versions <= 1.8 where 'sampler2DShadow' sampler type
>     /// is missing
> ```
> 
> sound like this should be #ifdefed for later Ogre versions.

Maybe, but I patch this version for vcpkg that compile for latest ogre version.

**Comment by talregev** [comment]
@paroj Any reason to keep this headers as a private?

**Comment by paroj** [comment]
it eases guaranteeing a stable API
