### ISSUE TITLE
Errors compiling in Linux with clang

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2850]
#### System Information
- Ogre Version: :grey_question:  143bb610bb10d32ef12f05dac33c8388627cc540
- Operating System / Platform: :grey_question: Linux/x86_64
- RenderSystem: :grey_question: no matter

#### Detailled description
Compiling error with clang (15.0.7) compiler see output in  attached file.
Changed the indentation in *.y file doesn't solve, compiles ok with gcc

[errors.txt](https://github.com/OGRECave/ogre/files/11584694/errors.txt)

**Comment by paroj** [comment]
why did you enable `-Werror`? This is typically just a warning

**Comment by Joilnen** [comment]
I only disabled rsimage in ci-build.cmake and commented Qt from Dependences.cmake, didn't touch on compilers flags

**Comment by paroj** [comment]
you may also want to remove Werror then there as well.

ci-build.cmake is meant to build the pull-requests on the CI, hence the name.
It is not not particularly designed to be used in a different environment..

**Comment by Joilnen** [comment]
this works ok with CMakeLists.txt only with warnings messages.
