### ISSUE TITLE
OgreGLES2HardWareBuffer.cpp OGRE_EXCEPT 

### ISSUE THREAD

**Issue by liusq2114** [OGRECave/ogre#2852]
#### System Information
- Ogre Version: :grey_question: 
- Operating System / Platform: :grey_question: huawei matepad pro, hamonyOS 2.0.0
- RenderSystem: :grey_question:

#### Detailled description
glgenbuffer(1, &mbufferid); mbufferid will sometimes be 0, then run into OGRE_EXCEPT. But glerror() get no_error.
I'm sure that glthread is always the same. 
#### Ogre.log
Cannot create GL ES buffer in OgreGLES2HardWareBuffer::createBuffer at OgreGLES2HardWareBuffer.cpp (line 55)

**Comment by paroj** [comment]
have you tried compiling with this set to 1?
https://github.com/OGRECave/ogre/blob/2940ada3570bc4fc66863a7e2e0342e9a95a2e63/RenderSystems/GLES2/include/OgreGLES2Prerequisites.h#L92

**Comment by liusq2114** [comment]
> 

yeal, I have already tried, but glgeterror() return 0.

**Comment by paroj** [comment]
then this is a driver issue on your device.

glGenBuffers should never fail the way you are observing. Please report to Huawei - there is not much we can do about this on the Ogre side.
