### ISSUE TITLE
Unexpected result with automatic instancing 

### ISSUE THREAD

**Issue by stefanroellin** [OGRECave/ogre#2857]
#### System Information
- Ogre Version: 13.6.1
- RenderSystem: OpenGL 3+ Rendering Subsystem

#### Detailed description
The automatic instancing reduces the batch count in my application significantly. However, I observe a strange effect: the involved objects sometime vanish when the camera is slightly moved, despite the objects should still be visible. Without automatic instancing, this never happens.

#### Example

**Correct**:

![image](https://github.com/OGRECave/ogre/assets/9341235/62884bf9-f92a-4398-8414-49575165f960)

**Wrong**, the "triangles" in dark gray vanish, but should still be visible:

![image](https://github.com/OGRECave/ogre/assets/9341235/5a9e9691-8c99-405b-944c-21344707b04e)

**Comment by paroj** [comment]
it is hard to tell what is going wrong here. A quick glance at the code did not show any obvious errors and I could not reproduce this behavior with the instancing sample.
You could maybe check with renderdoc whether the triangels are not rendered at all (culled by Ogre) or whether they are rendered but not visible (wrong transform/ culled by OpenGL).

**Comment by stefanroellin** [comment]
Thanks for the hint to check with renderdoc. I will give it a try and see if I can isolate the problem.
The objects use a hierarchy of scene nodes, with scalings, rotations and translations. Could this be part of the problem?

**Comment by paroj** [comment]
no the transforms are derived in the same way regardless of whether instancing is used.

**Comment by stefanroellin** [comment]
I couldn't reproduce the problem anymore and therefore I will close this issue. Nevertheless thanks for the help!
