### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dzylikecode** [OGRECave/ogre#2911]
#### System Information
- Ogre Version: 14.0.1
- Operating System / Platform: windows
- RenderSystem: :grey_question:

#### Detailed description

Here is my folder tree.

![image](https://github.com/OGRECave/ogre/assets/71511961/51562543-ce97-42bc-a1a3-2ac060a126e6)

Here is the content of CMakeLists.txt put under the `3rd_party`

![image](https://github.com/OGRECave/ogre/assets/71511961/0f916fda-932b-4a2d-8566-83ce001c053c)

The error occurs when I build the project.

![image](https://github.com/OGRECave/ogre/assets/71511961/c95df455-995e-410a-bf0a-2af577804bf0)

I thought I couldn't directly copy the `Media` to the `/build/3rd_party/ogre/Media`, but I tried. Another error happens:

![image](https://github.com/OGRECave/ogre/assets/71511961/486c9b02-9d4e-440c-9edd-7eb0807276c7)

## Addition

I have used `vcpkg` to install the package. However, it always reports an error in the picture below when I run the sample code. I tried to install `x64-windows-static` to bypass this error, another error about building is waiting for me. I have no idea to solve it

![image](https://github.com/OGRECave/ogre/assets/71511961/e2796608-f004-48aa-a8d0-ddb8d0e65860)

```cpp
// This file is part of the OGRE project.
// It is subject to the license terms in the LICENSE file found in the top-level
// directory of this distribution and at https://www.ogre3d.org/licensing.
// SPDX-License-Identifier: MIT

#include "Ogre.h"
#include "OgreApplicationContext.h"

//! [key_handler]
class KeyHandler : public OgreBites::InputListener {
  bool keyPressed(const OgreBites::KeyboardEvent& evt) override {
    if (evt.keysym.sym == OgreBites::SDLK_ESCAPE) {
      Ogre::Root::getSingleton().queueEndRendering();
    }
    return true;
  }
};
//! [key_handler]

int main(int argc, char* argv[]) {
  //! [constructor]
  OgreBites::ApplicationContext ctx("OgreTutorialApp");
  ctx.initApp();
  //! [constructor]

  //! [setup]
  // get a pointer to the already created root
  Ogre::Root* root = ctx.getRoot();
  Ogre::SceneManager* scnMgr = root->createSceneManager();

  // register our scene with the RTSS
  Ogre::RTShader::ShaderGenerator* shadergen =
      Ogre::RTShader::ShaderGenerator::getSingletonPtr();
  shadergen->addSceneManager(scnMgr);

  // without light we would just get a black screen
  Ogre::Light* light = scnMgr->createLight("MainLight");
  Ogre::SceneNode* lightNode =
      scnMgr->getRootSceneNode()->createChildSceneNode();
  lightNode->setPosition(0, 10, 15);
  lightNode->attachObject(light);

  // also need to tell where we are
  Ogre::SceneNode* camNode = scnMgr->getRootSceneNode()->createChildSceneNode();
  camNode->setPosition(0, 0, 15);
  camNode->lookAt(Ogre::Vector3(0, 0, -1), Ogre::Node::TS_PARENT);

  // create the camera
  Ogre::Camera* cam = scnMgr->createCamera("myCam");
  cam->setNearClipDistance(5);  // specific to this sample
  cam->setAutoAspectRatio(true);
  camNode->attachObject(cam);

  // and tell it to render into the main window
  ctx.getRenderWindow()->addViewport(cam);

  // finally something to render
  Ogre::Entity* ent = scnMgr->createEntity("Sinbad.mesh");
  Ogre::SceneNode* node = scnMgr->getRootSceneNode()->createChildSceneNode();
  node->attachObject(ent);
  //! [setup]

  //! [main]
  // register for input events
  KeyHandler keyHandler;
  ctx.addInputListener(&keyHandler);

  ctx.getRoot()->startRendering();
  ctx.closeApp();
  //! [main]
  return 0;
}
```

**Comment by paroj** [comment]
you must build ogre as described here:
https://ogrecave.github.io/ogre/api/latest/building-ogre.html

add_subdirectory wont do

**Comment by dzylikecode** [comment]
Can you help me with the `addition` part? I prefer using `vcpkg` to install it, but the plugin `Plugin_DotScene` can't be loaded when   running the `Bootstrap.cpp`
