### ISSUE TITLE
Unable to load the plugin `Plugin_DotScene` and `Codec_Assimp`

### ISSUE THREAD

**Issue by dzylikecode** [OGRECave/ogre#2916]
https://github.com/microsoft/vcpkg/issues/33111

**Comment by paroj** [comment]
could be an instance of #1303. Does a release build work?

If not, you should provide the actual message of the exception you get.

**Comment by dzylikecode** [comment]
no, the same error occurs in the release version that the specified module could not be found (`GetLastError() == 126`). `Plugin_DotScene` and `Codec_Assimp` both throw the exception. 

```txt
Error occurred during execution: Ogre::InternalErrorException::InternalErrorException: Could not load dynamic library C:/Users/Z/Desktop/Dz/fishing/game-3D-tutorial-env/config/../build/vcpkg_installed/x64-windows/plugins/ogre\Plugin_DotScene # can't work.  System Error: The specified module could not be found.
```

It works well if not using them.

**Comment by paroj** [comment]
its different then. Run depends (https://www.dependencywalker.com/) on the failing plugins and check whether they find their dependencies (e.g. DotScene needs pugixml)

**Comment by dzylikecode** [comment]
`DotScene` can find the dependencies except the DLLs beginning with `API-MS-WIN` or `EXT-MS-WIN` which other plugins working well can't find too. 

![image](https://github.com/OGRECave/ogre/assets/71511961/d5464efb-6df0-4445-b93a-15d1d46748d2)

**Comment by paroj** [comment]
no idea then. But our own SDK does work? (SampleBrowser starts) https://dl.cloudsmith.io/public/ogrecave/ogre/raw/versions/v14.0.1/ogre-sdk-v14.0.1-msvc142-x64.zip

**Comment by dzylikecode** [comment]
Yes, `SampleBrowser` starts up fine, but it seems not to contain two samples in the folder `tutorial`. I'm not sure whether it starts with the plugin `Dot Scene`

**Comment by paroj** [comment]
yes, the plugins are loaded. You can check the log. This is something on the vcpkg side then that they should debug.

**Comment by dzylikecode** [comment]
could you tell me where is the log?

**Comment by paroj** [comment]
Documents/OGRE Sample Browser/

**Comment by dzylikecode** [comment]
I have searched for a long time but failed to find >_<

![image](https://github.com/OGRECave/ogre/assets/71511961/c68e8e19-2bca-4841-bef5-2ea3d6d49475)

A wired thing is that I use the OGRE installed by `Vcpkg` and then set the environment variable `OGRE_CONFIG_DIR=/path/to/SDK/bin`. I think all will be fine because `Sample Browser` starts up fine with the plugin. But `Codec_STBI`, `Plugin_DotScene`, and `Codec_Assimp` can't work again.

**Comment by paroj** [comment]
its in your user Documents folder. C:\Users\%USERPROFILE%\Documents or something

**Comment by dzylikecode** [comment]
thanks
