### ISSUE TITLE
Logic error in WorkQueue?

### ISSUE THREAD

**Issue by lpea** [OGRECave/ogre#2935]
#### System Information
- Ogre Version: v14.0.1
- Operating System / Platform: Fedora 38
- RenderSystem: OpenGL 3+

#### Detailled description

Hi!

I've been investigating [this issue](https://forums.ogre3d.org/viewtopic.php?t=97107) with forum user **bro** and given the results of the git bisect we've looked more thoroughly at the code. In particular, the logic in `DefaultWorkQueueBase::processMainThreadTasks()` seems a bit odd. The code of the main loop can be simplified as follows:

```c++
        // keep going until we run out of responses or out of time
        while(true)
        {
            if(!mMainThreadTasks.empty())
            {
                std::function<void()> task = mMainThreadTasks.pop_front();
                task();
            }

            // time limit
            if (getCurrentTime() - msStart > mResposeTimeLimitMS)
                break;
        }
```

Written like this, when the task list becomes empty the loop is not exited until the timeout occurs. And even if the task list is empty when `processMainThreadTasks()` is called, the while loop is entered and spins until the timeout is reached.

I think it should be rewritten as follows:

```c++
        // keep going until we run out of responses or out of time
        while(!mMainThreadTasks.empty())
        {
            std::function<void()> task = mMainThreadTasks.pop_front();
            task();

            // time limit
            if (getCurrentTime() - msStart > mResposeTimeLimitMS)
                break;
        }
```

I've attached a proper patch that is compatible with v14.0.1 and can open a pull request if it is considered relevant.

I've tested it on my system and got equivalent performance to v13.6.2.

[commit-5076381.txt](https://github.com/OGRECave/ogre/files/12534907/commit-5076381.txt)

**Comment by paroj** [comment]
yes, please open a pull request
