### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for OGRE

### ISSUE THREAD

**Issue by wangyuliu** [OGRECave/ogre#2939]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, it can be estimated on average across various architectures.My focus is on the overall workload and difficulty of transplantation in the past and future.As part of my dataset, I have collected the OGRE project. I would like to gather community opinions to support my assessment. I appreciate your help and response! Based on scanning tools, the porting complexity is determined to be moderate leaning simple, with a small amount of code related to the CPU architecture in the project. What kind of developer configuration or team setup do you think is needed, and how much time will it take? (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.

**Comment by paroj** [comment]
it already works on RISCV:
https://packages.debian.org/sid/libogre1.12.10#pdownload

**Comment by wangyuliu** [comment]
> it already works on RISCV: https://packages.debian.org/sid/libogre1.12.10#pdownload

So which part do you think the actual workload of the transplant process falls into: easy, medium, or difficult? Looking forward to your answers. Our tool counts that there are many intrinsic functions in OGRE, so it is evaluated as medium leaning to simple. Do you think this is correct?
