### ISSUE TITLE
Vulkan Crashs

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2942]
Vulkan plugin render crashs in intel, x86, compiled with clang++, commit  3f0a656c7065f4167ad4d9d5fcbfbe6baa569aee

--- output message

Finished parsing scripts for resource group Essential
Creating resources for group Essential
All done
Texture 'sdk_bands.png': Loading 1 faces(PF_A8B8G8R8,2x32x1) with 5 generated mipmaps from Image. Internal format is PF_A8B8G8R8,2x32x1.
Loading shader cache from '/home/joilnen/.cache/OGRE Sample Browser/cache.bin'
Parsing scripts for resource group BSPWorld
An exception has occurred: ItemIdentityException: No program writer for language null in getProgramWriter at /home/joilnen/ogre3d_devel/ogre3d-14.1.x/Components/RTShaderSystem/include/OgreShaderProgramWriterManager.h (line 65)

**Comment by paroj** [comment]
you also need the GLSLang plugin

**Comment by Joilnen** [comment]
good it runs but full of flicking, probably need more polish ?

**Comment by paroj** [comment]
runs fine here on nvidia and amdgpu. Please open a new issue with a screenshot of the "flicking"
