### ISSUE TITLE
Font alpha compositing creates dark artefacts

### ISSUE THREAD

**Issue by corentinjaffre** [OGRECave/ogre#2950]
- Ogre Version: 13.3.1
- Operating System / Platform: windows
- RenderSystem: dx9c

When displaying white fonts on a white background, I can see dark edges where transparent pixels (from the AA) are.

My fontDef files are like this:
```
font myFont
{
     type truetype
     source myFont.ttf
     size 64
     resolution 72
     code_points 33-255
} 
```
Those are screenshots of the issues, which I reproduce with any fonts:

![font01](https://github.com/OGRECave/ogre/assets/6184263/06c70168-51ab-4ace-aeed-335443c1d416)

![font02](https://github.com/OGRECave/ogre/assets/6184263/f547648d-ba70-47bc-b0be-7bf82553bb27)

Could this be some premult issue?

**Comment by paroj** [comment]
can you also post the material that you are using?

**Comment by paroj** [comment]
ok, initially I thought this to be a mipmapping issue, but actually the Font material is set up by Ogre correctly.

It is still a filtering issue though. The correct solution is to use premult alpha for the font texture. Will have to wait to 14.2 for this.

> By the way, how can I use my own material for font rendering?

there is Font::_setMaterial. Check Font::loadImpl() for how to set it up.

**Comment by corentinjaffre** [comment]
Thanks!

**Comment by paroj** [comment]
setting "antialias_colour true" in 14.1.1 will fix this.

will make it the new default and deprecate "antialias_colour" in 14.2
