### ISSUE TITLE
AssimpLoader usage example?

### ISSUE THREAD

**Issue by ggslayer** [OGRECave/ogre#2951]
Hi, I am newer for ogre,  I want to load fbx and render animation in fbx using orge, I found there is a assimp plugin and a class named AssimpLoader， but after some attempts, I can't load the fbx file correctly(I don't know the mesh source, I give it null, then carsh.. ),  So, I want some help about:

1. how to load fbx in ogre?
2. how to render animation in fbx file? 

Is there some example code for this?  or  give me some archive this's direction advice?  thank you  very much !

**Comment by paroj** [comment]
https://www.ogre3d.org/2020/09/20/ogre-1-12-9-released#ogre-assimp-plugin

**Comment by ggslayer** [comment]
thank you for your reply in time, I will view it in detail

**Comment by ggslayer** [comment]
load fbx succeed, I will try hard on animation later, thankyou

**Comment by ggslayer** [comment]
Hi, after test, I occurs some problems with fbx downloaded from mixamo, 
first is a warning: "Warning: the mesh 'dance.fbx' includes vertices with more than 4 bone assignments. The lowest weighted assignments beyond this limit have been removed, so your animation may look slightly different. To eliminate this, reduce the number of bone assignments per vertex on your mesh to 4."

after that, the program exit with exception:   "Error occurred during execution: vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)"

some other fbx model can load(warning exist) ok with no crash, but crash only on mixamo's fbx.

Is there any methods to resolve this warning and crash?  thank you    @paroj

**Comment by paroj** [comment]
can you upload the faulty fbx here?

**Comment by ggslayer** [comment]
the file link:  https://github.com/ggslayer/codebase/releases/download/fbx/dance.fbx

**Comment by paroj** [comment]
the fbx loads fine with meshviewer:
![grafik](https://github.com/OGRECave/ogre/assets/4941802/db1f5488-44fe-4e94-a4a2-91d4fed43daf)

so that is likely an issue on your end.

However, the animation is currently broken. Likely due to the issue discussed here:
https://forums.ogre3d.org/viewtopic.php?p=555083#p555083

**Comment by ggslayer** [comment]
Thank you, I will review my code, reference meshviewer.

**Comment by ggslayer** [comment]
Hi, I install ogre-meshveiwer on ubuntu by ''sudo snap install ogre-meshviewer", after that,  I run: 'ogre-meshviewer /<fullpath>/dance.fbx' , start first time,  the ui popup, and I select gl3+ render, then the program crash, after that, when I run meshviewer again, ui not popup again, and crash with segment error directly.   Do you have some idea about this situation? can you give me some advice?   @paroj
