### ISSUE TITLE
newer questions

### ISSUE THREAD

**Issue by ggslayer** [OGRECave/ogre#2952]
Hi, I'm newer for ogre and render,  I have some primary problem about ogre  after some Tutorials,  Can you give me want some help about these problems:
1. I want load plugins manually, but default behavior is load all plugins in dir,   how to loadd plugins manually?
2. The tutorials show a windows as render target,  Can I make a memory texture as the render target? 

thank you very much for give me some advices for my questions

**Comment by ggslayer** [comment]
In my scene, I want run ogre as a service, which render fbx, and get fbx animation's per frame's rgba image, output to video, So, I want a memory serface as a rendertarget, can you give me some advice on my purpose?

**Comment by chillywillysoft** [comment]
ggslayer, search the [OGRE forums](https://forums.ogre3d.org/). Your question has probably been asked before. If not, you can ask there and your question will get much more visibility than here.
