### ISSUE TITLE
throw std::bad_cast substitution in OgreAny.h provides no error details

### ISSUE THREAD

**Issue by danielsefton** [OGRECave/ogre#2969]
#### System Information
- Ogre Version: 13.6.5
- Operating System / Platform: iOS 15
- RenderSystem: GLES 2

#### Detailed description
I am in the process of upgrading from Ogre v1.8 to v13.6.5 using GLES 2 and the RTSS running on iOS.

While trying to debug an issue with parsing material scripts, I noticed that the exception thrown provided no details on the source of the problem. It looks like this:

```
Parsing script MyMat.material
STL UNHANDLED EXCEPTION: std::bad_cast
```

I saw that the original OGRE_EXCEPT with useful information had been removed in v1.12.0:

[Main: Any - throw std::bad_cast instead of InvalidParametersException](https://github.com/OGRECave/ogre/commit/017025859205be744981ef92a39d3e1ec4776400)

Is there any reason for that? If I re-add it (along with adding more try/catches around the internal material script parsing) I get useful information that would have saved me a lot of time:

```
Parsing script MyMat.material
[TechniqueTranslator::translate] InvalidParametersException: Bad cast from type 'PN4Ogre8MaterialE' to 'PN4Ogre8MaterialE' in Ogre::any_cast at OgreMain/include/OgreAny.h (line 463)
[ScriptTranslator::processNode] InvalidParametersException: Bad cast from type 'void' to 'PN4Ogre9TechniqueE' in Ogre::any_cast at OgreMain/include/OgreAny.h (line 463)
```

(Separately, I have asked about the parsing errors in the [glitter.im](https://app.gitter.im/#/room/#OGRECave_ogre:gitter.im) channel)

Here is my proposed solution. Let me know if you agree and I will see about creating a PR:

`OgreAny.h`
```
#include <typeinfo>
#include <string>
#include <sstream>
#include <stdexcept>
#include <cxxabi.h>

class DetailedBadCast : public std::bad_cast {
private:
    std::string message;

    static std::string demangle(const char* mangledName) {
#ifdef HAS_CXA_DEMANGLE
        int status;
        char* demangled = abi::__cxa_demangle(mangledName, nullptr, nullptr, &status);
        std::string result = (status == 0 ? demangled : mangledName);
        free(demangled);
        return result;
#else
        return mangledName;
#endif
    }

public:
    DetailedBadCast(const std::type_info& sourceType, const std::type_info& targetType) {
        std::ostringstream str;
        str << "Bad cast from type '" << demangle(sourceType.name()) << "' "
        << "to '" << demangle(targetType.name()) << "'";
        message = str.str();
    }

    virtual const char* what() const noexcept override {
        return message.c_str();
    }
};

template<typename ValueType>
ValueType any_cast(const Any & operand)
{
    const ValueType * result = any_cast<ValueType>(&operand);
    if (!result) {
        throw DetailedBadCast(operand.type(), typeid(ValueType));
    }
    return *result;
}
```

This provides full demangled insight into what failed in the cast. Example output:

```
Bad cast from type 'void' to 'Ogre::Technique*'
```

It would be even more helpful to include `__FILE__`, `__FUNCTION__` and `__LINE__`. However, this would need a macro, so maybe it's going a bit too far.

**Comment by paroj** [comment]
> I saw that the original OGRE_EXCEPT with useful information had been removed in v1.12.0:

as the commit message says, it was done for compatibility with std::any, which we plan to use in the future. At that point, we wont be able to throw the proposed `DetailedBadCast` any more either. So while I see your point I dont think it is worth the work.

> [TechniqueTranslator::translate] InvalidParametersException: Bad cast from type 'PN4Ogre8MaterialE' to 'PN4Ogre8MaterialE' in Ogre::any_cast at OgreMain/include/OgreAny.h (line 463)

it basically says it cant cast Ogre::Material to Ogre::Material. I guess this is the same issue as #2907.

Take a look on the open discussion https://github.com/OGRECave/ogre/pull/2907#discussion_r1284333719

**Comment by danielsefton** [comment]
Thank you for the reply. I overlooked the pending PRs, my bad.

It seems that the pull request https://github.com/OGRECave/ogre/pull/2907 resolves my issue. There are no more errors and my game is now loading.

I see that you are not keen on merging it into the codebase, and you mentioned that something might be wrong on our side? I am also using the static library. I wonder what we are both doing wrong. I am working with a stable codebase of a previously in-production game. I will reply again if I figure anything out.

Fair enough regarding the future use of std::any, thanks for clarifying.
