### ISSUE TITLE
Compile error when glslang comonent on in linux 

### ISSUE THREAD

**Issue by Joilnen** [OGRECave/ogre#2980]
Getting compile error in fa4b4bc4df1e6f07fb68212cfde1e1b8a3b6b65d
Errors message attached here
[err_gcc.txt](https://github.com/OGRECave/ogre/files/13506299/err_gcc.txt)
[err_clang.txt](https://github.com/OGRECave/ogre/files/13506300/err_clang.txt)

**Comment by paroj** [comment]
change introduced in glslang 12.1/ vulkan sdk vulkan-sdk-1.3.268.0

**Comment by Joilnen** [comment]
yes that works, would not be the time to ogre to me to C++17 ?

**Comment by susnux** [comment]
Starting with GLSLANG 14 the ogre plugin is completely broken as it uses private types that are not exported / provided anymore (TType is now only a forward declared class).
