### ISSUE TITLE
Can't get metalness to work

### ISSUE THREAD

**Issue by snowPu** [OGRECave/ogre#2982]
I have the following material
```
material Material2
{
    technique
    {
        pass
        {
        specular 1.0 1.0 1.0 1.0 200.0
        rtshader_system
        {
           lighting_stage metal_roughness
        }
        diffuse 0.2 0.2 0.2 1.0
        }
    }
}
```

```
auto baseMaterial = Ogre::MaterialManager::getSingleton().getByName("Material2", nameOfResourceGroup);
entity->setMaterial(baseMaterial);
```
I know that the material gets loaded properly as the diffuse property works. However I can't see any change in appearance with the metal roughness properties. 

I have a directional light in the scene created by the following code:
```
Ogre::Light* light = sceneManager->createLight("MainLight");
    light->setCastShadows(true);
    light->setType(Ogre::Light::LT_DIRECTIONAL);
    light->setDiffuseColour(Ogre::ColourValue::White);
    Ogre::SceneNode* lightNode = this->cameraNode_->createChildSceneNode();
    lightNode->attachObject(light);
```

**Comment by paroj** [comment]
did you see the parameter mapping of specular here: https://ogrecave.github.io/ogre/api/latest/rtss.html#autotoc_md255 ?

as you set roughness=1.0, your material should be just slightly darker compared to blinn phong.

Also verify that the RTSS is active for your viewport (in case you are on D3D9 or GL1)

**Comment by snowPu** [comment]
1. What should I check for in parameter mapping exactly? This is what it says:
`By default, roughness is read from specular[0] and metalness from specular[1].`

2. `Also verify that the RTSS is active for your viewport (in case you are on D3D9 or GL1) -- `
how do I check this?

3. I wanted to post this ogre forum but my gmail id isn't being accepted for registration. I keep getting this:
```
verification mail delivery to gmail currently broken
The solution you provided was incorrect
```

**Comment by paroj** [comment]
> What should I check for in parameter mapping exactly?

your specular[0] and specular[1] values, which are both 1.0 as you posted above

> how do I check this?

you should a snippet like this in your code:
https://github.com/OGRECave/ogre/blob/2b1864e2ec97b61b0c273e8d56ae9646bea6ea4e/Samples/Simple/include/PBR.h#L42-L43

> I wanted to post this ogre forum but my gmail id isn't being accepted for registration. I keep getting this:

gmail just does not work. we are aware of this #2924

**Comment by paroj** [comment]
you must explicitly clone the RTSS parts, see:
https://github.com/OGRECave/ogre/blob/4acf4891a3bb1bcd38d067af98dbd495d4bd66b6/Tests/VisualTests/PlayPen/src/PlayPenTests.cpp#L6977-L6981
