### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [OGRECave/ogre#3004]
Would you like to add more error handling for return values from functions like the following?
* [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [MaterialSerializer::exportQueued](https://github.com/OGRECave/ogre/blob/7548e058a5c396951362f3df696fb1d6d9d70556/OgreMain/src/OgreMaterialSerializer.cpp#L80)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [_findfirst](https://github.com/OGRECave/ogre/blob/ee5fd3b21f93101c5d5fe6bf0fa837ad70131c0a/OgreMain/src/OgreSearchOps.cpp#L62)
* [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [nvparse](https://github.com/OGRECave/ogre/blob/7548e058a5c396951362f3df696fb1d6d9d70556/RenderSystems/GL/src/nvparse/nvparse.cpp#L85)

**Comment by paroj** [comment]
no

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by paroj** [comment]
- "Clang Static Analyzer" is manually run from time to time, which seems sufficient
- I do not think "Aspect-oriented programming" would be beneficial for the project

**Comment by elfring** [comment]
The current source code analysis status is still questionable, isn't it? :thinking:

**Comment by paroj** [comment]
why do you think it is?

**Comment by elfring** [comment]
Some tools can point remaining open issues out.

Another example:
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_43 "Avoiding undefined behaviour?")?

**Comment by paroj** [comment]
having zero reports in any static code analyzer is not a design goal.

However, if someone wants to improve e.g. MISRA C++ conformance, we can discuss it on a case by case basis.
But again, I will not actively work towards this myself.
