### ISSUE TITLE
Issue render with Ogre3D and Pure OpenGL (QOpenGLWidget) in 2 separete QWidget within a Qt Application

### ISSUE THREAD

**Issue by khuong-nv** [OGRECave/ogre#3007]
#### System Information
- Ogre Version: v1.12.10
- Operating System / Platform: Ubuntu 22.04
- RenderSystem: OpenGL

#### Detailled description
I am encourerting a significant rendering problem when using Ogre3D and pure opengl (QOpenGLWidget) simultaneously on 2 separate QWidget withing a single Qt application. 
Steps to reproduct:
1. Crate a Qt application with at least two widgets
2. Integrate Ogre3D on one widget and QOpenGLWidget on another.
3. Attempt to render context on both widgets simultaneously.

The render process on QOpenGLWidget is too lag.
Please let me know if any further details or clarification is needed to address and resolve this rendering issue

**Comment by paroj** [comment]
not an Ogre issue. Qt integration can be discussed here: https://forums.ogre3d.org/viewtopic.php?p=555627#p555627
