### ISSUE TITLE
Problem with anti-aliasing and render to texture

### ISSUE THREAD

**Issue by lpea** [OGRECave/ogre#3015]
#### System Information
- Ogre Version: 14.0.1
- Operating System / Platform: Linux Fedora 35 & 39
- RenderSystem: OpenGL 3+ Rendering Subsystem

#### Detailled description

Hi! I'm trying to use Ogre to get multiple views of a scene and process the resulting images with OpenCV. Here's the setup:
* Create a scene with a mesh inside
* Create multiple cameras looking at the object
* Make the cameras render to separate textures
* When the rendering is done, loop over the textures, lock the buffers and copy to a cv::Mat
* Process / display the result with OpenCV.

It works fine as long as the texture is created with fsaa = 0, but when I set it to a non-zero value I get this weird behavior where the buffers of all the cameras appear to contain the same data. If I set a different FSAA level or buffer size to all cameras then the behavior will be correct.

With FSAA = 0 (no antialiasing, textures are correct):

![ogre_cameras_fsaa_0](https://github.com/OGRECave/ogre/assets/4275716/7b67e7c1-deef-4c9b-9ce1-0cb37162f23b)

With FSAA = 4 (antialiasing works but all textures contain the same data):

![ogre_cameras_fsaa_4](https://github.com/OGRECave/ogre/assets/4275716/9cbd27cd-ea8d-4b2f-ba56-aebf29c84d7a)

So it could be summarized as follows: cameras rendering to textures of the same size and same FSAA level seem to share the same data (which appears to be that of the last rendered texture).

#### Ogre.log

[ogre.log](https://github.com/OGRECave/ogre/files/14054402/ogre.log)

Sample code: 

[camera.tar.gz](https://github.com/OGRECave/ogre/files/14054406/camera.tar.gz)

Change the `fsaa` value on line 121 to either zero or a non-zero value to get the behavior described above.

Maybe my understanding of how Ogre works is wrong and I made a mistake somewhere?

Thanks in advance

**Comment by paroj** [comment]
you should also call `renderer->update(); (RenderTarget::update)`. For simplicity also switch to `RenderTarget::setAutoUpdated(false)`

**Comment by paroj** [comment]
thanks for the nice reproducer btw

**Comment by lpea** [comment]
Hi paroj, thank you so much for the quick reply and answer, it works perfectly with `renderer->update()`! I'm still new to the many concepts using in Ogre and the API.

Cheers

BTW I tried to register on the forum a few days ago but couldn't because of the gmail issue, unfortunately.
