### ISSUE TITLE
[BUG Report] Is SAFE_DELETE modified erroneously?

### ISSUE THREAD

**Issue by walker-WSH** [OGRECave/ogre#3048]
Hi,  I find `SAFE_DELETE` is changed in this commit 
https://github.com/OGRECave/ogre/commit/ee5fd3b21f93101c5d5fe6bf0fa837ad70131c0a
![1709178080](https://github.com/OGRECave/ogre/assets/18413354/d0fda6e8-9764-4c2b-900f-8f2d66cc6c0b)

Should `"delete p"` be removed ?  
This causes below variables can't be destroied normally since they are not managed by smart pointer ~

![1709177916](https://github.com/OGRECave/ogre/assets/18413354/78b30d20-fb82-47be-b644-e40895b0628f)

By the way, this commit has been included in `14.2` while not in `14.1.2`

**Comment by paroj** [comment]
yes, this was an overlook when merging. Thanks for reporting! Reverting..
