### ISSUE TITLE
[Crash Report] overflow access in D3D11HLSLProgram::buildConstantDefinitions()

### ISSUE THREAD

**Issue by walker-WSH** [OGRECave/ogre#3050]
Hi, I am building SampleBrowser with tag14.2.0.
When I startup this sample, overflow access to vector in `D3D11HLSLProgram::buildConstantDefinitions()` always appear.

I checked tag14.1.2,  crash also happen in this class.
If you need more information, please tell me.

![1709264003](https://github.com/OGRECave/ogre/assets/18413354/18cd6e0c-4677-490a-abed-104a6f059975)
![1709264071](https://github.com/OGRECave/ogre/assets/18413354/82c2e88d-707e-4bc4-bf26-fbc61185487e)

**Comment by paroj** [comment]
cannot reproduce.

change the line to
```cpp
if (mVarDescPointer.at(pointerCount-1).uFlags & D3D_SVF_USED)
````
in a relwithdebinfo build, but no exception was thrown.

Do you have any other changes to the source code? Can you provide the ogre.log?

**Comment by walker-WSH** [comment]
hi @paroj     
sorry, it's my fault.  this crash is caused by failture of preparing dependency libs

so I close it.
thanks~
