### ISSUE TITLE
ImGUI is no longer optional for OGRE Bites.

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre#3070]
It seems that this commit: https://github.com/OGRECave/ogre/commit/06e4b63b38077d0d6e06b24c1eceb75fc6c1fb34 made ImGUI a requirement for building with OGRE Bites.

I don't understand what is the purpose of the option: `DOGRE_BITES_NATIVE_DIALOG`

I thought that with this option set to `True` we would be using platform specific config dialogs instead of the platform agnostic ImGUI.

The SampleBrowser is also dependent on ImGUI.

**Comment by paroj** [comment]
OGRE_BITES_NATIVE_DIALOG is meant to disable the platform specific dependencies, if you switch to imgui.

the rest is a lack of testing on my side and should be fixed soon
