### ISSUE TITLE
`OgreMeshUpgrader` and `OgreXMLConverter` have empty time in log

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre#3078]
This is the log from `OgreMeshUpgrader` from OGRE v13.6.5
```
22:00:00: MeshSerializer writing mesh data to stream D:\tmp\VertexOptTest\Plane.mesh...
22:00:00: File header written.
22:00:00: Writing mesh data...
22:00:00: Writing submesh...
22:00:00: Exporting submesh texture aliases...
22:00:00: Submesh texture aliases exported.
22:00:00: Submesh exported.
22:00:00: Exporting bounds information....
22:00:00: Bounds information exported.
22:00:00: Exporting submesh name table...
22:00:00: Submesh name table exported.
22:00:00: Mesh data exported.
22:00:00: MeshSerializer export successful.
```

This is the log from `OgreMeshUpgrader` from OGRE v14.2.3
```
: MeshSerializer writing mesh data to stream D:\tmp\VertexOptTest\Plane.mesh...
: File header written.
: Writing mesh data...
: Writing submesh...
: Submesh exported.
: Exporting bounds information....
: Bounds information exported.
: Exporting submesh name table...
: Submesh name table exported.
: Mesh data exported.
: MeshSerializer export successful.
```

The time is missing.

Same thing happens with `OgreXMLConverter`

Also... it would be nice to have time and date.

**Comment by paroj** [comment]
you are mingw, right? Then it is the combination of:
- https://sourceforge.net/p/mingw-w64/bugs/793/
- 6b8123a9fae709f1b1c13b91609f721fd30c4573

will have to replace %T.

**Comment by paroj** [comment]
> Also... it would be nice to have time and date.

ogre logs get overwritten each run, so the timestamp of the file gives the date. However the main reason I dont want to add date is that somebody is probably parsing the log output and it would break that.
