### ISSUE TITLE
glTF multiple materials support

### ISSUE THREAD

**Issue by ikcppdeveloper** [OGRECave/ogre#3125]
Hi all, it seems that currently multiples materials are not supported for glTF format below you can find different viewers usage for same glTF source file:

![image](https://github.com/OGRECave/ogre-meshviewer/assets/985905/dae55cdb-c964-40f6-9e3d-c8656fa36be9)

![image](https://github.com/OGRECave/ogre-meshviewer/assets/985905/f943e306-5af1-4a7c-bad2-02b0d2dcf656)

![image](https://github.com/OGRECave/ogre-meshviewer/assets/985905/adcd762f-57bf-4ef3-8abc-17a0c33e269b)

and the sample source file in mesh-viewer:

![image](https://github.com/OGRECave/ogre-meshviewer/assets/985905/d9043901-f5de-4c25-ad67-581e28194cc3)

the test source file:

[training.zip](https://github.com/OGRECave/ogre-meshviewer/files/15456371/training.zip)

**Comment by paroj** [comment]
this is a limitation of the assimp loader in ogre. transferring the issue there
