### ISSUE TITLE
PCZSceneManager might have a memory leak as it doesn't delete mAntiPortals

### ISSUE THREAD

**Issue by Hotshot5000** [OGRECave/ogre#3132]
In PCZSceneManager destructor I see that mPortals get deleted but mAntiPortals are not deleted. Same in init() only mPortals get deleted.

**Comment by Hotshot5000** [comment]
Should probably be something like this:
`PCZSceneManager::~PCZSceneManager()
    {
        // we don't delete the root scene node here because the
        // base scene manager class does that.

        // delete ALL portals
        Portal * p;
        PortalList::iterator i = mPortals.begin();
        for (i = mPortals.begin(); i != mPortals.end(); i++)
        {
            p = *i;
            OGRE_DELETE p;
        }
        mPortals.clear();
        
        AntiPortal * ap;
        AntiPortalList::iterator iap = mAntiPortals.begin();
        for (iap = mAntiPortals.begin(); iap != mAntiPortals.end(); iap++)
        {
            ap = *iap;
            OGRE_DELETE ap;
        }
        mAntiPortals.clear();

        // delete all the zones
        for (ZoneMap::iterator j = mZones.begin();
            j != mZones.end(); ++j)
        {
            OGRE_DELETE j->second;
        }
        mZones.clear();
        mDefaultZone = 0;
    }`

**Comment by paroj** [comment]
sounds valid. can you provide a pull-request?

**Comment by Hotshot5000** [comment]
https://github.com/OGRECave/ogre/pull/3134

Waiting for the checks to pass.
