### ISSUE TITLE
Question: Is there a possibility to use paths as filenames within OgreResourceManager?

### ISSUE THREAD

**Issue by schoko-drache** [OGRECave/ogre#3196]
I'm developing my own Game engine using Ogre. I have the following problem:
I have a file located in data/images and add data to resource group "General" and then try to load it using `Ogre::TextureManager::getSingleton().load("images/Image.png", "General");` but i get FileNotFound exceptions. I'm using Ogre for the first time and there is no option for me to add each folder to the resources.cfg and also no option to use the recursive search, because there are multiple files with the same name. Thanks for help!

**Comment by paroj** [comment]
setting the recursive flag will give you the behaviour your describe:
https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_resource_group_manager.html#a6ff0efec5d27cedb448cfba8b2b78c8d
