### ISSUE TITLE
Recursive option documentation misleading

### ISSUE THREAD

**Issue by schoko-drache** [OGRECave/ogre#3199]
The documentation of the recursive flag at the resource manager is misleading it says: `If the resource location has a concept of recursive directory traversal, enabling this option will mean you can load resources in subdirectories using only their unqualified name. The default is to disable this so that resources in subdirectories with the same name are still unique. ` I understand that with the "unqualified" like this: you have a image in data/images/image.jpg and add data to resources.cfg reading the documentation I thought I now can read image by just loading image.png without path because this is unqualified and would be done by recursive search. But in fact the flag does something completely different. Sorry if I'm misinterpreting something but I think I'm not the only beginner that got stuck there.

**Comment by paroj** [comment]
fixed in 6f45c91abc5fff97ca51c29c8024e0a0f00438a1
