### ISSUE TITLE
In ApplicationContextQt.h file, two virtual functions is private, but in Qt is protected, ok?

### ISSUE THREAD

**Issue by suchaoyong** [OGRECave/ogre#3211]
hello,

There are two functions about the end of ApplicationContextQt.h file,  
--------------------------
private:
    void timerEvent(QTimerEvent *e) override;
    bool eventFilter(QObject *obj, QEvent *event) override;
--------------------------
In Qt, they are protected.

why no use 'final' ?

**Comment by suchaoyong** [comment]
This Narrows access and makes it difficult to change the behavior of these two functions in derived classes.
Was it designed that way on purpose?

**Comment by paroj** [comment]
the functions are private on purpose. However, I have no strong feeling to keep it that way. Can you provide a use-case where you would need protected access to them?

**Comment by paroj** [comment]
no reply by reporter
