### ISSUE TITLE
Add repology badge to README ?

### ISSUE THREAD

**Issue by luzpaz** [OGRECave/ogre#3251]
Add a Packaging Status section in readme with the following badge:  
<a href="https://repology.org/project/ogre/versions">
    <img src="https://repology.org/badge/vertical-allrepos/ogre.svg?columns=3&header=Ogre%20Packaging%20Status&exclude_unsupported=1" alt="Packaging status">
</a>

I'm currently trying to clean up the badge so it differentiates ogre from ogre-next

-----

Edit: 
It's also possible to put the badge in a collapsed div. Here's an preview of how it can look in the README:

## Packaging Status

<details><summary>Expand to view Ogre Packaging status</summary>
<a href="https://repology.org/project/ogre/versions">
    <img src="https://repology.org/badge/vertical-allrepos/ogre.svg?columns=3&header=Ogre%20Packaging%20Status&exclude_unsupported=1" alt="Packaging status">
</a>
</details>

**Comment by paroj** [comment]
I already link to repology on the downloads page:
https://www.ogre3d.org/download/sdk/sdk-ogre

I do not think it is necessary to have it in the readme
