### ISSUE TITLE
Stunt Rally 2.x is using it

### ISSUE THREAD

**Issue by cryham** [OGRECave/ogre#3258]
I'm just concerned about the line in [README.md](https://raw.githubusercontent.com/OGRECave/ogre/refs/heads/master/README.md)
linking to
`- [Stunt Rally - 3D Racing Game with Track Editor](https://stuntrally.tuxfamily.org/)`

Technically Stunt Rally 2.x is using Ogre.
Stunt Rally 3.x is using Ogre-Next 3.0, from SR 3.0, soon since 2 years (as in our [Statistics.md](https://github.com/stuntrally/stuntrally3/blob/main/docs/Statistics.md)).

This could be confusing, so I'd recommend changing the line to this:
`- [Stunt Rally 2.x - 3D Racing Game with Track Editor](https://github.com/stuntrally/stuntrally/)`
as the main SR website also shows SR3 now, e.g. in gallery, video etc.

Do you agree? If so, could you change it or should I do it in a PR?

**Comment by paroj** [comment]
feel free to create a PR

**Comment by cryham** [comment]
ok done
https://github.com/OGRECave/ogre/pull/3259
