### ISSUE TITLE
API/ABI changes review for OGRE

### ISSUE THREAD

**Issue by lvc** [OGRECave/ogre#375]
The review of API/ABI changes for OGRE since 1.7.3 version: https://abi-laboratory.pro/tracker/timeline/ogre/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

The tool checks _all_ API symbols declared in header files, so there may be some false positives.

Thank you.

![ogre-1](https://cloud.githubusercontent.com/assets/1517837/24507134/b1cb4290-1570-11e7-87a3-033e5c4bcf1e.png)

![ogre-2](https://cloud.githubusercontent.com/assets/1517837/24507144/bc3f1a80-1570-11e7-8906-c76b569dbe2b.png)

## Environment
* Linux x86_64
* GCC 4.9
* OGRE 1.7.3 and higher

**Comment by paroj** [comment]
Thanks this overview is very helpful.

However, there are many false positives due to a template argument change related to the STLAllocator.
One would get a more realistic API change estimate with
 `OGRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR=1` set in CMake for Ogre 1.10. Could you change the build accordingly?

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/ogre/

Should we check lib/OGRE/* objects?

Thank you.

![ogre-3](https://cloud.githubusercontent.com/assets/1517837/24647644/cc366190-1931-11e7-9e40-2b5fd5052182.png)

![ogre-4](https://cloud.githubusercontent.com/assets/1517837/24647648/d11c805e-1931-11e7-98b6-726aedf2af33.png)

**Comment by paroj** [comment]
> Should we check lib/OGRE/* objects?

no, those are plugins that are only supposed to be used through the OgreMain API.

**Comment by paroj** [comment]
I have added a link to the review on the github landing page: https://ogrecave.github.io/ogre/

does your builder picks up soname changes automatically? e.g. if I go from 1.10.3 to 1.10.4? And do you poll github or bitbucket?

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/ogre/

Added 'current' version from the Mercurial source repository. The report is updated 3 times a week (SONAME is reflected properly). If you'd like to regenerate report on every commit then you can setup your local instance of the Tracker: https://github.com/lvc/abi-tracker

Releases of the library are currently tracked on https://github.com/OGRECave/ogre/tags

Thank you.

**Comment by paroj** [comment]
thanks a lot! if there is one more thing to ask, I would rather prefer that "current" tracks master on github instead of bitbucket for consistency.

Unfortunately I currently do not have access to an dedicated machine to set up a custom isntance of the abi-tracker.

**Comment by lvc** [comment]
> "current" tracks master on github instead of bitbucket for consistency

Done: https://abi-laboratory.pro/tracker/timeline/ogre/

Thank you.

**Comment by paroj** [comment]
awsome! thanks again for setting this up and developing the tool.
