### ISSUE TITLE
undefined reference to 'rand'

### ISSUE THREAD

**Issue by ftheirs** [OGRECave/ogre#376]
Hi! I compiled this version of OGRE but I get an error message when I try to use it in my Qt application.

The samples OgreJNI and SampleBrowserNDK are working fine. The problem that I have with this version is that when I try to compile my application I get **undefined reference to 'rand'** (from OgreMath.cpp). I cannot understand why this is happening.

API level: 21
NDK: r12b

Is there a restriction with the NDK version that I should use? Or I'am doing something wrong?

**Comment by paroj** [comment]
probably `-lm` is missing. also take a look at: https://github.com/OGRECave/ogre/blob/master/CMake/Templates/Android.mk.in

**Comment by ftheirs** [comment]
Oks, I added libm to my Qt project but the error stays. Then I recompiled OGRE with "ANDROID_LIBM_PATH" but nothing's changed.

I compiled OGRE again but this time with NDK r8c for API 14. The error about 'rand' is gone but my app crashes when it creates a render window. This is probably my fault.

Is there a know issue about compatibility between different NDK version? Or I could use this (r8c for OGRE) and a newer for my application?

**Comment by paroj** [comment]
quick round of google gives this:
https://stackoverflow.com/questions/27338318/cannot-load-library-reloc-library1285-cannot-locate-rand

so it probably has to do with android API 21. As both OGRE samples build fine with API 21, this seems specific to your setup and not OGRE related.

**Comment by ftheirs** [comment]
Yup! My bad :( In AndroidManifest.xml I set the minimum version to API 19 and that was the problem! Thanks paroj!!
