### ISSUE TITLE
 ensure that resources created in the current context would be visible after context switching

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#403]
from: https://bitbucket.org/sinbad/ogre/commits/93ed2fb584e01e6a0aecc9eeef107c7a750b1e9d

Basically the problem of the multi context Ogre is that for new rendertarget with a new scene resources for the new scene are created in arbitrary current OpenGL context, but rendering commands are issued after switching to the new context of the new rendertarget. There is the problem, command sequencing is required, so that resource creation commands in first context would be completed before resource usage commands in second context. Or Ogre should allow to explicitly switch to specific context, so that resource would be created where would be used, as an alternative.

It's true, glFlushRenderAPPLE is faster version of glFlush, because it is not presenting version of glFlush.

Ogre has glFlush and glFinish commands, but both are created to guarantee flushing interim buffers and ensuring that result of rendering is presented to rendertarget. Ogre design that hides OpenGL context switching needs command sequencing that could be achieved by flushing per-context command queue to single GPU queue, but both glFlush and glFinish are additionally present whatever the content of backbuffer is to the rendertarget of the current context, for example shadow map of the new scene to the old view, causing flickering or even long term view content corruption if rendering is not 'as fast as possible' but on demand. The other problem is that even the glFlush blocks till all commands are passed to the GPU queue of limited length, emptied from the other end by actually performing commands on GPU. glFlushRenderAPPLE is glFlush without presentation, that is suitable to solve Ogre's problem with sequencing commands in the multiple contexts without corruption of the content of the current rendertarget. For GPU queues of large enough length blocking should not happen too, but without any guarantee. You see? Cross platform Ogre problem, with platform specific solution. For EGL contexts the problem is recognized, and solution via eglWaitXxx is standardized, https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglWaitClient.xhtml . But actually what is needed is a fence, not a flushing, it is an accident that with a single <GPU command queue> flushing does a sequencing.

Regarding standard solution to sequencing problem - it could be constructed using commands availaible since OpenGL 3.2 (ouch!!!) or via ARB_sync extension. Fence (official term) could be created and scheduled for signailling using glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE). That fence type is even multi-context aware and could be waited for in other contexts, that is not true for earlier NV_fence or APPLE_fence extensions. So far, so good, but devil is in details - shit happens at the waiting site. There are two functions that are capable of waiting for the fence completion - CPU blocking glClientWaitSync and non-CPU-blocking glWaitSync https://www.khronos.org/opengl/wiki/Sync_Object . The promised shit - glWaitSync blocks GPU queue from accepting new commands from per-context CPU queues till the fence is completed, performing necessary sequencing in standard compliant way EXCEPT that it causes DEADLOCK if fence creation is itself not yet in GPU queue. HolyMFShit. But lets try to workaround broken design - lets try to flush fence creation to GPU to perform sequencing via fences without deadlocking to avoid flushing to GPU. There is GL_SYNC_FLUSH_COMMANDS_BIT that is looking quite promising, but non-blocking glWaitSync does not accept it. We should call glClientWaitSync, passing GL_SYNC_FLUSH_COMMANDS_BIT and a large enough timeout or commands flushing could not be yet completed, causing deadlock. OpenGL 4.5 provides workaround for an workaround, suggesting to create fence long before it would be needed, and guarantee that first call to glClientWaitSync with GL_SYNC_FLUSH_COMMANDS_BIT on the same context that creates fence will flush commands till and including the fence itself, but not later issued commands, so that there is hope that fence is already created, there would not be waiting for fence creation, and there would not be deadlock when glWaitSync would be called for this fence in other contexts - for the costs of creating fence long ahead of time it would be needed. But this approach would work, even if only since OpenGL 3.2.

The other issue with glFenceSync+glClientWaitSync/glWaitSync is that synchronization is cooperative from the side of the other contexts, that should call glWaitSync - while it is acceptable in the case of single threaded multicontext application - it is not good for multithreaded multicontext applications, and glFlushRenderAPPLE or eglWaitXxx is much simpler solution for the simple problem of the multicontext application, such as Ogre is.

That is the reason why for the existing (!) cross-platform (!) problem of the Ogre in area of sharing resources between multiple contexts I provide only platform-specific solution, for the platform that is already crashes (!) due to this problem is not hidden on this platform (OSX) as configured by Ogre(via enabling Apple OpenGL multithreaded engine via kCGLCEMPEngine) by some platform-specific things that are done despite not required by standard.

**Comment by Naros** [comment]
The GL3+ render system is seriously flawed in its support for multi render targets.

The legacy OpenGL implementation worked like a charm when you wanted to have different scenes being rendered to different render windows; however I have yet to be able to accomplish the same on GL3+ under Linux using Mesa/GTX.  

The `currentGLContext=true` option ends with a crash at buffer swap with a BadMatch exception when using a shared GL context and when not using a shared context, only the first window that allocates the associated VAO is what gets rendered.  The other windows never formally draw any of their geometry in the scene pass.

**Comment by Naros** [comment]
I recently added the following update on the forums:
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=84711&p=536917#p536917

When using a single context shared between multiple render windows, GL3+ will work but the issue seems to be with how the GLXFBConfig is generated (doesn't seem to work exactly as intended) but can be hacked around but then the compositor pass buffer swap order seems to present issues.

**Comment by paroj** [comment]
this issue is fixed. please open a separate issue for the "multi render targets" problems.
