### ISSUE TITLE
when v2.x can build success on macOS?

### ISSUE THREAD

**Issue by srxqds** [OGRECave/ogre#413]
hi, I  pay attention to following ogre v2.x progress every day.  I notice the macos version always don't build pass. And I can't waiting for it, I longed to see it and learning.

Is something tutorial about build current version on macOS or when?

**Comment by paroj** [comment]
2.0 should build. 2.1 currently does not support OSX due to outdated GL3 implementation by Apple and incomplete Metal renderer in OGRE.
