### ISSUE TITLE
DualQuaternion_Common.glsl error

### ISSUE THREAD

**Issue by alabd14313** [OGRECave/ogre#524]
Hello!
Ogre v1.10.8

I can compile bellow project successfully, but when I run it (GL or GL3_plus) produces an error:
`An OGRE exception has occured: 
FileNotFoundException: Cannot locate resource DualQuaternion_Common.glsl in resource group General. in ResourceGroupManager::openResource at /build/ogre/src/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 708)`

Here is project files:
[ogre-tut.zip](https://github.com/OGRECave/ogre/files/1316958/ogre-tut.zip)

**Comment by paroj** [comment]
the group "General" is defined twice in your resources.cfg

**Comment by paroj** [comment]
also does the snap package work for you?

**Comment by paroj** [comment]
no response by reporter
