### ISSUE TITLE
build of Direct3D9 fail with OGRE_USE_STD11=ON

### ISSUE THREAD

**Issue by Speciesx** [OGRECave/ogre#525]
> Error	C2039	'bind': is not a member of 'std::shared_ptr<Ogre::MemoryDataStream>' [D:\Ogre_1.10\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\Ogre_1.10\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9HardwarePixelBuffer.cpp	643	

> Error	C2039	'set': is not a member of 'std::atomic<Ogre::Resource::LoadingState>' [D:\Ogre_1.10\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\Ogre_1.10\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9Texture.cpp	1871	

Windows 10 x64
VS 2017 Community

**Comment by paroj** [comment]
these are remains of the some deprecated API that is not available with OGRE_USE_STD11. see:
https://ogrecave.github.io/ogre/api/1.10/deprecated.html

can you provide a pull-request fixing this?

**Comment by Speciesx** [comment]
> Error	C2065	'mResourcesMutex': undeclared identifier [D:\\Ogre_1.10\\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\\Ogre_1.10\\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9ResourceManager.cpp	135	
Error	C2065	'mResourcesMutex': undeclared identifier [D:\\Ogre_1.10\\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\\Ogre_1.10\\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9ResourceManager.cpp	150	
Error	C2228	left of '.lock' must have class/struct/union [D:\\Ogre_1.10\\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\\Ogre_1.10\\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9ResourceManager.cpp	135	
Error	C2228	left of '.unlock' must have class/struct/union [D:\\Ogre_1.10\\build_x86\Build\ogre\RenderSystems\Direct3D9\RenderSystem_Direct3D9.vcxproj]	ogre	D:\\Ogre_1.10\\build_x86\Source\ogre\RenderSystems\Direct3D9\src\OgreD3D9ResourceManager.cpp	150	


more errors with the latest upstream.
