### ISSUE TITLE
gl_PointCoord is null

### ISSUE THREAD

**Issue by matthieu-ft** [OGRECave/ogre#542]
Using OpengGL3+  with ogre, I used to be able to use `gl_PointCoord` without problem in fragment shader.
I tried to use it again today, and it wouldn't  work (gl_PointCoord always zero), unless I enable  `GL_POINT_SPRITE`  with the following implementation:

```cpp
    void GL3PlusRenderSystem::_setPointSpritesEnabled(bool enabled)
    {
        OGRE_CHECK_GL_ERROR(glEnable(0x8861));
    }
```

as suggested in https://www.reddit.com/r/opengl/comments/480u1r/help_gl_pointcoordxy_always_zero_in_fragment/ .

GL_POINT_SPRITE is supposed to be enabled per default, so this is surely driver bug.
This is the only way I found to overcome the problem, so it might be useful to integrate it.

**Comment by paroj** [comment]
could you provide your driver and driver version? We should restrict this workaround to the case where it is needed.
Also this should be in `_oneTimeContextInitialization` for consistency with the specs.

**Comment by matthieu-ft** [comment]
RenderSystem Name: OpenGL 3+ Rendering Subsystem
GPU Vendor: nvidia
Device Name: GeForce GTX 960M/PCIe/SSE2
Driver Version: 4.5.0.0
