### ISSUE TITLE
Objects are not rendered anymore since OGRE 1.10.8

### ISSUE THREAD

**Issue by greimela** [OGRECave/ogre#562]
Version: 1.10.8
OS: Ubuntu 16.04

I have the problem since upgrading from OGRE 1.10.7 to 1.10.8 that some objects are not rendered anymore.
I was not able to provide a minimum example, but I identified the problem to be a combination of using OpenGL, rendering in triangle mode while using GLSL 120 on an intel graphics card capable of OpenGL 3.0.
The rendering still works fine on an Nvidia card capable of OpenGL 4.5.

After checking all changes since version 1.10.7, I identified the responsible change to be commit aa4b80c63fdeb829d785f3ebbe87581288ea1519. 

In this change, the `isAttributeValid()` method is removed from the `OgreGLSLLinkProgram` and instead uses the superclass implementation.

The implementation therefore changes from 
https://github.com/OGRECave/ogre/blob/4fd060cd914a5d54f00f9a7bec80fa42e155ec6e/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp#L230-L233
to
https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GLSupport/include/GLSL/OgreGLSLProgramCommon.h#L81-L83

When I revert to the original version of `isAttributeValid()` in the OgreGLSLLinkProgram` class, the objects are rendered correctly.

Do you have any idea what could be the problem here?
Why do the two `isAttributeValid()` methods lead to different results?

Please tell me if you need more information!

------------
**Additional Findings**
~~I noticed that the new [isAttributeValid()](https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GLSupport/include/GLSL/OgreGLSLProgramCommon.h#L81-L83) method above checks whether the result of [getAttributeValid()](https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp#L187) is equal to -1.
However, [getAttributeValid()](https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp#L187) only calls [OgreGLSLProgramCommon::getFixedAttributeValid()](https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GLSupport/src/GLSL/OgreGLSLProgramCommon.cpp#L179), which never returns -1.
Could this be the reason for the bug?~~
Edit: Never mind, this was fixed in a future commit.

**Comment by paroj** [comment]
> Edit: Never mind, this was fixed in a future commit.

does this issue itself still persist in the "future" commit?

**Comment by greimela** [comment]
Yes, the issue still persists at the v1.10.8 tag, which includes this "future" commit. 
-------- Ursprüngliche Nachricht --------Von: Pavel Rojtberg <notifications@github.com> Datum: 06.11.17  17:20  (GMT+01:00) An: OGRECave/ogre <ogre@noreply.github.com> Cc: Andreas Greimel <andreas@greimel.de>, Author <author@noreply.github.com> Betreff: Re: [OGRECave/ogre] Objects are not rendered anymore since OGRE 1.10.8 (#562) 

Edit: Never mind, this was fixed in a future commit.

does this issue itself still persist in the "future" commit?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OGRECave/ogre","title":"OGRECave/ogre","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OGRECave/ogre"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paroj in #562: \u003e Edit: Never mind, this was fixed in a future commit.\r\n\r\ndoes this issue itself still persist in the \"future\" commit?"}],"action":{"name":"View Issue","url":"https://github.com/OGRECave/ogre/issues/562#issuecomment-342200912"}}}

**Comment by paroj** [comment]
what are the values for "semantic" and "index"? This all boils down to `getFixedAttributeIndex` returning -1 where it did not return -1 before..

**Comment by greimela** [comment]
I added some cout's to [OgreGLSLProgramCommon::isAttributeValid()](https://github.com/OGRECave/ogre/blob/aa4b80c63fdeb829d785f3ebbe87581288ea1519/RenderSystems/GLSupport/include/GLSL/OgreGLSLProgramCommon.h#L81-L83), it is called with the semantics 1, 5 and 7, each with index 0.

If I add the [OgreGLSLLinkProgram::isAttributeValid()](https://github.com/OGRECave/ogre/blob/4fd060cd914a5d54f00f9a7bec80fa42e155ec6e/RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp#L230-L233) method back and check the parameters there, it is always called with semantic 0 and index 0.

Looks like the VES_POSITION attribute never reaches `isAttributeValid()` in `GLSLProgramCommon`?

**Comment by paroj** [comment]
VES_POSITION = 1, semantic = 0 does not exist. From you log isAttributeValid() behaves as expected in the new version while it always returns true in the old. Can you confirm that? (ideally make a table with semantic/ index/ return value for old/ new version)

**Comment by paroj** [comment]
does dca6b44f0871a63399597b14f647ffb2a432cd34 fix things for you?

**Comment by greimela** [comment]
Yes, it does!
Is it still interesting for you to see the different semantic/index/return value combinations?
Or should we just leave it that way?

**Comment by paroj** [comment]
no, the commit message already explains what was going wrong.

**Comment by greimela** [comment]
Perfect, thanks for your help!
