### ISSUE TITLE
TerrainMaterialGeneratorA does not load materials from correct resource group

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/ogre#567]
Since resource group loading became strict it became apparent that `TerrainMaterialGeneratorA` does not take into account the proper resource group where the materials should be in (the group that the Terrain uses). 

This is easy to fix however. For Ogre 1.10.9 source change lines 272 and 322 from `TerrainMaterialGeneratorA.cpp` so that the last parameter for `matMgr.create()` is `terrain->_getDerivedResourceGroup()` instead of `ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME`.

Patch:
```cpp
Index: OgreTerrainMaterialGeneratorA.cpp
===================================================================
--- OgreTerrainMaterialGeneratorA.cpp	(revision 25948)
+++ OgreTerrainMaterialGeneratorA.cpp	(working copy)
@@ -269,7 +269,7 @@
             mat = matMgr.getByName(matName);
             if (!mat)
             {
-                mat = matMgr.create(matName, ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME);
+                mat = matMgr.create(matName, terrain->_getDerivedResourceGroup());
             }
         }
         // clear everything
@@ -319,7 +319,7 @@
             mat = matMgr.getByName(matName);
             if (!mat)
             {
-                mat = matMgr.create(matName, ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME);
+                mat = matMgr.create(matName, terrain->_getDerivedResourceGroup());
             }
         }
         // clear everything
```

**Comment by paroj** [comment]
Thanks. For providing patches a pull-request would be better though - I could just merge it then.
