### ISSUE TITLE
Fails to find std::tr1::unordered_map

### ISSUE THREAD

**Issue by yurivict** [OGRECave/ogre#591]
On FreeBSD 11.1 there is no such class. You probably need to wrap it into ```#ifdef __cplusplus <  NNN```.

Also, this
```
#elif __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1800) || defined(__FreeBSD__)
    using std::function;
#else
    using std::tr1::function;
#endif
```

resolves to ```std::tr1::function``` and isn't found on the FreeBSD 11.1. I think ```__cplusplus >= 201103L``` has the wrong number in it.

**Comment by paroj** [comment]
can you provide an according pull-request?

**Comment by yurivict** [comment]
No, I am not sure what the solution should be.
