### ISSUE TITLE
OgreBillboardChain::getNumChainElements returns 1 after clear

### ISSUE THREAD

**Issue by Martin-Idel** [OGRECave/ogre#603]
Ogre Version 1.10.10 (or lower):

Given a BillboardChain with one chain (at least), I would assume from reading the documentation that
`BillboardChain::getNumChainElements(0)` returns 0 after calling `BillboardChain::clearAllChains()`. 

However, it returns 1. When accessing the element via `BillboardChain::getChainElement(0,0)` I get back an element, however modifying it via `BillboardChain::updateChainElement(0,0)` it fails.

If this is unintended behaviour, I can provide a PR fixing this issue.

**Comment by paroj** [comment]
> If this is unintended behaviour, I can provide a PR fixing this issue.

yes please, getChainElement and getNumChainElements seem not to handle SEGMENT_EMPTY correctly.
