### ISSUE TITLE
Cropping a hardware pixel buffer doesn't work

### ISSUE THREAD

**Issue by AndreAhmed** [OGRECave/ogre#604]
I have a texture and I get its hardware pixel buffer, the texture width is 512, and its height is 1024.
I tried to lock, crop the pixels, but I get scan lines.

     int min_x = 0;
        int min_y = 0;
        int max_x = 0;
        int max_y = 0;
        float screenPositionX =512 - screenPosition.x;
        float screenPositionY =1024 - screenPosition.y;

        min_x = std::max( 0, (int) screenPositionX );
        min_y = std::max( 0, (int) screenPositionY );
        max_x = std::min( (int)512, (int) screenPositionX + radius );
        max_y = std::min( (int)1024, (int) screenPositionY + radius );
        // Get the pixelbox within the radius.
        Ogre::Box regionBox( (int)screenPositionX, (int)screenPositionY, max_x, max_y  )

**Comment by AndreAhmed** [comment]
For example a src box (0,0,512,1024) it gets a full image, but a srcbox with (0,512,1023) I get scanlines

**Comment by paroj** [comment]
which rendersystem were you using?
maybe fixed by da32e53a9a870d861ee98186cbbb4baf6e9a5e16
