### ISSUE TITLE
build fails using angle (google stock) opengl es2 egl window windows msvc 2015

### ISSUE THREAD

**Issue by uvguy** [OGRECave/ogre#613]
Hello , I encountered build problems using opengl es2 from angle (google stock) on windows.
in https://github.com/OGRECave/ogre/blob/master/RenderSystems/GLSupport/CMakeLists.txt

around line 33, I need to add  something like this
```
 if(MSVC AND OGRE_BUILD_RENDERSYSTEM_GLES2) 
		include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../GLES2/include)
		include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../GLES2/src/GLSLES/include)
		set(PLATFORM_LIBS ${EGL_egl_LIBRARY})
	  endif(MSVC AND OGRE_BUILD_RENDERSYSTEM_GLES2)
```
otherwise the build wont work using above setup. Assuming current support opengl es2 desktop is msvc only. I'm not sure if using mingw if possible.

If someone want to reproduce try using this git https://github.com/google/angle/commit/a71a98ee22 version (this is last working with msvc2015 only).

**Comment by paroj** [comment]
GLSupport should not depend on any RS. Does this work as well?
https://github.com/OGRECave/ogre/pull/611/commits/94bbbcc4754820f7cff4b2c5c3b87a9bf79db47b#diff-e5c976a0e69f179cbf66fa3a27244abdL35

**Comment by uvguy** [comment]
in ogrewin32eglsupport texture header should also be removed

**Comment by uvguy** [comment]
build fines now thanks, but I got exception when running samplebrowser example 
![fafa](https://user-images.githubusercontent.com/28796034/34422658-441590f6-ec49-11e7-8ea5-fb320298f86d.png)

any pointers?

**Comment by paroj** [comment]
closing as the initial issue is solved

> any pointers?

no, unfortunately
