### ISSUE TITLE
How to compile android version on ubuntu16.04

### ISSUE THREAD

**Issue by Qchrlis** [OGRECave/ogre#626]
I use the command "cmake -DCMAKE_TOOLCHAIN_FILE=CMake/toolchain/android.toolchain.cmake -DANDROID_NDK=/home/chrlis/workspace/test/ogre/android-ndk-r15c ." 

But it prompt error like below:

`CMake Error at CMake/toolchain/android.toolchain.cmake:732 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:95 (include)
  CMakeLists.txt:48 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
`

**Comment by paroj** [comment]
works here. maybe the specified NDK location is wrong?

**Comment by Qchrlis** [comment]
@paroj Yes, I mv it into other dir, but I get other error(I met before).

`-- Could not locate FREETYPE
-- Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR) 
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMake/Dependencies.cmake:281 (find_package)
  CMakeLists.txt:351 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMake/Dependencies.cmake:281 (find_package)
  CMakeLists.txt:351 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMake/Dependencies.cmake:290 (find_package)
  CMakeLists.txt:351 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMake/Dependencies.cmake:290 (find_package)
  CMakeLists.txt:351 (include)


-- Looking for POCO...
-- Could not locate POCO
-- Looking for TBB...
-- Could not locate TBB
-- Looking for GLSL_Optimizer...
-- GLSL_Optimizer_PREFIX_PATH changed.
-- Could not locate GLSL_Optimizer
-- Looking for HLSL2GLSL...
-- HLSL2GLSL_PREFIX_PATH changed.
-- Could not locate HLSL2GLSL
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) 
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for Softimage...
-- Softimage_PREFIX_PATH changed.
-- Could not locate Softimage
-- 
-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
+ zlib
+ zziplib
+ OpenGL ES 1.x
+ OpenGL ES 2.x
+ OpenGL ES 3.x
-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
+ freeimage: Support for commonly used graphics image formats <http://freeimage.sourceforge.net>
+ freetype: Portable font engine <http://www.freetype.org>
+ OpenGL 3+: Support for the OpenGL 3+ render system <http://www.opengl.org/>
+ boost: Boost (general) <http://boost.org>
+ boost-thread: Used for threading support <http://boost.org>
+ POCO: POCO framework <http://pocoproject.org/>
+ tbb: Threading Building Blocks <http://www.threadingbuildingblocks.org/>
+ GLSL Optimizer: GLSL Optimizer <http://github.com/aras-p/glsl-optimizer/>
+ HLSL2GLSL: HLSL2GLSL <http://hlsl2glslfork.googlecode.com/>
+ OpenEXR: Load High dynamic range images <http://www.openexr.com/>
+ Python: Language bindings to use OGRE from Python <http://www.python.org/>
+ Doxygen: Tool for building API documentation <http://doxygen.org>
+ Softimage: Softimage SDK needed for building XSIExporter <FALSE>
-----------------------------------------------------------------------------

-- 
----------------------------------------------------------------------------
  FEATURE SUMMARY
----------------------------------------------------------------------------

Building components:
  + HLMS [BETA]
  + MeshLodGenerator
  + Paging
  + Property
  + RTShader System
  + RTShader System Core Shaders
  + RTShader System Extensions Shaders
  + Terrain
  + Volume
Building plugins:
  + Octree scene manager
  + Particle FX
Building rendersystems:
  + OpenGL ES 2.x
Building core features:
  + Mesh Lod
  + DDS image codec
  + PVRTC image codec
  + ETC image codec
  + STBI codec
  + ZIP archives

Build type:                      static
Threading support:               none
ResourceManager behaviour:       legacy [DEPRECATED]
Use double precision:            disabled
Nodes inherit transform:         disabled
Assert mode:                     release exceptions
Allocator type:                  standard
STL containers use allocator:    disabled
Strings use allocator:           disabled
Memory tracker (debug):          disabled
Memory tracker (release):        disabled

----------------------------------------------------------------------------

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREETYPE_FT2BUILD_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/OgreMain
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLSupport
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/RenderSystems/GLES2
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/OctreeSceneManager
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/PlugIns/ParticleFX
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Paging
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/MeshLodGenerator
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Property
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Terrain
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/RTShaderSystem
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/Volume
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Components/HLMS
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Docs
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/Samples/Media
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake
   used as include directory in directory /home/chrlis/workspace/test/ogre/CMake

-- Configuring incomplete, errors occurred!
See also "/home/chrlis/workspace/test/ogre/CMakeFiles/CMakeOutput.log".
See also "/home/chrlis/workspace/test/ogre/CMakeFiles/CMakeError.log".
`

See: /home/chrlis/workspace/test/ogre/CMakeFiles/CMakeError.log
`
Performing C++ SOURCE FILE Test OGRE_GCC_HAS_SSE failed with the following output:
Change Dir: /home/chrlis/workspace/test/ogre/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ee784/fast"
/usr/bin/make -f CMakeFiles/cmTC_ee784.dir/build.make CMakeFiles/cmTC_ee784.dir/build
make[1]: Entering directory '/home/chrlis/workspace/test/ogre/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_ee784.dir/src.cxx.o
/home/chrlis/workspace/test/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++   -DANDROID -isystem /home/chrlis/workspace/test/android-ndk-r15c/platforms/android-26/arch-arm/usr/include -isystem /home/chrlis/workspace/test/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/chrlis/workspace/test/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include  -fexceptions -frtti -Wno-psabi --sysroot=/home/chrlis/workspace/test/android-ndk-r15c/platforms/android-26/arch-arm -fpic -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fdata-sections -ffunction-sections -Wa,--noexecstack  -DOGRE_GCC_HAS_SSE   -msse -o CMakeFiles/cmTC_ee784.dir/src.cxx.o -c /home/chrlis/workspace/test/ogre/CMakeFiles/CMakeTmp/src.cxx
arm-linux-androideabi-g++: error: unrecognized command line option '-msse'
CMakeFiles/cmTC_ee784.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_ee784.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_ee784.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/chrlis/workspace/test/ogre/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ee784/fast' failed
make: *** [cmTC_ee784/fast] Error 2

Source file was:
int main() { return 0; }
`

Can you give me some advice ?

**Comment by paroj** [comment]
it did not build the dependencies - probably due to the invalid NDK. start over with a clean build

**Comment by Qchrlis** [comment]
I can not get an r10b NDK, but it will download an r13 NDK automatically. 
But the same question.
