### ISSUE TITLE
No way to quit the application. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [OGRECave/ogre#686]
#### Expected behavior
I downloaded this app from f-droid and opened this for a while. Then I want to close the app.

#### Actual behavior
When I opened the app for some time now i want to close the app by "quit"option fixed in app.
No way to quit the app.

#### How to reproduce
Download the OgerSampleBrowser from f-droid.
Then open it for some time,
when you want to close the app, press on the "quit" option mentioned in app.
It doesn't gets quit.

* Browser: OgreSampleBrowser
* Version:1.10.11
* Operating system:5.1.1
#### Recording Of The Bug
Here is the GIF of the bug.
![20180304_184531.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520189701/poepvukjlh9lilvs7uyb.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/bug-found-in-ogresamplebrowser">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by paroj** [comment]
the sample browser is only a demo app for testing ogre on your device and honestly you are not meant to ever leave ogre..

**Comment by 0xpr03** [comment]
@paroj please just close it if you think it's too minor. The reporting account is 24 days old and posts only kind of abuse related issues to android repos (10+), all of them related to utopian, from which I've some response.

**Comment by paroj** [comment]
fixed in master
