### ISSUE TITLE
RSC_GLSL_SSO_REDECLARE has problems with Intel HD graphic cards

### ISSUE THREAD

**Issue by tobiza** [OGRECave/ogre#690]
The attribute RSC_GLSL_SSO_REDECLARE has problems with Intel HD graphic cards.
First of all Intel HD graphic cards do not support float gl_ClipDistance[]; because of the empty array size.
To fix this one can manually disable RSC_GLSL_SSO_REDECLARE in the application.

The new Intel HD 530 graphic cards actually need the gl_PerVertex declaration or otherwise they fail with "gl_PerVertex block must be explicitly declared by user in separable program".
To fix this one can add the declaration of gl_Position and gl_PointSize manually to every vertex and geometry shader but because of the first issue with the array size one cannot add gl_ClipDistance[].

It would be a good idea to add a workaround (for both cases?) in Ogre3D for this behavior of Intel HD graphic cards.

**Comment by ViennaL** [comment]
I am having the same issues:

Hardware: Intel HD 530 graphics card
OS: Windows 7

Intel Driver Version 20.19.15.4331 (2015) --> everything works fine
Intel Driver Version 21.20.16.4839 (19.10.2017) --> shader compilation errors
Intel Driver Version 21.20.16.4680 (15.11.2017) --> shader compilation errors

In the log file you get for every shader program that includes a geometry stage:
GLSL program result : 
**gl_PerVertex block must be explicitly declared by user in separable program**

**Comment by paroj** [comment]
probably this https://github.com/PCSX2/pcsx2/commit/bdc8038e7e568b9a40425810d0c0e3f88dd752af
