### ISSUE TITLE
Ogre stable branch does not compile on GNU/Linux

### ISSUE THREAD

**Issue by ViennaL** [OGRECave/ogre#699]
**Ogre stable branch does not compile on GNU/Linux.**
Commit b166b52878103219d80297522223c2d97f3dc9fa produces the follwing compile error:

```
/OgreMain/include/OgreImage.h:204:64: error: no matching function for call to 'Ogre::Image::loadRawData(const DataStreamPtr&, Ogre::uint32&, Ogre::uint32&, int, Ogre::PixelFormat&)'
             return loadRawData(stream, width, height, 1, format);
```

Additionally your continuous integration server seems to be stuck at compiling the latest changes:
http://jonas.masterfalcon.com:8080/view/default/job/ogre-default-pipeline/

**Comment by paroj** [comment]
fixed via force push. The Jenkins servers are stuck by default, therefore the main CI is Travis:
https://travis-ci.org/OGRECave/ogre
