### ISSUE TITLE
Parsing script files with missing end bracket(s) fails silently

### ISSUE THREAD

**Issue by marko213** [OGRECave/ogre#701]
When a script file (tested with .material so far, but they should have the same parser) with at least one missing end bracket ('}') is parsed, no errors are generated; however the corresponding script is not added to the list of scripts.

Example script:
```cpp
// PanelWhite.material

material PanelWhite {
    receive_shadows off
    technique {
        pass PanelWhite {
            ambient 0.9 0.9 0.9 1.0
            diffuse 1.0 1.0 1.0 1.0
//	}
    }
}
```

**Comment by paroj** [comment]
material script go through the new (as in OGRE 1.6) script compiler framework instead the ad-hoc parsing like in Overlay.

The place to generate according errors is the Lexer:
https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreScriptLexer.cpp

**Comment by marko213** [comment]
It seems that no check is made to see whether some amount of brackets are missing (but there is a check for quotes)

**Comment by paroj** [comment]
unfortunately I have no time to fix this, but as always a PR is welcome
