### ISSUE TITLE
Showing configuration dialog partially fails: can not find codec for 'png'

### ISSUE THREAD

**Issue by marko213** [OGRECave/ogre#707]
![ogreconfigfail](https://user-images.githubusercontent.com/27025532/37846053-4dab08d6-2ec4-11e8-8d42-444e0b39992c.png)

Showing a configuration dialog with `Ogre::Root::Root::showConfigDialog` generates a "transparent" window with a graphics system selection box, which can be opened, but from which no options can be selected. Along with that a warning message is shown:
```
Warning: Can not load backdrop for config dialog: Can not find codec for 'png' image format.
Supported formats are: dds ktx pkm.
```

This was tested with `OgreBites::ApplicationContext`, https://github.com/OGRECave/ogre/blob/9ec6377176954b700e98b7e3c5d62078d8da90ec/Components/Bites/src/OgreApplicationContext.cpp#L241 likely fails.

The window also doesn't gain focus when clicked.

Built on Linux 32-bit.

**Comment by paroj** [comment]
it does not find any plugins. Check the log and your `plugins.cfg`.

The png codec is a plugin and the renderer box is populated by plugins.

**Comment by marko213** [comment]
If the plugin is in `RenderSystem_GLES` or `RenderSystem_GLES2`, then the issue might be caused by my build, which has the library for neither plugin being built.

Effective lines in `plugins.cfg`, which gets loaded (enabled loading the EXR codec):
```
PluginFolder=/usr/local/lib/OGRE
Plugin=RenderSystem_GL
Plugin=RenderSystem_GL3Plus
Plugin=Plugin_ParticleFX
Plugin=Plugin_CgProgramManager
Plugin=Plugin_EXRCodec
```

**Comment by paroj** [comment]
is this a debug build? The plugins cfg is incomplete there as I was going to drop the release/ debug cfg separation. You probably just need to add this line:
https://github.com/OGRECave/ogre/blob/master/CMake/Templates/plugins.cfg.in#L16

**Comment by marko213** [comment]
Indeed, that seemed to fix it. The `plugins.cfg` was copied from some manual tutorial which was about 3 years old, so that might have been the problem.
