### ISSUE TITLE
Dragging Sample Browser from one monitor to another freezes the application (possible endlessloop)

### ISSUE THREAD

**Issue by IQS-Leopold** [OGRECave/ogre#710]
#### System Information
- Ogre Version: 1.10.11
- Operating System / Platform: Windows 10 X64 (Fall Creators Update)
- RenderSystem: Direct3D9

#### Detailled description
I've discovered a application freeze if I move a a 3D Window to another screen. I can reproduce it with the sample browser. If I open the sample browser on one screen and move it to a second screen the application freezes. This only happens with Direct3D9.

I've located that the problem happens when reloading the textures after the new device is created. There is an Endless Loop. If I remove all Textures and all Fonts from my Application all works fine. It seems that accessing the buffer automatically causes a recreate of the texture which causes the load of the buffer and so on...

**Comment by paroj** [comment]
can you provide a stack trace/ line numbers for reconstructing the issue? The Ogre.log maybe?

**Comment by IQS-Leopold** [comment]
I think there are two Problems:

The problem described above wont occure if I change the getBuffer Method from the D3D9Texture class as following:

`    HardwarePixelBufferSharedPtr D3D9Texture::getBuffer(size_t face, size_t mipmap) 
    {
        if(face >= getNumFaces())
            OGRE_EXCEPT(Exception::ERR_INVALIDPARAMS, "A three dimensional cube has six faces",
                    "D3D9Texture::getBuffer");
        if(mipmap > mNumMipmaps)
            OGRE_EXCEPT(Exception::ERR_INVALIDPARAMS, "Mipmap index out of range",
                    "D3D9Texture::getBuffer");
        size_t idx = face*(mNumMipmaps+1) + mipmap;

		/*
		IDirect3DDevice9* d3d9Device = D3D9RenderSystem::getActiveD3D9Device();
		TextureResources* textureResources = getTextureResources(d3d9Device);
		if (textureResources == NULL || textureResources->pBaseTex == NULL)
		{
			createTextureResources(d3d9Device);
			textureResources = getTextureResources(d3d9Device);
		}
		assert(textureResources != NULL);
		assert(idx < mSurfaceList.size());
		*/

		return mSurfaceList[idx];
    }

`

And also the access of the buffer for logging from OgreMain -> Texture should be commented like this:

` //--------------------------------------------------------------------------
    void Texture::_loadImages( const ConstImagePtrList& images )
    {
        if(images.size() < 1)
            OGRE_EXCEPT(Exception::ERR_INVALIDPARAMS, "Cannot load empty vector of images",
             "Texture::loadImages");
        
        // Set desired texture size and properties from images[0]
        mSrcWidth = mWidth = images[0]->getWidth();
        mSrcHeight = mHeight = images[0]->getHeight();
        mSrcDepth = mDepth = images[0]->getDepth();

        // Get source image format and adjust if required
        mSrcFormat = images[0]->getFormat();
        if (mTreatLuminanceAsAlpha && mSrcFormat == PF_L8)
        {
            mSrcFormat = PF_A8;
        }

        if (mDesiredFormat != PF_UNKNOWN)
        {
            // If have desired format, use it
            mFormat = mDesiredFormat;
        }
        else
        {
            // Get the format according with desired bit depth
            mFormat = PixelUtil::getFormatForBitDepths(mSrcFormat, mDesiredIntegerBitDepth, mDesiredFloatBitDepth);
        }

        // The custom mipmaps in the image have priority over everything
        uint32 imageMips = images[0]->getNumMipmaps();

        if(imageMips > 0)
        {
            mNumMipmaps = mNumRequestedMipmaps = images[0]->getNumMipmaps();
            // Disable flag for auto mip generation
            mUsage &= ~TU_AUTOMIPMAP;
        }

        // Create the texture
        createInternalResources();
        // Check if we're loading one image with multiple faces
        // or a vector of images representing the faces
        size_t faces;
        bool multiImage; // Load from multiple images?
        if(images.size() > 1)
        {
            faces = images.size();
            multiImage = true;
        }
        else
        {
            faces = images[0]->getNumFaces();
            multiImage = false;
        }
        
        // Check whether number of faces in images exceeds number of faces
        // in this texture. If so, clamp it.
        if(faces > getNumFaces())
            faces = getNumFaces();
        
        if (TextureManager::getSingleton().getVerbose()) {
            // Say what we're doing
            StringStream str;
            str << "Texture: " << mName << ": Loading " << faces << " faces"
                << "(" << PixelUtil::getFormatName(images[0]->getFormat()) << "," <<
                images[0]->getWidth() << "x" << images[0]->getHeight() << "x" << images[0]->getDepth() <<
                ")";
            if (!(mMipmapsHardwareGenerated && mNumMipmaps == 0))
            {
                str << " with " << static_cast<int>(mNumMipmaps);
                if(mUsage & TU_AUTOMIPMAP)
                {
                    if (mMipmapsHardwareGenerated)
                        str << " hardware";

                    str << " generated mipmaps";
                }
                else
                {
                    str << " custom mipmaps";
                }
                if(multiImage)
                    str << " from multiple Images.";
                else
                    str << " from Image.";
            }

            // Scoped
            {
				/*
                // Print data about first destination surface
                HardwarePixelBufferSharedPtr buf = getBuffer(0, 0); 
                str << " Internal format is " << PixelUtil::getFormatName(buf->getFormat()) << 
                "," << buf->getWidth() << "x" << buf->getHeight() << "x" << buf->getDepth() << ".";
				*/
            }
            LogManager::getSingleton().logMessage( 
                    LML_NORMAL, str.str());
        }
        
        // Main loading loop
        // imageMips == 0 if the image has no custom mipmaps, otherwise contains the number of custom mips
        for(size_t mip = 0; mip <= std::min(mNumMipmaps, imageMips); ++mip)
        {
            for(size_t i = 0; i < faces; ++i)
            {
                PixelBox src;
                if(multiImage)
                {
                    // Load from multiple images
                    src = images[i]->getPixelBox(0, mip);
                }
                else
                {
                    // Load from faces of images[0]
                    src = images[0]->getPixelBox(i, mip);
                }
    
                // Sets to treated format in case is difference
                src.format = mSrcFormat;

                if(mGamma != 1.0f) {
                    // Apply gamma correction
                    // Do not overwrite original image but do gamma correction in temporary buffer
                    MemoryDataStream buf(PixelUtil::getMemorySize(src.getWidth(), src.getHeight(),
                                                                  src.getDepth(), src.format));

                    PixelBox corrected = PixelBox(src.getWidth(), src.getHeight(), src.getDepth(), src.format, buf.getPtr());
                    PixelUtil::bulkPixelConversion(src, corrected);
                    
                    Image::applyGamma(static_cast<uint8*>(corrected.data), mGamma, corrected.getConsecutiveSize(), 
                        static_cast<uchar>(PixelUtil::getNumElemBits(src.format)));
    
                    // Destination: entire texture. blitFromMemory does the scaling to
                    // a power of two for us when needed
                    getBuffer(i, mip)->blitFromMemory(corrected);
                }
                else 
                {
                    // Destination: entire texture. blitFromMemory does the scaling to
                    // a power of two for us when needed
                    getBuffer(i, mip)->blitFromMemory(src);
                }
                
            }
        }
        // Update size (the final size, not including temp space)
        mSize = getNumFaces() * PixelUtil::getMemorySize(mWidth, mHeight, mDepth, mFormat);

    }`

So I don't have a problem with ressource recreation for normal textures. But RenderTarget Textures are also not recreated? Do I have to do that for myself?

**Comment by paroj** [comment]
another duplicate:
https://forums.ogre3d.org/viewtopic.php?f=2&t=94699

**Comment by paroj** [comment]
so basically the multi device functionality in D3D9 is horribly broken ATM. The workaround in #994 prevents the crash at the cost of not restored resources.

> to fix this we should probably use the notify mechanism instead of
recrating the texture in getBuffer.

**Comment by paroj** [comment]
after #1000 there is no longer an endless loop/ freeze and moving the application back to original screen works. So the original issue is solved. Feel free to open follow-ups for the remaining problems.
