### ISSUE TITLE
TextAreaOverlayElement text not showing up until window resize

### ISSUE THREAD

**Issue by marko213** [OGRECave/ogre#725]
#### System Information
- Ogre Version: 1.11.0dev
- Operating System / Platform: Ubuntu 32-bit
- RenderSystem: GL

<br/>

The bug only seems to affect TextAreas either loaded from .overlay files or created before any rendering calls.

There is an old thread regarding this very issue [here](https://forums.ogre3d.org/viewtopic.php?f=2&t=58047&start=0), but it doesn't seem to have been resolved officialy. From there, the problem seems to be a missing `mpFont->load();` and possibly some material management.

There is also a proposed [solution](https://forums.ogre3d.org/viewtopic.php?f=2&t=58047&start=0#p403848), which *could* be used:
> I moved the code to updatePositionGeometry():
> ```
> void TextAreaOverlayElement::updatePositionGeometry()
>    {
>        float *pVert;
>
>        if (mpFont.isNull())
>        {
>            // not initialised yet, probably due to the order of creation in a template
>            return;
>        }
>
>        // On-demand load
>        // Moved from setFontName to avoid issues with background parsing of scripts
>        if (mpMaterial.isNull())
>        {
>            mpFont->load();
>            // Ugly hack, but we need to override for lazy-load
>            *const_cast<MaterialPtr*>(&mpMaterial) = mpFont->getMaterial();
>            mpMaterial->setDepthCheckEnabled(false);
>            mpMaterial->setLightingEnabled(false);
>        }
> ```
> And it fixes the issue, but I doubt its the most suitable place and if there is any affect to the background loading process...

(Matching current code is in [TextAreaOverlayElement::getMaterial](https://github.com/OGRECave/ogre/blob/f2fbd78d3776647a69c6380ff728b84575b48118/Components/Overlay/src/OgreTextAreaOverlayElement.cpp#L453))

However I don't know whether this could harm said process, so no PR at the moment.

**Comment by paroj** [comment]
fixed in latest 1.12
