### ISSUE TITLE
An error occurred when make ogre 1.10.0 on MinGW 

### ISSUE THREAD

**Issue by gqy2468** [OGRECave/ogre#732]
#### System Information
- Ogre Version: 1.10.0
- Operating System / Platform: Windows 7 x64 MinGW/MSYS
- RenderSystem: Direct3D9

#### Detailled description
When make on MinGW, an error occurred as follows:

d:\mingw\lib\gcc\mingw32\6.3.0\include\xmmintrin.h:193:1: error: inlining failed
 in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific o
ption mismatch

**Comment by gqy2468** [comment]
I have resolved this problem by adding -msse as follows: 

if (MINGW)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse")
  ...
endif ()

**Comment by paroj** [comment]
the current release is 1.10.11, where this issue does not exist
