### ISSUE TITLE
Make error: '_locale_t' does not name a type

### ISSUE THREAD

**Issue by gqy2468** [OGRECave/ogre#741]
#### System Information
- Ogre Version: 1.10.10
- Operating System / Platform: Win7 64bit MinGW
- RenderSystem: OpenGL

#### Detailled description
Error occured when make: 

D:/Documents/Downloads/ogre-1.10.10/OgreMain/include/OgreString.h:61:21: error:
'_locale_t' does not name a type

**Comment by paroj** [comment]
is this mingw or mingw-w64?

**Comment by gqy2468** [comment]
I'm using mingw, not mingw-w64! Has the issue been fixed?
