### ISSUE TITLE
OSX "externalWindowHandle" does not work in Debug mode

### ISSUE THREAD

**Issue by Martin-Idel-SI** [OGRECave/ogre#745]
#### System Information
- Ogre Version: 1.10.11
- Operating System / Platform:  Mac OSX
- RenderSystem:  OpenGL

#### Detailed description
Setting up a simple render system using "externalWindowHandle" on Mac works in Release mode but not in Debug mode. 

In order to embed our application into a Qt-GUI, we use "externalWindowHandle" (https://github.com/ros2/rviz). This has problems on Mac. The issue can be reproduced with the following more or less minimal example: 
We use the following test:
```
#include <gtest/gtest.h>
#include "test_render_system.hpp"

TEST(SAMPLE_TEST, no_name) {
  test_namespace::RenderSystem::get();

  ASSERT_TRUE(true);
}
```
in common with the following rather minimal render system setup:

https://gist.github.com/Martin-Idel-SI/d07d16d4d4de19d6bad307c57520edc0
https://gist.github.com/Martin-Idel-SI/1e5611850678970b58fa1690e28f6b8e

(note that the paths to plugins and resource directory need to be adjusted).
The behaviour is the following:

- Build Ogre + test in Release or RelWithDebugInfo and the test passes
- Build Ogre + test in Debug and the test fails with

```
Assertion failed: ([externalHandle isKindOfClass:[NSView class]]), function create, file .../ogre-master-ca665a6-prefix/src/ogre-master-ca665a6/RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm, line 334.
```
It turns out that while in Debug mode, the corresponding assert here: 
https://github.com/OGRECave/ogre/blob/79546907fa3ffcfa97d5e7b341aa4f5a0253e54e/RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm#L327
fails because the handle is 0, in Release mode, the handle is nonzero.

The behaviour can also be observed when building the whole application in Debug mode and running it on Mac - see issue https://github.com/ros2/rviz/issues/246

We had even larger issues with 1.10.10, so maybe some of this was fixed in and the problem is also related to https://github.com/OGRECave/ogre/commit/231877ed943b613e791abc1f7294bc48cb8c8b05 ?

**Comment by paroj** [comment]
> fails because the handle is 0, in Release mode, the handle is nonzero.

in your test code, the handle is also 0 in Release mode - the assert is just disabled there.

from what I see, you are not supposed to pass 0 there, but rather create a dummy NSView*, similar to what you do on linux:
https://github.com/ros2/rviz/blob/ros2/rviz_rendering/src/rviz_rendering/render_system.cpp#L173

**Comment by Martin-Idel-SI** [comment]
Thank you for a quick reply!
What you describe is what I would have expected. But it seems not the case, because what we see in Release mode is that:

- everything works as expected, we obtain an embedded render window and everything works as on Linux or Windows,
- when stepping into the function with GDB, we see that for some reason the NSView number is not zero (it is in debug as the failing assert also tells us, but something weird is going on in the Debugger, so I'm not entirely sure I can trust everything). If it were 0, I would have expected the cast after the assert to fail or anything being done afterwards (but just as you, I don't have any idea about OSX/Cocoa...). It's very weird.

**Comment by paroj** [comment]
to add some details from our internal discussion:
* In obj c, nullptrs being called is just a no-op and return values are zero, thus both ptrs become null. If the user is later providing the handles again somehow, it may explain why it works. 
* the assert reveals the problem, client should debug it rather than hide and fall flat later due memory corruption

therefore I am marking this invalid for now.

**Comment by Martin-Idel-SI** [comment]
Thanks for looking into this!

I'm still a bit confused, because I would have expected weird behaviour in Release mode when entering code after and `assert`, but by just wrapping the `externalWindowHandle` into an if statement and not setting it if it's 0, everything works correctly, but that's a different issue.

Since that resolves the problem and it's not a bug, I'm happy.
