### ISSUE TITLE
Missing ItemNotFoundException

### ISSUE THREAD

**Issue by karamellpelle** [OGRECave/ogre#764]
#### System Information
- Ogre Version: 1.11

#### Detailled description
There is no `ItemNotFoundException` in _OgreException.h_. Instead `ItemIdentityException` is used which is misleading (I got fooled). See [OgreException.h](https://github.com/OGRECave/ogre/blob/873c7d7ac1b27d8a7349fd2210332aeba786ec73/OgreMain/include/OgreException.h#L267)

**Comment by paroj** [comment]
changing this would break applications that are currently catching `ItemIdentityException` which is not worth it.

**Comment by paroj** [comment]
maybe this change would be enough in your case though:
https://github.com/OGRECave/ogre/pull/763/commits/56f5c0470c02abc367d9a42c962424556f69947b
