### ISSUE TITLE
App crashes when I put the app in recent tabs and open it again

### ISSUE THREAD

**Issue by pzdawood** [OGRECave/ogre#768]
### Actual behaviour
When I open the orgesamplebrowser app and and put it into recent tabs or background . Then I open the app again it gets crashed.

### How to reproduce
* Download the orgesamplebrowser app .
* Install this app.
* Open the orgesamplebrowser app.
* Put it into recent tabs or background .
* Open the app again.
* When I open the app again app crashes.
* Browser:orgesamplebrowser.
* Version: 1.10.11
* Operating system: 7.1.2
### Recording of the bug
https://youtu.be/lKHRdINRwsg

**Comment by paroj** [comment]
please record a log of when then app crashes using logcat:
https://developer.android.com/studio/debug/am-logcat

**Comment by paroj** [comment]
no reply by author. Also this is a (potentially) paid report by Utopian:
https://steemit.com/utopian-io/@alexcarlos/app-gets-crashed-when-i-put-the-app-in-recent-tabs-and-open-it-again
