### ISSUE TITLE
Inconsistent order of SceneManager::setShadowTechnique in the examples

### ISSUE THREAD

**Issue by karamellpelle** [OGRECave/ogre#775]
#### System Information
- Ogre Version: 1-11-1 
- Operating System / Platform: macOS High Sierra
- RenderSystem: RenderSystem_GL3Plus

#### Detailled description
The tutorial states that enabling shadowing technique should be be the first thing you do during scene setup, see [Manual > Enabling shadows](https://ogrecave.github.io/ogre/api/1.11/_shadows.html).

This is not done in for example _Samples/Tutorials/BasicTutorial.cpp_ and _Samples/Terrain/include/Terrain.h_.

**Comment by paroj** [comment]
The Terrain sample is about switching shadow techniques, so it takes special caution. Also generally, when keeping to texture shadows, this restriction does not apply.
