### ISSUE TITLE
Is there any way to make an entity to be close to a plane ?

### ISSUE THREAD

**Issue by gqy2468** [OGRECave/ogre#779]
#### System Information
- Ogre Version: :grey_question:  1.10.0
- Operating System / Platform: :grey_question:  ubuntu
- RenderSystem: :grey_question:  opengl

#### Detailled description
Is there any way to make an entity to be close to a plane, for example a person walk on the ground ?!
Now I can't get the right position of the bone after rolled or pitched !!

**Comment by paroj** [comment]
see the character sample:
https://github.com/OGRECave/ogre/tree/master/Samples/Character/include

**Comment by gqy2468** [comment]
I use the following code to show the model on the ground, but there is a small gap between the thigh bone of the model and the ground !!! And when the thigh bone of the model rolled or pitched, the 
gap size will become bigger !!! Is there any way to make the gap size to zero ?! Thanks !!!

```
float bottom = -100;
Plane plane(Vector3::UNIT_Y, bottom);
... ...
Entity* model = mSceneMgr->createEntity("entity", "ninja.mesh");
... ...
mSceneMgr->getRootSceneNode()->createChildSceneNode(Vector3::UNIT_Y * bottom)->attachObject(model);
```
