### ISSUE TITLE
Emscripten project compilation problem!

### ISSUE THREAD

**Issue by OgreShader** [OGRECave/ogre#803]
The C compiler identification is MSVC 18.0.40629.0
The CXX compiler identification is MSVC 18.0.40629.0
Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:8 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:16 (file):
  file COPY cannot find
  "E:/ogre-master/ogre-master/Samples/Emscripten/Samples/Emscripten/media".

CMake Error at CMakeLists.txt:20 (file):
  file COPY cannot find
  "E:/ogre-master/ogre-master/Samples/Emscripten/Samples/Media/materials/textures/ribbonband.png".

CMake Error at CMakeLists.txt:27 (file):
  file COPY cannot find
  "E:/ogre-master/ogre-master/Samples/Emscripten/Samples/Media/RTShaderLib/GLSL".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!
See also "E:/ogre-master/ogre-master/Samples/Emscripten/CMakeFiles/CMakeOutput.log".

Cmake error!

**Comment by paroj** [comment]
please note that this tracker is for bugs in ogre only. For user support see https://forums.ogre3d.org/
