### ISSUE TITLE
crash in Ogre::Root::getSingleton().createRenderWindow

### ISSUE THREAD

**Issue by stefanroellin** [OGRECave/ogre#814]
I use OGRE in a Qt application for linux as well as for windows. For both platforms, I use the GL RenderSystem. Until now I have used 1.10.8. 
Now, I have updated to 1.11.1. Under linux everything works as expected. However under windows, I observe a crash during the call
```
Ogre::Root::getSingleton().createRenderWindow(...) 
```
and there in the file RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp 
at the line:

            // Pass pointer to self as WM_CREATE parameter
            mHWnd = CreateWindowEx(dwStyleEx, "OgreGLWindow", title.c_str(),
                getWindowStyle(fullScreen), mLeft, mTop, mWidth, mHeight, parent, 0, hInst, this);

A git bisect shows that the crash can be observed since the following commit:

```
commit aa90530a586d1c484abdf8be316838afe27c7bd1
Author: Pavel Rojtberg <rojtberg@gmail.com>
Date:   Mon Jan 29 19:18:43 2018 +0100

    Main: move WindowEventUtilities to Bites

    actually they are pretty useless, but maybe somebody relies on this.
```

The following patch solves the crash for me, however I don't know, whether this makes any sense:

```
--- a/RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp
+++ b/RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp
@@ -380,7 +380,7 @@ namespace Ogre {
                 classStyle |= CS_DBLCLKS;

             // register class and create window
-            WNDCLASS wc = { classStyle, NULL, 0, 0, hInst,
+            WNDCLASS wc = { classStyle, DefWindowProc, 0, 0, hInst,
                 LoadIcon(NULL, IDI_APPLICATION), LoadCursor(NULL, IDC_ARROW),
                 (HBRUSH)GetStockObject(BLACK_BRUSH), NULL, "OgreGLWindow" };
             RegisterClass(&wc);
```

**Comment by paroj** [comment]
the patch seems valid. Can you create a pull request?
