### ISSUE TITLE
"Ogre::Singleton<Ogre::Root>::msSingleton" is undefined on macOS

### ISSUE THREAD

**Issue by dweckmann** [OGRECave/ogre#815]
#### System Information
- Ogre Version: :grey_question: 1.11
- Operating System / Platform: :grey_question: macOS sierra 10.13.6 (17G65) - Apple LLVM version 9.1.0 (clang-902.0.39.2)
- RenderSystem: :grey_question:  OpenGL 3+

#### Detailled description
After commit https://github.com/OGRECave/ogre/commit/373b1ecf2dbc163bb910b2d4e7b8cf8cce74437e#diff-c6b312e582e9412303a9b6dfed405901, putting code like `::Ogre::Root* root = ::Ogre::Singleton< ::Ogre::Root >::getSingletonPtr();` leads to a link error: 

```
Undefined symbols for architecture x86_64:
  "Ogre::Singleton<Ogre::Root>::msSingleton", referenced from:
      Ogre::Singleton<Ogre::Root>::getSingletonPtr() in xxxx.cpp.o
```

**Comment by paroj** [comment]
to me this is the correct behavior. msSingleton is supposed to be explicitly instantiated in somewhere.

**Comment by dweckmann** [comment]
Well, I prefer to think there is a visibility problem on macOS, because before the commit that precisely change the default visibility of some components, everything was working fine and the exact same code work well on linux and windows. I don't know yet why this commit is handled differently on macOS target, but I really doubt `<Ogre::Root>` is not explicitly instantiated in somewhere. I will also add that a declaration somewhere should be enough as we talk about missing symbols, not null pointer.

**Comment by paroj** [comment]
Using your code I also get an undefined reference on linux with
`gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)`

Note that we are not talking about instantiation of `Ogre::Root`, but `Ogre::Singleton<Ogre::Root>::msSingleton`.

**Comment by dweckmann** [comment]
You are right, with `::Ogre::Root* root = ::Ogre::Root::getSingletonPtr();` things work like expected.

**Comment by felixf4xu** [comment]
> to me this is the correct behavior. msSingleton is supposed to be explicitly instantiated in somewhere.

Is there any example to instantiate `msSingleton`?

I have a runtime crash here `assert( msSingleton );`:
https://github.com/OGRECave/ogre/blob/b9fbf7da95a9de887944de0633ea77983988c375/OgreMain/src/OgreTextureManager.cpp#L33-L41

If it's designed to instantiate it **somewhere**, I'd like to know **where** to instantiate it.

**Comment by paroj** [comment]
https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_singleton.html#details

**Comment by felixf4xu** [comment]
pardon me if I have hijacked this thread, but I'm really struggling debugging a `assert( msSingleton )` crash.

What I'm looking for is some code to assign a value for `::msSingleton`.

I have searched in the **Sample** folder, but I did not find the assignment code, could you give me a hint to search?
