### ISSUE TITLE
Error occured when loading facial.mesh 

### ISSUE THREAD

**Issue by gqy2468** [OGRECave/ogre#819]
#### System Information
- Ogre Version: 1.10.10
- Operating System / Platform: macos 10.13
- RenderSystem: OpenGL

#### Detailled description
Error occured when loading facial.mesh:
`Segmentation fault: 11`

#### Ogre.log
```
15:33:26: InvalidParametersException: Named constants have not been initialised, perhaps a compile error. in GpuProgramParameters::_findNamedConstantDefinition at /Users/guoqiya/Downloads/ogre-1.10.10/OgreMain/src/OgreGpuProgramParams.cpp (line 2194)
15:33:26: InvalidParametersException: Named constants have not been initialised, perhaps a compile error. in GpuProgramParameters::_findNamedConstantDefinition at /Users/guoqiya/Downloads/ogre-1.10.10/OgreMain/src/OgreGpuProgramParams.cpp (line 2194)
```

**Comment by paroj** [comment]
we do not support already released versions. Please try again with latest master. If you must stick with 1.10.x please update to 1.10.12.
