### ISSUE TITLE
GL3Plus shader patching bug

### ISSUE THREAD

**Issue by 1k0** [OGRECave/ogre#841]
#### System Information
- Ogre Version: 1 master 
- Operating System / Platform: OSX, (can be triggered in Windows too) 
- RenderSystem: GL3Plus

#### Detailled description
Under GL3PlusRendersystem in OgreGLSLShader.cpp in void GLSLShader::submitSource() function, shader patching gives wrong results if, "shouldUpgradeToVersion150" boolean is triggered. (This boolean triggers in OSX, but the error can be reproduced under Windows too, if you set the boolean manually to true)

Wrong results include no image under Windows, and garbage under OSX.

This bug is caused by if(shouldUpgradeToVersion150) block (line 179). In my opinion prefixFp shader patch constant string should NOT contain the following text.

"#define gl_FragColor FragColor\n"
"out vec4 FragColor;\n"

This snippet messes up fragment shaders, with custom out declaration. Because if you write to a custom defined output in the fragment shader, rather than using the "built in" gl_FragColor, you will have an MRT (Multi Render Target) situation, instead of the intended single render target.

In my opinion the whole prefixFp and prefixVp patching is problematic. These patches encourage the usage of deprecated glsl functions/symbols. An alternate solution would be, to drop the deprecated glsl symbol support in glsl130+, and log an error if someone uses deprecated symbols in glsl130+. This way the shader patcher would only need to redefine the glsl version to 150 in OSX, so (non deprecated) 130 and 140 shaders could run.

**Comment by paroj** [comment]
yes, there should be a check whether the shader actually uses gl_FragColor. Can you provide a pull request?

> These patches encourage the usage of deprecated glsl functions/symbols. 

yes we want to support shader sharing between GLES2 and GL3+. Allowing using the minimal GLSL version is part of it.

**Comment by paroj** [comment]
> This is the reason for SSO redeclaration too

yes, to allow using the same shaders with and without SSO (where the redaclaration is not needed)

giving this low priority for now as this only affects MRT shaders and simple workaround by using #version 150 exists.
