### ISSUE TITLE
[Emscripten/Webassembly] Unable to build ogre3D due to the missing cmake variables for ogre depenencies.

### ISSUE THREAD

**Issue by Apivan** [OGRECave/ogre#852]
#### System Information
- Ogre Version: : OGRE 1.11.2 (Obtained from GIT tag)
- Operating System / Platform:: **Unix Makefiles Emscripten Webassembly**

#### Detailled description
There was an error building ogre's using **Emscripten**.  The problem is not reproducible with gcc or msvc.
The patch below fix my problem.

```
diff --git a/CMake/Dependencies.cmake b/CMake/Dependencies.cmake
index c0603acd9..082f49921 100644
--- a/CMake/Dependencies.cmake
+++ b/CMake/Dependencies.cmake
@@ -128,6 +128,8 @@ if(OGRE_BUILD_DEPENDENCIES AND NOT EXISTS ${OGREDEPS_PATH})
     execute_process(COMMAND ${CMAKE_COMMAND}
         -DCMAKE_INSTALL_PREFIX=${OGREDEPS_PATH}
         -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
+        -DZLIB_LIBRARY=${CMAKE_BINARY_DIR}/Dependencies/lib
+        -DZLIB_INCLUDE_DIR=${CMAKE_BINARY_DIR}/Dependencies/include
         -DZLIB_ROOT=${OGREDEPS_PATH}
         -DBUILD_SHARED_LIBS=${OGREDEPS_SHARED}
         -G ${CMAKE_GENERATOR}
```

And, I noticed that the zziplib download the master version (ZZIPlib-master.tar.gz) instead of fixed version.  This might be the reason why the build module used to work.

**Comment by paroj** [comment]
which CMake version are you using? this should be already handled by ZLIB_ROOT:
https://github.com/Kitware/CMake/blob/v3.11.0/Modules/FindZLIB.cmake#L49

**Comment by Apivan** [comment]
The problem is reproducible using CMake 3.12.0. I found that structure of **Dependencies folder** is different between Emscripten toolchain and native toolchain (gcc). Please notice the **zlib.h**

And, the patch I added above only work with Emscripten toolchain. (must rf -rf * the build folder and then retry).

Emscripten toolchain

```
.
├── include
│   ├── freetype2
│   │   ├── freetype
│   │   │   ├── free type stuffs ..
│   │   └── ft2build.h
│   ├── zconf.h
│   ├── zlib.h
│   └── zzip
│       ├── conf.h
│       ├── _config.h
│       ├── fetch.h
│       ├── _msvc.h
│       ├── plugin.h
│       ├── types.h
│       └── zzip.h
├── lib
│   ├── cmake
│   │   └── freetype
│   │       ├── freetype-config.cmake
│   │       └── freetype-config-relwithdebinfo.cmake
│   ├── libfreetype.a
│   ├── libz.a
│   ├── libz.so -> libz.so.1
│   ├── libz.so.1 -> libz.so.1.2.11
│   ├── libz.so.1.2.11
│   └── libzzip.a
└── share
    ├── man
    │   └── man3
    │       └── zlib.3
    └── pkgconfig
        └── zlib.pc
```

Native toolchain (gcc)
```

├── include
│   ├── freetype2
│   │   ├── freetype
│   │   │   ├── free type stuffs ...
│   │   └── ft2build.h
│   └── zzip
│       ├── conf.h
│       ├── _config.h
│       ├── fetch.h
│       ├── _msvc.h
│       ├── plugin.h
│       ├── types.h
│       └── zzip.h
└── lib
    ├── cmake
    │   └── freetype
    │       ├── freetype-config.cmake
    │       └── freetype-config-relwithdebinfo.cmake
    ├── libfreetype.so -> libfreetype.so.2.9
    ├── libfreetype.so.2.9 -> libfreetype.so.2.9.0
    ├── libfreetype.so.2.9.0
    └── libzzip.so
```

**Comment by paroj** [comment]
this is why:

https://github.com/OGRECave/ogre/blob/a92b83d0b3205e825206f9f010aa51e111e4ae12/CMake/Dependencies.cmake#L101-L102

I could reproduce the problem though. The correct solution is to forward CMAKE_FIND_ROOT_PATH when cross compiling
