### ISSUE TITLE
null string in X11EGLWindow::create

### ISSUE THREAD

**Issue by Luomin1993** [OGRECave/ogre#864]
first ,beacause I meet issue when building JAVA lib for ogre, so I didn't choose javalib in cmake-gui...

then I finish BUILD without issues,but,

I can't run "SampleBrowser" in build/bin and I got

" " "
X11EGLWindow::create used FBConfig = 8/8/8/8
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

" " "

then I try to build the Samples/Tutorials/ but I got:
" " "
CMake Error in CMakeLists.txt:
  Imported target "RenderSystem_GL3Plus" includes non-existent path

    /usr/local/include/OGRE/RenderSystems/GL3Plus/GLSL

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

   The path was deleted, renamed, or moved to another location.

  An install or uninstall procedure did not complete successfully.

   The installation package was faulty and references files it does not
  provide.

" " "

Why ? Wish help and Thanks

**Comment by paroj** [comment]
can you provide a backtrace for the first crash?

start as `gdb ./Samplebrowser` then type `bt` after the crash happened

**Comment by paroj** [comment]
no reply by reporter/ cannot reproduce
