### ISSUE TITLE
OGRE includes some non-free content

### ISSUE THREAD

**Issue by ignatenkobrain** [OGRECave/ogre#882]
* [x] Samples/Media/packs/chiropteraDM.*
* [x] Samples/Media/materials/textures/nvidia/*

I'm not sure what exact license is, but Fedora Legal team (I think) said that those are non-free and we have to remove them from tarball.

This is inconvenient for me as of ogre maintainer in Fedora.

**Comment by paroj** [comment]
should take a look at https://github.com/stuntrally/stuntrally/tree/master/data
for replacements.
