### ISSUE TITLE
PF_RG8 doesn't work

### ISSUE THREAD

**Issue by AndreAhmed** [OGRECave/ogre#936]
Hi,
I'm trying to use ARKit with Opengles3 on ogre 1.10, the problem is there is no chrome, I used the extension PF_RG8 for the chrome texture and only a gray scale image that works which means the luminance is just working. I think it's a bug.

**Comment by paroj** [comment]
which version exactly? also do you have a screenshot and testdata?

**Comment by AndreAhmed** [comment]
The question is which PF format should I use for Opengles3 for Y and for UV ?

**Comment by AndreAhmed** [comment]
OpenGL error 0x0502 GL_INVALID_OPERATION in virtual void Ogre::GLES2TextureBuffer::upload(const Ogre::PixelBox &, const Image::Box &) at line 446 for glTexSubImage2D

**Comment by paroj** [comment]
you need at least v1.10.9 for PF_RG8 to work properly.

> The question is which PF format should I use for Opengles3 for Y and for UV ?

it depends on the YUV pixel format - eg.g YUV422 fully fits into PF_RG8, while for YUV420p, you will likely need two textures or a custom shader for unpacking.

marking as invalid as we only track issues with master here.
