### ISSUE TITLE
RTSS can't generate SM4+ shaders

### ISSUE THREAD

**Issue by TheNicker** [OGRECave/ogre#973]
#### System Information
- Ogre Version: : latest 
- Operating System / Platform: windows 10 1803 /x64
- RenderSystem: Direct3D11

#### Detailled description
The RTSS in its current form is unable to compile shader model 4.0 hlsl code.
Though the samples provided with Ogre don't use any modern functionality, users are using shader model 4.0 , 5.0 and 5.1 with Direct3D11 and the RTSS.

**Comment by TheNicker** [comment]
I tend to agree with you about what should be done, but one thing that hasn't been taken into consideration is the fact that the RTSS did support SM4 for sometime now it has been dropped off and implementations are broken without providing an alternative.
For that reason I would set the priority of this issue to the maximum possible.

**Comment by paroj** [comment]
this is not a regression as we explicitly dropped it with the 1.11 release. See:
https://github.com/OGRECave/ogre/blob/master/Docs/1.11-Notes.md#rt-shader-system

although the wording is not clear enough that SM4 is no longer supported.

Anyway your options are:
* stick with 1.10.12
* downgrade your RTSS modules to SM3
* provide an implementation that can be integrated in 1.11/ 1.12 RTSS
* copy paste the 1.10.12 implementation and maintain it in parallel to whatever happens upstream
