### ISSUE TITLE
Sharing metal texture with ogre

### ISSUE THREAD

**Issue by AndreAhmed** [OGRECave/ogre#983]
Hi,
I have a texture MTL and I would like to share it with OgreTexture.. is that possible ? I modified ogre so that it accepts a texture ID and draws, binds it.

From the documentation, it says they should share the same IsoSurface.. how is that possible with ogre 1.10 ?

**Comment by paroj** [comment]
no idea.. but if you find out, please create a pull request with a sample.

note that we recently had a PR adding external textures for android: https://github.com/OGRECave/ogre/pull/914

maybe you can use that as a reference
