### ISSUE TITLE
Texture unit state setBlank() do not reset animated texture controller

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#992]
#### System Information
- Ogre Version: 1.11.1: 
- Operating System / Platform: Windows
- RenderSystem: OpenGL

#### Detailled description
Texture unit state setBlank() do not reset animated texture and controller frame
This result to a crash in next render call in TextureFrameControllerValue::setValue(Real value)
with a division by 0

**Comment by paroj** [comment]
yeah.. that was incomplete. see 052377b93be5943c748bb5e51fe3c1ba0fa72aa0

**Comment by arkeon7** [comment]
good thanks
